### ISSUE TITLE
Automatic breaks on a highstock chart not working

### ISSUE THREAD

**Issue by idanmiller** [whawker/react-jsx-highcharts#104]
Hi,

I have ported a highstock chart from using react-highcharts to using react-jsx-highstock.
All is well, except that on the former library, gaps in the time on the x axis were ignored, i.e. the graph didn't show an empty part, but skipped them, as if defining the xAxis.breaks property automatically.

However, I couldn't have the same functionality when using react-jsx-highstock...
I think the problem lies in the fact I have to define a <XAxis /> and so when doing so have to define breaks.

In the former config, there was no definition of xAxis at all, and so breaks weren't needed.

Could this be fixed?

Thanks,
Idan

**Comment by whawker** [comment]
Would you be able to post an example chart, either the code or a picture of before and after? 

I've had a quick browse of the react-highcharts codebase, and I can't see anything specific to breaks.

**Comment by madagithub** [comment]
I'm attaching the entire component code.
Note that there are no xAxis definitions, which from my understanding is what's causing it not to break, but I'm not entirely sure.
I can say that I've moved to highcharts-react and everything works well there as well.
If this will be resolved I'm hoping to move back to react-jsx-highcharts as it's much more convenient...

Code is here: 
https://jsfiddle.net/888tb73f/

Thanks,
Idan

**Comment by whawker** [comment]
Hi @madagithub, I am unable to run your example, as the `data` and `fetched` props are provided via Redux connect, but obviously there in no store. Therefore I'm not sure what shape data the Graph consumes.

P.s. I would recommend using [StackBlitz](https://stackblitz.com/) or [CodeSandbox](https://codesandbox.com/) over JSFiddle for ES6 React demos.

**Comment by ismusidhu** [comment]
@madagithub you can easily fork from https://stackblitz.com/edit/base-chart-example to demonstrate your problem

**Comment by idanmiller** [comment]
@whawker Seems that no, as I already did the suggested import.
I will try hopefully this week to fork and demonstrate the problem.
Currently using the official highcharts react component so not stuck, but will be happy to move to react-jsx-highcharts if this issue is resolved.

**Comment by idanmiller** [comment]
Hi eveyone,

Sorry this took so long.

Here's my reproduction of the issue:
https://stackblitz.com/edit/base-chart-example-l78cdn?file=MyChart.js

I indeed forked as @ismusidhu suggested from the basic example.

Note that there is a gap between candles that have missing times.
This happens in real data between end of trade of one day to the start of trade in the next day.
Now, in the regular highcharts component, I just didn't specify an XAxis.
And so, the gaps simply were ignored.

However, in react-jsx-highcharts I have to sepcify XAxis (I get error 18 if not), and when doing so I get the gaps.

Hope all is clear now.

Thanks,
Idan

**Comment by whawker** [comment]
Hi @idanmiller after much digging around, it seems the workaround is quite simple 

Simply add the `ordinal` prop to your `XAxis` ([Ordinal docs](https://api.highcharts.com/highstock/xAxis.ordinal))
```jsx
<XAxis ordinal>
  <XAxis.Title>Time</XAxis.Title>
</XAxis>
```

This is the default on a stock chart usually ([see here](https://github.com/highcharts/highcharts/blob/master/js/parts/StockChart.js#L162-L174)) but I haven't replicated this properly in React JSX Stockcharts

I might raise a bug on Highcharts, as I think these defaults should also apply to dynamically added axes.

**Comment by whawker** [comment]
Opened https://github.com/highcharts/highcharts/issues/8603

**Comment by idanmiller** [comment]
@whawker Thanks!

**Comment by anajavi** [comment]
https://github.com/highcharts/highcharts/issues/8603 has been fixed in the highcharts@9.1.0.

Can we close this issue now?

**Comment by anajavi** [comment]
Closing this as it is fixed on highcharts
