### ISSUE TITLE
Highstock Navigator not working

### ISSUE THREAD

**Issue by LorenzWieseke** [whawker/react-jsx-highcharts#105]
As soon as I use the Navigator form the highstock lib I get an error saying 

Highcharts Error #18
The requested axis does not exist
This error happens when you set a series' xAxis or yAxis property to point to an axis that does not exist.

![image](https://user-images.githubusercontent.com/29607121/40253148-f9c205f2-5ade-11e8-8f7d-9d9ea29c5e00.png)

Im using "react-jsx-highstock": "^2.3.0-alpha.2" and "highcharts": "^5.0.0"

Highchart it self seems to work just fine.

**Comment by whawker** [comment]
Ah, you shouldn't have got the alpha version yet it's not stable. That's weird!

Does it work if you `npm install --save react-jsx-highstock@2.2.1` ?

**Comment by anajavi** [comment]
This is probably the same problem as in #46.

**Comment by LorenzWieseke** [comment]
Thanks ! Thats it !

**Comment by whawker** [comment]
Awesome, thanks @anajavi!
