### ISSUE TITLE
Resize animation

### ISSUE THREAD

**Issue by quirk0o** [whawker/react-jsx-highcharts#107]
Hello,

I'm dynamically resizing the diameter of a pie chart and the animation is really strange. I'm changing both the `width` and `height` of the `Chart` component as well as the `size` of the `PieSeries` because I want a specific size without any labels etc. Here's a clip:

![donut-issue](https://user-images.githubusercontent.com/5123725/40497703-32e9009a-5f7d-11e8-9f3e-b7ddbb7573be.gif)

Is this a problem with `react-jsx-highcharts` or just with `highcharts`?

**Comment by whawker** [comment]
Hmm interesting, have you tried explicitly defining the center? As mentioned [here](https://api.highcharts.com/highcharts/series.pie.center)?

**Comment by quirk0o** [comment]
I have tried setting the center to `['50%', '50%']` but it didn't change anything.

**Comment by whawker** [comment]
Would it be possible to share the code you're using to help me to debug?

**Comment by quirk0o** [comment]
Of course, apologies.
Here's a minimal repro:

https://codesandbox.io/s/pprnxq2q4j

**Comment by whawker** [comment]
Ahhh ok, looks the toggle in completely destroying the chart
i.e.
```jsx
const SocialDonut = ({ expanded, data }) =>
  !expanded ? <BabyDonut data={data} /> : <ExpandedDonut data={data} />;
```

This means previous chart instance is destroyed, and a completely new chart is created in it's place.

Ideally the same chart should be used, just update the props you pass to it.

[Example here](https://codesandbox.io/s/ko4k7zj657), `BabyDonut` and `ExpandedDonut` removed, using `SocialDonut` with updating props.

**Comment by quirk0o** [comment]
I'm still getting the same effect in my codebase after applying these changes. The chart is contained within a Flex and later CSS Grid. Is it possible that this is affecting it's positioning?

**Comment by whawker** [comment]
It's possible, but difficult to say without seeing the code.

Is it possible to share what you chart code looks like now?

**Comment by quirk0o** [comment]
Also when I use the same chart like you suggest but turn off animations I get a result that's almost okay but the bottom-right kind of eases in with a square shape:

![donut-issue-no-animation](https://user-images.githubusercontent.com/5123725/41091063-fe56a016-6a45-11e8-8b7f-0cb60712ec36.gif)

**Comment by quirk0o** [comment]
As for the code it would be hard to extract just the relevant bit and unfortunately it's not open source. I'll try to create a repro later this week.

**Comment by quirk0o** [comment]
So sorry I missed that! That does indeed help. Thanks for you help 🎉

**Comment by whawker** [comment]
No worries!
