### ISSUE TITLE
Integrate Flow typing

### ISSUE THREAD

**Issue by whawker** [whawker/react-jsx-highcharts#113]
Integrate Flow Typing for better IDE support

**Comment by anajavi** [comment]
I added flow tooling in https://github.com/anajavi/react-jsx-highcharts/tree/flow

I tried to make small example of how it would work, and it quickly became extremely complex :)

I have to take some time to think about how to make it simple and easy to use, maybe just bypass most of the HOC typings and leave only typings for the user facing component props.

I don't want to make very complex system out of this as typescript might make flow obsolete.

**Comment by bondz** [comment]
Is there an existing type def for typescript?

**Comment by whawker** [comment]
@bondz not at the moment, I'm not a fan of typescript so I can't find the motivation to add them. Would love a PR though, if you feel up to it?

**Comment by bondz** [comment]
I've written a few type definitions for JS libraries, would give this a go sometime during the weekend and send a PR.

**Comment by whawker** [comment]
@anajavi Nice work!! I also prefer the simpler approach, I would much rather provide flow typing on the external API rather than internally, as it means it's much easier to maintain.

The existing PropType definitions only define the required props for minimal functionality, does it matter if you pass additional props to a component, that aren't referenced in Flow types?

**Comment by anajavi** [comment]
Let's go with the external typings then. I will send a PR when I'm happy with it.

It doesn't seem to matter if you pass additional props, at least in my flow config, but I will check it.

As for props that are passed to highcharts: it is hard to know their types beforehand. Flow typings for highcharts would help, but I'm afraid there is no such thing.

**Comment by anajavi** [comment]
PR in #116

**Comment by anajavi** [comment]
I guess this one has gone stale.

Almost all libraries providing typings are doing it with typescript nowadays. Even Highcharts has typescript typings, which makes typing react-jsx-highcharts with typescript considerably easier.

Closing.
