### ISSUE TITLE
How to add more elements in the tooltips ? 

### ISSUE THREAD

**Issue by kweyhaupt** [whawker/react-jsx-highcharts#118]
Hi, 

First of all, thank you for this library, it helped me a lot during my current project !

Secondly, I have a question, is this possible to add another element such as a score in the tooltip in addition to the Y detailed value? 
I know that you can give to serie an array with object (ex: [{y: 42, score: 20}...] to the basic Highcharts JS library. After that you can simply retrieve the 'score' value in the tooltip formatter, but i don't know how to do this with your library.

I tried multiple solutions : 
- Add tooltip formatter in the plotOption const 
`tooltip: {
    formatter: function () {
        return 'The value for <b>' + this.score +
            '</b> is <b>' + this.y + '</b>';
    }
}`
- Create a function in my graph component which return : 'Score: <b>' + point.score + '</b>'; and give this fonction to the props formatter of my Tooltip component.

None of them worked so far, so i was wondering if there was a solution to make this work.

Regards,
Kévin

**Comment by whawker** [comment]
Hi @kweyhaupt,

You need to create a tooltip formatter function, and pass it as a prop to the tooltip, i.e. `<Tooltip formatter={fn} />`

[Example here](https://stackblitz.com/edit/rjh-tooltip-formatter?file=MyChart.js)

**N.B.**
```js
// Make sure you use the ES5 style function
function tooltipFormatter () { /* ... */ }
// or
const tooltipFormatter = function () { /* ... */ }

// Rather than ES6 (as the arrow this changes the scope of `this`)
const tooltipFormatter = () => { /* ... */ }
```

**Comment by kweyhaupt** [comment]
Hi! 

It works great ! Thank you for your fast answer !

Have a nice day. 
Regards, Kévin
