### ISSUE TITLE
LineSeries coordinates not updating

### ISSUE THREAD

**Issue by webisteme** [whawker/react-jsx-highcharts#12]
I am using a LineSeries to draw a vertical line on a graph using your package:

        <LineSeries
          data={[{x: this.props.x, y: this.props.y_end}, {x: this.props.x, y: this.props.y_start}]}
        />

The size of the line needs to change in response to other variables in the application. Unfortunately it doesn't change when the props update. This seems to have to do with the fact that it's a fixed line with start and end coordinates, as opposed to a normal data-series (e.g. a list of values)

I would appreciate your input.

**Comment by whawker** [comment]
I think the issue here is that your `<LineSeries />` requires an `id` prop. 

React JSX Highcharts requires ids so it knows which parts of the Highcharts configuration to update behind the scenes.

This should fix it (I think)
```jsx
    <LineSeries
      id="mySeries"
      data={[{x: this.props.x, y: this.props.y_end}, {x: this.props.x, y: this.props.y_start}]}
    />
```

**Comment by webisteme** [comment]
That worked, thanks!

**Comment by whawker** [comment]
No worries!
