### ISSUE TITLE
Are *all* of Highcharts features and options accessible?

### ISSUE THREAD

**Issue by lumberg72** [whawker/react-jsx-highcharts#120]
Hi, this looks like a great library. But does it impose limitations on our usage of HighCharts? HighCharts has SO many feature and configuration options, I can't imagine you have exposed *everything* through your API (I'm new to React... not sure if that's the right term).
I mean, if you have not specifically included a Highcharts option, is there always a way to get at it anyway? If so, could you provide an example?

I just know how it goes for me. If there's a highcharts option that's not available through this component... then I'll definitely need and it will drive me crazy.

Thanks!

**Comment by whawker** [comment]
Hi @lumberg72, as far as I'm aware anything you can do in Highcharts you can do with React JSX Highcharts (except maps #56).

If there isn't a specific component for a option group, you can pass it as a prop to `<HighchartsChart />`

For example, there is currently no component for [`colorAxis`](https://api.highcharts.com/highcharts/colorAxis) but we can pass it as a prop. [Example here](https://github.com/whawker/react-jsx-highcharts/blob/master/examples/Treemap/App.js#L37)

**Comment by lumberg72** [comment]
Awesome. That's what I wanted to know. And thanks for the quick reply.
