### ISSUE TITLE
Bug Next.js and jsx-highstock 3.0.1

### ISSUE THREAD

**Issue by deman4ik** [whawker/react-jsx-highcharts#121]
#### Bug or Feature Request?
Bug

#### Description
I have an error in Next.js(runtime) with jsx-highstock version 3.0.1:

> ReferenceError: window is not defined
>     at Object.<anonymous> (../node_modules/react-jsx-highstock/dist/react-jsx-highstock.min.js:1:320)

but version 2.2.1 works fine.

#### How to reproduce
Sample
https://github.com/deman4ik/highstock_next

#### Versions
* React JSX Highstock version: 3.0.1
* Highcharts version: 6.1.0
* React version: 16.4.1
* Next.js version: 6.0.3
* Webpack version: 3.10.0

**Comment by whawker** [comment]
Ahh crap, seems to be related to the Webpack 4 update https://github.com/webpack/webpack/issues/6522, the umd build now references `window` instead of `this`.

**Comment by whawker** [comment]
I'll implement [this change](https://github.com/feathericons/feather/pull/430/files) and see what happens...

**Comment by whawker** [comment]
@deman4ik just published `react-jsx-highcharts@3.0.2`  and `react-jsx-highstock@3.0.2` which should fixed this issue.

**Comment by deman4ik** [comment]
@whawker yep, all fine now.
Thank you for fast support!

**Comment by deman4ik** [comment]
@whawker same problem with react-jsx-highstock-datepickers

**Comment by whawker** [comment]
Good spot, just published the fix for that too `react-jsx-highstock-datepickers@3.0.1`

**Comment by CarlMungazi** [comment]
Having this same problem with:
- Highcharts 7.1.1
- Next.js 8.0.4
- React-JSX-Highstock 3.6.0
- React 16.8.6

Am I missing something?
