### ISSUE TITLE
gapSize not working

### ISSUE THREAD

**Issue by ismusidhu** [whawker/react-jsx-highcharts#124]
#### Bug
When data is missing in between, the dots should not connect and `gapSize` property from highcharts is not working here. 

#### How to reproduce
https://stackblitz.com/edit/spline-react-jsx-highcharts?file=MyChart.js

#### Live demo demonstrating bug
https://stackblitz.com/edit/spline-react-jsx-highcharts?file=MyChart.js

#### Versions
* React JSX Highcharts version: 3.0.0
* Highcharts version: 6.0.7
* React version: 16.1.1

Or is it something I'm doing wrong?

**Comment by whawker** [comment]
Hi @ismusidhu, if you search for `gapSize` in the [High*charts*](https://api.highcharts.com/highcharts/plotOptions.series.gapSize) api reference, you'll see it's not present, it seems to be a High**stock** only option.

If you change your Highcharts import to...

```js
import Highcharts from 'highcharts/highstock';
```

The the gap size start working as expected.

[Example here](https://stackblitz.com/edit/spline-react-jsx-highcharts-8pbexk?file=MyChart.js)
