### ISSUE TITLE
Can't render the SimpleLine example

### ISSUE THREAD

**Issue by MaximeHeckel** [whawker/react-jsx-highcharts#126]
#### Bug or Feature Request?
Bug

#### Description
I'm trying to render the `SimpleLine` example on my own project. I'm currently using React 16.4.0, Highcharts 6.0.0 and react-jsx-highcharts 3.1.0 and I'm on webpack 4.5
When implementing the SimpleLine project this happens when the project renders:
``` 
Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `HighchartsWrappedComponent`.
```
I'm pretty sure this might be due to something specific on my end but I was wondering if maybe someone had the same issue here, or to get an hint on what could trigger this.

#### Versions
* React JSX Highcharts version: 3.1.0
* Highcharts version: 6.0.0
* React version: 16.4.0

**Comment by whawker** [comment]
Hi @MaximeHeckel, would you mind posting the exact Chart component you're using so I can see if you're missing anything?

**Comment by whawker** [comment]
That seems normal, and how is the parent component rendering `SimpleLine`?

**Comment by MaximeHeckel** [comment]
I know it's exactly the example that you provided
Concerning the parent component I have simply this:
```
import React from 'react';
import SimpleChart from './SimpleChart';

class Panel extends React.component { 
...

  render() {
    return (
       <div class="main">
           <SimpleChart />
       </div>
    );
  }
}
```

**Comment by whawker** [comment]
Hmm only odd thing I can see there is `class="main"` which should be `className="main"`.

I'll have try in the morning to see if I can replicate.

**Comment by MaximeHeckel** [comment]
Oh yeah you can ignore the `class`.
The error comes from `HighchartsWrappedComponent` returning an object somehow. Maybe this is due to my specific setup but that would be pretty odd.

**Comment by MaximeHeckel** [comment]
Here's a screenshot of the error in my dev tools
![screen shot 2018-06-20 at 4 33 22 pm](https://user-images.githubusercontent.com/2974412/41689889-c603b0a2-74a7-11e8-9517-3463cbb3142b.png)

**Comment by fernandolobao** [comment]
I have the same problem here, same configuration as example.

**Comment by MaximeHeckel** [comment]
@fernandolobao same versions of React/Webpack as well?

**Comment by fernandolobao** [comment]
@MaximeHeckel Except I'm using React@^15.6.2

**Comment by whawker** [comment]
@MaximeHeckel just to warn you, [I dropped official support for React v15 in 3.0.0](https://github.com/whawker/react-jsx-highcharts/releases/tag/v3.0.0)

**Comment by MaximeHeckel** [comment]
@whawker I'm on 16.4.0

**Comment by MaximeHeckel** [comment]
@whawker have you been able to reproduce or do you have any idea what could trigger this?

**Comment by whawker** [comment]
@MaximeHeckel I've had no luck reproducing

I've tried
* Using the same versions as stated in the original post, [here](https://stackblitz.com/edit/base-chart-example-hjp5rf?file=index.js)
* A new Create React App, in both development and production mode. i.e. [here](https://kkvizpmo.github.stackblitz.io/SimpleLine)
* Browser only, in development and production mode i.e. [here](https://whawker.github.io/react-jsx-highcharts/examples/SimpleLine/index.html)

Could you maybe share your Webpack config?

**Comment by MaximeHeckel** [comment]
@whawker I might not be able to share the full config (a bit big) but here are the main items that I think might affect this:
- Webpack 4.5.0
- Here are the plugins I'm using:

```
const plugins = [
    debug
      ? new FriendlyErrorsWebpackPlugin({
          clearConsole: true,
        })
      : undefined,
    debug
      ? new CircularDependencyPlugin({
          // exclude detection of files based on a RegExp
          exclude: /tests|scripts|dist|node_modules/,
          // add errors to webpack instead of warnings
          failOnError: true,
          // set the current working directory for displaying module paths
          cwd: process.cwd(),
        })
      : undefined,
    debug
      ? new UnusedFilesWebpackPlugin({
          patterns: ['src/**/*.js', 'src/**/*.css'],
          globOptions: {
            ignore: [
              'node_modules/**/*', 
            ],
          },
        })
      : undefined,
    new webpack.LoaderOptionsPlugin({
      debug,
    }),
    debug
      ? undefined
      : new MiniCssExtractPlugin({
          // Options similar to the same options in webpackOptions.output
          // both options are optional
          filename: '[name].bundle.css',
        }),
    new webpack.HotModuleReplacementPlugin(),
    new webpack.DefinePlugin({
      // defining client side process.env variables
      'process.env': {
        NODE_ENV: JSON.stringify(debug ? 'development' : 'production'),
      },
    }),
    new ManifestPlugin({ cache: {} }),
    watch ? new webpack.NoEmitOnErrorsPlugin() : undefined,
    !debug ? new webpack.optimize.AggressiveMergingPlugin() : undefined,
    new HtmlWebpackPlugin({
      title: constants.HTML_TITLE_MAIN,
      template,
      hash: false,
      inject: 'body',
      chunks: ['main'],
    }),
    new HtmlWebpackPlugin({
      title: constants.HTML_TITLE_LOGIN,
      template,
      filename: 'login/index.html',
      hash: false,
      inject: 'body',
      chunks: ['login'],
    }),
    new HtmlWebpackPlugin({
      title: constants.HTML_TITLE_ERROR,
      template,
      filename: 'error/index.html',
      hash: false,
      inject: 'body',
      chunks: ['error'],
    }),
    new CopyWebpackPlugin([
      {
        from: path.resolve(__dirname, '../..', 'src/static'),
        to: '.',
        ignore: ['.DS_Store'],
      },
    ]),
    new webpack.optimize.ModuleConcatenationPlugin(),
  ].filter(plugin => !!plugin);
```

- Here are the modules I'm using
```
rules: [
      {
        enforce: 'pre',
        test: /\.js$/,
        exclude: /(node_modules|\.spec\.js)/,
        loader: 'eslint-loader',
      },
      {
        test: /\.(js|jsx)$/,
        include: path.resolve(__dirname, '../../src'),
        exclude: /node_modules/,
        loader: 'babel-loader',
        options: {
          cacheDirectory: true,
        },
      },
      {
        test: /\.(txt|md)$/,
        use: 'raw-loader',
      },
      {
        test: /\.(png|jpg|jpeg|gif|svg|woff|woff2)$/,
        use: 'url-loader?limit=10000',
      },
      {
        test: /\.(eot|ttf|wav|mp3)$/,
        use: 'file-loader',
      },
      {
        test: /\.css$/,
        exclude: [/(react-select|rc-slider).*\.css$/],
        loaders: [
          debug ? 'style-loader' : MiniCssExtractPlugin.loader,
          {
            loader: 'css-loader',
            query: {
              modules: true,
              importLoaders: 1,
              localIdentName: '[name]__[local]___[hash:base64:5]',
            },
          },
          {
            loader: 'postcss-loader',
            options: {
              config: {
                path: path.resolve(__dirname, 'postcss.config.js'),
              },
            },
          },
        ],
      },
      {
        test: [/(react-select|rc-slider).*\.css$/, 'docker-css'],
        use: ['style-loader', 'css-loader'],
      },
      {
        test: /\.(eot|svg|ttf|otf|woff|woff2)$/,
        loader: 'file-loader',
      },
    ],
```
- Running the following command for dev: `webpack-dev-server.js --mode='development' --inline --progress --debug --config ./webpack.config.js`

**Comment by MaximeHeckel** [comment]
And my `.babelrc`
```
{
  "presets": [
    "env",
    "react",
    "es2015",
    "stage-0"
  ],
  "plugins": [
    "transform-object-rest-spread",
    "transform-decorators-legacy",
    "transform-runtime",
  ]
}
```

**Comment by MaximeHeckel** [comment]
Confirming this works! 
I just forgot to update React-Dom with React. See https://stackoverflow.com/questions/49703370/react-16-3-context-provider-err-expected-string-or-class-func-but-got-object
Closing.

**Comment by whawker** [comment]
:sweat: phew!
