### ISSUE TITLE
Unmet peer dependency warning for "immutable"

### ISSUE THREAD

**Issue by Gudahtt** [whawker/react-jsx-highcharts#129]
#### Bug or Feature Request?

Bug

#### Description

I get the following warning when I install this package:
```
`react-jsx-highcharts` > is-immutable@1.0.1" has unmet peer dependency "immutable@>=3.0.0".
```

It looks like `immutable` isn't required to use `react-jsx-highcharts`. Yet I am forced to install `immutable` alongside `react-jsx-highcharts` or I get this warning.

It looks as though the `is-immutable` package doesn't directly rely upon `immutable`, but maybe the field that it looks for is not necessarily present in `immutable@<3.0.0`. If that's the case, then perhaps this case is better handed by documenting this, rather than having `immutable` as a peer dependency?

#### How to reproduce

Install this package without installing "immutable".

**Comment by whawker** [comment]
Yeah fair point. I never really considered that when I added Immutable support way back then.

I'll look to remove the peer dependency in the next release.

**Comment by whawker** [comment]
I've made `immutable` an _optional_ dependency of `is-immutable`.

Reason being optional removes the warning (which fixes the issue), but it also makes sure that if immutable _is_ being used, it's above the expected 3.0.0 minimum.

**Comment by Gudahtt** [comment]
This does indeed get rid of the warning, but I don't believe it'll have the effect you have in mind.

When you install an npm package, npm will always attempt to download the optional dependencies too. It will just allow them to fail without considering the install to have been a failure. `immutable` likely won't fail to install, so this change is no different than including `immutable` as a regular dependency. If the version used elsewhere in the project is too low, then npm will download a second copy above the 3.0.0 minimum version.

I'm not sure offhand how to achieve the desired behavior of requiring `immutable>3.0.0` only if *some* version of `immutable` is being used.
