### ISSUE TITLE
Can't remove tick marks on X-Axis

### ISSUE THREAD

**Issue by webisteme** [whawker/react-jsx-highcharts#13]
I would like to make the X-Axis on a Lien graph invisible. I have managed to remove everything except the tick marks (ignore the blue container div border underneath)
![ticks](https://user-images.githubusercontent.com/1211298/29410749-4678a5aa-8352-11e7-9046-60f38bdef57b.png)

My XAxis is defined as follows:

      <XAxis
        gridLineWidth='0'
        labels='None'
        lineWidth='0'
        minorTickLength='0'
        tickLength='0'
      />

Normally in HighCharts this would result in the whole axis disappearing. Any help appreciated.

**Comment by whawker** [comment]
The zero values need to be passed as integers, not strings.
```jsx
  <XAxis
    gridLineWidth={0}
    labels='None'
    lineWidth={0}
    minorTickLength={0}
    tickLength={0}
  />
```

**Comment by webisteme** [comment]
Thanks again
