### ISSUE TITLE
Request: help with location of highstock datepicker in chart component

### ISSUE THREAD

**Issue by ayesha-omarali** [whawker/react-jsx-highcharts#130]
#### Request
Hi! Thanks for your wrapper, it's been very helpful! 
Could you please help me out with this? I'm trying to use the date picker and put it in the same location as one of your demos [here](https://whawker.github.io/react-jsx-highcharts/examples/CustomComponent/index.html). 
Instead, it shows up underneath the chart. Ideally, I'd like to be able to have the RangeSelector buttons on the top left, and the date picker on the top right. 

Thank you for your help! 

#### Description
![image](https://user-images.githubusercontent.com/10991288/42184179-780215b4-7df9-11e8-914d-a2d11606f824.png)

#### How to reproduce
```
        <HighchartsStockChart>
          <Chart zoomType="x" />

          <Title>Highstocks Example</Title>
          <Subtitle>Using Date-Pickers</Subtitle>

          <Legend>
            <Legend.Title>Key</Legend.Title>
          </Legend>
            
          <DateRangePickers axisId="xAxis"/>

          <RangeSelector>

            <RangeSelector.Button count={1} type="day">1d</RangeSelector.Button>
            <RangeSelector.Button count={7} type="day">7d</RangeSelector.Button>
            <RangeSelector.Button count={1} type="month">1m</RangeSelector.Button>
            <RangeSelector.Button type="all">All</RangeSelector.Button>

          </RangeSelector>

          <Tooltip />

          <XAxis>
            <XAxis.Title>Time</XAxis.Title>
          </XAxis>

          <YAxis>
            <YAxis.Title>Events</YAxis.Title>
            <AreaSplineSeries id="profit" name="Profit" data={transformData} />
          </YAxis>

          <Navigator>
            <Navigator.Series seriesId="profit" />
          </Navigator>
        </HighchartsStockChart>
```

#### Versions
  *  "react-jsx-highcharts": "^3.1.0",
  *  "react-jsx-highstock": "^3.1.0",
  *  "react-jsx-highstock-datepickers": "^3.0.1",
  *  "highcharts": "^6.1.0",
  *  "react": "16.3.2",

**Comment by whawker** [comment]
Hi @ayesha-omarali, I am using CSS and `position: absolute`

<img width="915" alt="screen shot 2018-07-03 at 08 41 33" src="https://user-images.githubusercontent.com/2003804/42214798-6d4c8b34-7eb4-11e8-85af-c0719ddd2d83.png">

[See here](https://whawker.github.io/react-jsx-highcharts/examples/CustomComponent/index.html)
