### ISSUE TITLE
Add Histogram support

### ISSUE THREAD

**Issue by ricopella** [whawker/react-jsx-highcharts#135]
#### Bug or Feature Request?
Feature Request

#### Description
Would love to be able to use a Histogram series. Is that on the roadmap?

[Highcharts Histogram](https://www.highcharts.com/docs/chart-and-series-types/histogram-series)

**Comment by whawker** [comment]
Hi @ricopella, we don't have a `HistogramSeries` component (yet), but you can use the base `Series` component with the `type` prop i.e. `<Series type="histogram" />`

The named series components such as LineSeries, ScatterSeries etc, are just wrappers of the base Series component

Example histogram chart [here](https://stackblitz.com/edit/rjh-histogram?file=MyChart.js)

P.s. Remember to import and apply the Histogram module `'highcharts/modules/histogram-bellcurve'`
