### ISSUE TITLE
Comparison with the official React wrapper

### ISSUE THREAD

**Issue by dandv** [whawker/react-jsx-highcharts#138]
Hi Will, I read your [blog post](https://www.highcharts.com/blog/frameworks/react/highcharts-abstraction-react-components-react-jsx-highcharts/) about this library, and saw the link at the top pointing to [the official React wrapper for Highcharts](https://www.highcharts.com/blog/tutorials/highcharts-react-wrapper/), which they released on April 11.

I see there have been commits since then, so I'm curious how this library compares with [the official wrapper](https://github.com/highcharts/highcharts-react). BTW, thanks for explaining in the README how it compares with [other libraries](https://github.com/kirjs/react-highcharts/issues/413)!

**Comment by whawker** [comment]
I believe my library provides a simpler way for React to interact with a Highcharts chart, by providing an abstraction layer. 

All the official Highcharts wrapper does is take a large configuration option and call [`this.chart.update`](https://github.com/highcharts/highcharts-react/blob/master/src/HighchartsReact.js#L20). Which is largely fine for static charts, however for more complex use cases where the chart needs to be dynamic, you need to learn the Highcharts API to update your chart's configuration

I believe my library hides all that Highcharts complexity away. For instance the application author does not need to know that you should call `chart.series[0].setData([ /* array */])` to update the data in the first series. Instead just simply to update the `data` prop on the relevant series component.

I also believe my library feels more like "React", I think passing around large configuration objects in a old jQuery-esque style doesn't translate well to React applications.

**Comment by dandv** [comment]
Thank you!
