### ISSUE TITLE
Resizing without animation

### ISSUE THREAD

**Issue by jacobweber** [whawker/react-jsx-highcharts#140]
#### Bug or Feature Request?
Question

#### Description
First of all, thanks for this component...I converted my code from react-highcharts, and it worked so well on the first try, I had to make sure my code had actually re-compiled!

Anyway, I have a Highstock chart that I resize when the browser window is resized (I'm using react-sizeme for that).

In the pure Javascript version, I would call chart.setSize(width, height, false) to prevent animation during the resize. But how can I do that with react-jsx-highcharts? I tried setting `<Chart animation={false} />` but that didn't help.

Also, am I correct that I can change the width/height properties of Chart and it will update the size of the existing chart (rather than re-creating the chart)?

#### How to reproduce
```
<HighchartsStockChart>
	<Chart
		animation={false}
		width={this.props.size.width}
		height={this.props.size.height}
	/>
	<XAxis
		ordinal={false}
		type='datetime'
	>
	</XAxis>
	<YAxis>
		<AreaSeries
			data={this.props.data}
			animation={false}
		/>
	</YAxis>
</HighchartsStockChart>
```

#### Versions
* React JSX Highcharts version: 3.1.0
* Highcharts version: 6.0.7
* React version: 16.3.1

**Comment by whawker** [comment]
Thanks for the kind words!

Have you seen the [reflow example](https://whawker.github.io/react-jsx-highcharts/examples/Reflow/index.html)? That seems to work with `animation={false}`

https://stackblitz.com/edit/base-chart-example-kpxvcc?file=MyChart.js

**Comment by jacobweber** [comment]
Yeah, I looked at that. I'd been avoiding Highcharts' reflow feature, since I've had problems with it in the past, and calling setSize() was working for me.

It looks like [you call](https://github.com/whawker/react-jsx-highcharts/blob/master/packages/react-jsx-highcharts/src/components/Chart/Chart.js#L57) chart.update when the Chart width/height properties change. This would use the default value for the [animation argument](https://api.highcharts.com/class-reference/Highcharts.Chart#update), which is true. Maybe you could add a way to override this?

**Comment by whawker** [comment]
As a temporary workaround (if you don't want any animations at all on your chart) you could set the global animation option on your chart.

On the aforementioned stackblitz example

```js
getChart = chart => {
  Highcharts.setAnimation(false, chart)
}
```

**Comment by jacobweber** [comment]
Looks like this works by default now with Highcharts 6.1.0 and greater. You can disable animation on resize by passing `animation={false}` to the Chart component. To disable the initial animation, you have to pass the same property to all of your series components.
