### ISSUE TITLE
Dynamic activation with dropdown

### ISSUE THREAD

**Issue by Izio91** [whawker/react-jsx-highcharts#141]
Hi to everyone, I'd like to know if there is a way for integrate a dropdown to the highchart for the purpose of active the associate histogram to the item selected

**Comment by whawker** [comment]
Hi @Izio91, it should just be a case of changing the `baseSeries` prop to the ID of your selected series.

Example here: https://stackblitz.com/edit/rjh-histogram-vgsxwy?file=MyChart.js

**Comment by Izio91** [comment]
Thank you a lot for your answer! Using the same library can I add or remove histograms for the purpose of compare them in the same plan?

**Comment by whawker** [comment]
If I understand your meaning, yes - just mount/unmount a Histogram `Series` component.

**Comment by Izio91** [comment]
Thank you!
