### ISSUE TITLE
Missing support for 'tilemap' chart type.

### ISSUE THREAD

**Issue by alexei-tilikin** [whawker/react-jsx-highcharts#142]
#### Bug or Feature Request?
Feature request.

#### Description
Hello, I discovered react-jsx-highcharts and it seems to be conseptually more efficient solution comparing to flat highcharts adapters for reactjs.

I didn't really come to work with it too much, then I realized that data series of type tilemap is not supported.
I'm aware of the fact that additional modules should be added to highcharts when using a tilemap type: heatmap and tilemap.

#### How to reproduce
1. Import highcharts and required modules:

```
import Highcharts from 'highcharts';
import highChartsTilemap from 'highcharts/modules/tilemap';
import highChartsHeatmap from 'highcharts/modules/heatmap'
import highchartsMore from 'highcharts/highcharts-more';
```

2. Add the module to the highcharts provider:
```
highchartsMore(Highcharts);
highChartsHeatmap(Highcharts);
highChartsTilemap(Highcharts);
```

3. Try defining a chart of type 'tilemap'
```
<HighchartsChart colorAxis={colorAxis}
				plotOptions={this.state.plotOptions}
				callback={this.getChart}>
<Chart type="tilemap" />
<XAxis />
<YAxis />
<Series type="tilemap" name="s1" data={data}/>

</HighchartsChart>
```

4. Expected to see tilemap, instead empty chart shown without any errors or warnings in browser console.
<TilemapSeries> component doesn't exist.
<Series> component seems to ignore the type "tilemap".

#### Live demo demonstrating bug

https://stackblitz.com/edit/base-chart-example-62g6mx?file=MyChart.js

#### Versions
* React JSX Highcharts version: 3.1.0
* Highcharts version: 6.0.4
* React version: 16.2.0

**Comment by whawker** [comment]
Hi @alexei-tilikin there is an outstanding issue to add Highmaps support (#56)

Judging by the imports required by [vanilla Highcharts](http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/maps/demo/diamondmap), looks like this would be a prerequisite.

**Comment by alexei-tilikin** [comment]
Hi @whawker ,
Thanks for your response.
As far as I'm familiar with highcharts, the type 'tilemap' is not a highmap, but a highchart.
It doesn't require highmaps module, and rather depends on heatmap module (which is also part of highcharts).

The imported modules that I used in the reproduce example don't contain highmaps, and they are working for other highcharts react wrappers (such as <ReactHighcharts> or highcharts-react-official).

Here is the highcharts [demo page for Tilemap](https://www.highcharts.com/demo/honeycomb-usa), it is categorized under highcharts and not under highmaps.

Do you support 'heatmap' type? I didn't find that one as well. 
Supporting it would probably be a prerequisite...

**Comment by whawker** [comment]
@alexei-tilikin ah good spot.

Looks like the problem is that `Series` needs to child of an Axis - usually the `YAxis`.

Also, in your StackBlitz example above, you were importing the modules but not applying them, I think this might have just been a copy paste error though, as you mentioned that in your original post.

Here is that America tile chart, working in React JSX Highcharts: https://stackblitz.com/edit/base-chart-example-crydtv?file=MyChart.js

**Comment by alexei-tilikin** [comment]
@whawker it works!
Thank you for the help!
Funny enough I tried adding the series to XAxis, but probably missed something else then...
