### ISSUE TITLE
Treemap Drilldown button disappears

### ISSUE THREAD

**Issue by btomy** [whawker/react-jsx-highcharts#143]
#### Bug or Feature Request?
Bug

#### Description
Hi,
I discovered a bug when i was using the Drilldown Treemap series for my project.
So if you drilldown into the series and then you change the data ( Graph will reload) the drilldown button disappears after the graph is loaded 

#### How to reproduce
Once you click on any of the Continents and drilldown into the series. 
Then click on the 6 months radio button. The new data will be loaded
*The drilldown button disappers* 

#### Live demo demonstrating bug
https://stackblitz.com/edit/react-wbxgyv

Github Repo
https://github.com/btomy/Highcharts-treemap

#### Versions
* React JSX Highcharts version: 3.1.0
* Highcharts version: 6.1.1
* React version: 16.4.1

**Comment by anajavi** [comment]
Moving tooltipformatter out from the render fixes this. If it is inside render() it's always created when the chart renders, this somehow causes highcharts to forget about the drilldown.
Fixed example:
https://stackblitz.com/edit/react-qdktdr?file=Treemap.js
