### ISSUE TITLE
rangeSelector.buttons.events 

### ISSUE THREAD

**Issue by mwubgadeashish** [whawker/react-jsx-highcharts#144]
#### How to add click event for rangeSelector buttons
@whawker 

#### What I am trying to do?
On 1Day, 1Week and 1Month button click, trying to get first and last value from series.processedYData[0] and series.processedYData[series1.processedYData.length - 1])

#### Code Sample to set event:
1. using plotOptions: 
```
    const plotOptions = {
      series: {
        dataGrouping: {
          enabled: false
        },
        events: {
          legendItemClick: function () {
            return false;
          }
        }
      },
      toolTip: {
        enable: true,
        shared: true
      },
      rangeSelector: {
        buttons: [{
          events: {
            click: function (e) {
              console.log('here');
              this.setDayData(e);

            }
          }
        }]
      }
    };
```
2. Adding on button:
NOTE: button onClick fires before chart is reloaded/refreshed

```
          <RangeSelector selected={0}
              verticalAlign="bottom"
              x={-80}
              floating={false}
              useHTML={true}
              buttonTheme={{'width': 55,'height': 18, 'padding': 10, 'fill': 'none', 'states': {'select': {'fill': '#e0e0e0', 'hover': {'fill': '#e0e0e0'}}}}}
              buttonPosition={{'align': 'center'}}>
            <RangeSelector.Button count={1} type="day"  click={this.setDayData}>1 Day</RangeSelector.Button>
            <RangeSelector.Button count={1} type="week"  click={this.setDayData}>1 Week</RangeSelector.Button>
            <RangeSelector.Button count={1} type="month" click={this.setDayData}>1 Month</RangeSelector.Button>
          </RangeSelector>
```
#### Code Sample for Click Method
```
  setDayData = (e) => {
    Highcharts.charts.forEach(chart => {
      if(chart !== undefined) {
        chart.series.forEach(series1 => {
          if(series1.name !== 'XXX') {
            return;
          } else {
            console.log('Min => ', series1.processedYData[1]);
            console.log('Min => ', series1.processedYData[series1.processedYData.length - 1]);
          }
        });
      }
    });
  };

```

#### Versions
* React react-jsx-highstock version: "^2.2.1"
* Highcharts version: "^6.0.7"
* React version: "^16.2.0"

**Comment by whawker** [comment]
Hi @mwubgadeashish, as mentioned [in the readme](https://github.com/whawker/react-jsx-highcharts#exception-1), we use the React convention `onEventName` for event handlers.

See the example below, using `onClick` on the "Hi" button
https://stackblitz.com/edit/base-chart-example-v1ntv3?file=MyChart.js

**Comment by mwubgadeashish** [comment]
@whawker thanks for quick response. I have already tried this example and event was called as you have shown in example. 
But this event is called before graph is re-loaded and the values in `processedYData` refers to prior selected `RangeSelector` and not the currently clicked.

I was looking for something like callback event on button or on entire chart when entire chart data is reloaded. OR is there is any way by which i can find what will be the data range for 1Day, 1Week & 1Month (1m will be entire data)?

#### What I am trying to achieve?
On RangeSelector.Button click, need to change the color of Line based on 1st and last value shown/displayed in the graph.

Thanks,
Ashish

**Comment by mwubgadeashish** [comment]
@whawker can you please look into my previous comment?
