### ISSUE TITLE
xAxis.crosshair zIndex

### ISSUE THREAD

**Issue by mwubgadeashish** [whawker/react-jsx-highcharts#145]
#### Ref: https://api.highcharts.com/highcharts/xAxis.crosshair.zIndex
I tried it by using plotOptions but did not worked

@whawker

**Comment by whawker** [comment]
I seem to be getting the `zIndex` through in my tests? Have you specified a `zoomType` on your chart?

<img width="739" alt="screen shot 2018-07-31 at 09 08 47" src="https://user-images.githubusercontent.com/2003804/43448134-051931c8-94a5-11e8-8f11-dbb900bf59c9.png">

See here: https://stackblitz.com/edit/base-chart-example-1uvkjp?file=MyChart.js

**Comment by mwubgadeashish** [comment]
@whawker thanks for quick response. It worked.

I was trying throw plotOptions and seems I was doing something wrong. 

Once again thanks for quick help.

Thanks,
Ashish
