### ISSUE TITLE
Range Selector Button - get associated data values

### ISSUE THREAD

**Issue by mwubgadeashish** [whawker/react-jsx-highcharts#147]
#### I have 3 range selector buttons (viz 1 Day, 1 Week and 1 Month). I need to know what data will be displayed on each button click. With Highcharts object how to get these values?

@whawker

**Comment by whawker** [comment]
Not sure on that one. Seems more of a question on how to use Highcharts than my wrapper library. You might best off posting on the [Highcharts issues](https://github.com/highcharts/highcharts/issues) instead.

**Comment by mwubgadeashish** [comment]
@whawker Thanks for response and I am able to get it by using `processedYData`

Also do you have any example where I can dynamically change the color for LineSeries  by using `id` or `name`?

**Comment by whawker** [comment]
Being a React component it is already dynamic, you just need to change the value of the `color` prop on your `LineSeries`

I.e.
```jsx
state = {
  color: 'red'
}

someMethod = () = {
  this.setState({ color: 'green' })
}

render () {
  const { data } = this.props
  const { color } = this.state
  return (
    <HighchartsChart>
      // axes etc. omitted
      <LineSeries name="My Series" color={color} data={data} />
    </HighchartsChart>
  ) 
}
```
