### ISSUE TITLE
AxisProvider method removePlotLine won't remove the plot line

### ISSUE THREAD

**Issue by geforcefan** [whawker/react-jsx-highcharts#15]
After analysing the problem why **removePlotLine** in Component **PlotLine.componentWillUnmount** won't kick in is that the argument (id) won't be passed to **highcharts** in "raw" format.

I've traced this code:
`this.props.removePlotLine("SomeID");`

and landed in the raw function **removePlotBandOrLine** in **highcarts**. What I saw is, that the argument, which is passed though the boundContextHelper, seems to be messy:

`removePlotBandOrLine({
0: "SomeID"
})`

What I've expected is just:

`removePlotBandOrLine("SomeID")`

This is happening because **removeProviderProps** in the **cleanPropsBeforeUpdate.js** expects an object, which is not given in this method thus `return omit(config, getProvidedProps());` turns the config, which needs to be flat, into an object.

After removing the wrapper function **cleanPropsBeforeUpdate** from the **AxisProvider** for the **removePlotLine** method, removing a plot line works like a charm, but I don't think this is a perfect solution (There is surely a good reason, why you guys wrapped the remove methods with **cleanPropsBeforeUpdate**) due it seems to be a general problem (same applies to **removePlotBand**).

Maybe the function **removeProviderProps** (or **cleanPropsBeforeUpdate**) needs to be modified properly.

In fact, Ive tried just for fun to pass multiple arguments to native **highcharts** methods by using **getBoundAxisMethod** which results in passing only the first argument (depending on whether I am wrapping the method with **cleanPropsBeforeUpdate** which indeed passes multiple arguments as an object like described above)

I've posted a quick dirty solution to fix this bug in #16

Gonna post a little snippet how to reproduce the problem.

**Comment by whawker** [comment]
Thanks very much for this detailed bug report and fix! I've modified the `removePlotLine` and `removePlotBand` functions as you highlighted in the commits above.
