### ISSUE TITLE
If two charts share a data value, only one gets updated

### ISSUE THREAD

**Issue by jacobweber** [whawker/react-jsx-highcharts#151]
#### Bug or Feature Request?
Bug

#### Description
If two charts reference the same value in their "data" property, changing the value only updates one of the charts.

#### How to reproduce
Create an array of data, and pass it into a chart component's "data" property. Pass the same array into a second identical chart. Now update the property's value (e.g. don't just change the array's contents, but replace it with a new array). The first chart will update, but the second one will display the old data.

#### Live demo demonstrating bug
https://stackblitz.com/edit/base-chart-example-qwu6er
Click Update once and both charts update. Click again and only the top chart updates.

#### Versions
* React JSX Highcharts version: 3.2.0
* Highcharts version: 6.1.1
* React version: 16.4.0

**Comment by whawker** [comment]
Hmm interesting, I'm not quite sure why that is. 

It might be something to do with Highcharts modifying the array by memory reference when it processes it, therefore the second chart believes there is no work to be done? I'll look into it.

As a workaround, it seems if you spread the data before passing it down (therefore cloning it), it seems to avoid the issue

```jsx
render () {
  const { data } = this.state
  return (
    <div className="app">
      <button onClick={() => this.handleClick()}>Update</button>
      <MyChart data={[ ...data ]} />
      <MyChart data={[ ...data ]} />
    </div>
  );
}
```

**Comment by anajavi** [comment]
This issue has changed. With highcharts@7.2.1 it now ignores second update to data, but then it starts to work.
https://stackblitz.com/edit/base-chart-example-wtfzdk?file=index.js

With react-jsx-highcharts@4.0.0-alpha.6 even the second update works:
https://stackblitz.com/edit/base-chart-example-zvktrw?file=index.js

**Comment by anajavi** [comment]
The 4.0.0-alpha uses Object.is check instead of isEqual on data prop. I think that highcharts mutating the passed in data causes isEqual check to return true (previous data is the same as new data).

Anyway, this should be fixed in alpha, although I expect there to be more problems if highcharts keeps on mutating the data.

**Comment by anajavi** [comment]
This now works on v4.0.0
