### ISSUE TITLE
how to force to update collection of ColumnSeries

### ISSUE THREAD

**Issue by vladimirvorobiev** [whawker/react-jsx-highcharts#154]
#### Bug or Feature Request?
N/A

#### Description
how to force to update collection of ColumnSeries looks like it push it by default when state changed

#### Versions
* React JSX Highcharts version: latest
* Highcharts version:  latest
* React version: latest

**Comment by whawker** [comment]
Would you mind creating a demo of the problem? I'm not quite sure what you mean.

**Comment by vladimirvorobiev** [comment]
I've created the app
https://stackblitz.com/edit/react-iq27yr

if you uncheck/check [02pm]  checkbox it will disappears and appears in the end on series.  
If you uncheck/check [09am]  checkbox it will disappears and appears in the end on series BUT I am expecting to be appear in the start of series (in the place it was before unchecked)
Did I miss smth or dont understand smth? Thanks

**Comment by vladimirvorobiev** [comment]
Added demo
Please review

**Comment by whawker** [comment]
Hmm I would suggest using the series `visible` and `showInLegend` properties instead of an array filter?

React JSX Highcharts automatically adds/removes a series when a `<Series />` component is mounted/unmounted.

Instead of 
```jsx
arr.filter(c => c.enabled)
  .map(item => (
    <ColumnSeries 
      key={item.sortOrder} 
      //etc
    />
  ))
```

Try
```jsx
arr.map(item => (
    <ColumnSeries
      key={item.sortOrder} 
      visible={item.enabled}
      showInLegend={item.enabled}
      //etc
      />
  ))
```

**Comment by vladimirvorobiev** [comment]
did not help
change the demo - behavior is the same

**Comment by vladimirvorobiev** [comment]
sorry it works
