### ISSUE TITLE
Can anyone show a working example of dataLabels in a Bar Chart?

### ISSUE THREAD

**Issue by devcreations** [whawker/react-jsx-highcharts#156]
#### Bug or Feature Request?
Can anyone show a working example of dataLabels in a Bar Chart?

#### Description
dataLabels example in a Bar Chart?

#### Versions
* React JSX Highcharts version: 
* Highcharts version: 
* React version:

**Comment by whawker** [comment]
@devcreations is this what you mean? https://stackblitz.com/edit/base-chart-example-mztu7w?file=MyChart.js

**Comment by devcreations** [comment]
Thank you! Looking at the example you provided, I was able to determine my mistake in adding dataLabels={true} for each columnSeries, when all I needed was to declare in plotOptions.
