### ISSUE TITLE
ColumnSeries color

### ISSUE THREAD

**Issue by vladimirvorobiev** [whawker/react-jsx-highcharts#158]
#### Bug or Feature Request?
question

#### Description
Is it possible to set custom color for each column in ColumnSeries?
I could see that ColumnSeries color property affects all columns in series...
#### Versions
* React JSX Highcharts version: latest
* Highcharts version:  latest
* React version: latest

**Comment by whawker** [comment]
[Yes](https://api.highcharts.com/highcharts/series.column.color). As stated [in the readme](https://github.com/whawker/react-jsx-highcharts#getting-started), you can use the Highcharts API documentation to determine which props to pass.

```jsx
<ColumnSeries color='#FF0000' data={[1, 2, 3]} />
````

Equivalent to
```js
series: [{
  type: 'column',
  color: '#FF0000',
  data: [1, 2, 3]
}]
```

**Comment by alilland** [comment]
@whawker is it possible to conditionally set the color of each Column? The desire is to show one color if its over a goal, and another if its under a goal.
[https://stackoverflow.com/questions/7737409/set-different-colors-for-each-column-in-highcharts](url)
