### ISSUE TITLE
CI Server

### ISSUE THREAD

**Issue by whawker** [whawker/react-jsx-highcharts#159]
Use a CI server to automatically lint and test each commit

**Comment by whawker** [comment]
> @anajavi 
> Do you have a preference for a CI server? Circle might be easiest.

I've mostly used Travis, but I'm happy to go with Circle if you're are more comfortable with it?

**Comment by anajavi** [comment]
I made a configuration for travis (5154a06). Currently it doesn't build datepickers as the commands are different in that package.

Can you please enable building the project in travis?

**Comment by whawker** [comment]
I just added Travis, do you have access?

**Comment by whawker** [comment]
Sounds good to me! Same as what you did in #116?

**Comment by anajavi** [comment]
Same thing. And travis seems to work okay. Gives me some peace of mind that my commits won't break things too much :)

**Comment by whawker** [comment]
Nice work on this @anajavi!
