### ISSUE TITLE
PlotLine values not updating, PropTypes wrong

### ISSUE THREAD

**Issue by geforcefan** [whawker/react-jsx-highcharts#16]
For some reason, **PlotLine values** are not updating. Maybe I am missing a point, but It seems 
that **PlotLine** needs to provide **componentDidUpdate**.

My solution was to add following code:

```
  componentDidUpdate (prevProps) {
        this.props.removePlotLine(prevProps.id);
        const { axisId, dimension, ...rest } = this.props;
        this.props.addPlotLine(rest);
    }
```
Because of the other bug I've reported, this solution will not fix the problems, because **this.props.removePlotLine** won't pass the **id** to **highcharts** (Described in: #15)

The PropTypes seems to be copied from **PlotBand**. This means **value** property is not existing in **PlotLine** but **from** and **to**. 

My quick solution for BOTH bugs (#16, #15) is extending the **PlotLine** Component and provide some additional functionalities for removing the plot line (this is a dirty hack):

```
import { PlotLine as OrignalPlotLine } from 'react-jsx-highcharts';
import PropTypes from 'prop-types';
import boundContextHelper from 'react-jsx-highcharts/src/utils/boundContextHelper';

class PlotLine extends OrignalPlotLine {
    static propTypes = {
        id: PropTypes.string.isRequired,
        axisId: PropTypes.string, // Provided by Axis component
        dimension: PropTypes.string, // Provided by Axis component
        value: PropTypes.number.isRequired,
        xAxis: PropTypes.string,
        yAxis: PropTypes.string,
        color: PropTypes.string,
        addPlotLine: PropTypes.func, // Provided by AxisProvider
        removePlotLine: PropTypes.func // Provided by AxisProvider
    };

    constructor(props) {
        super(props);

        const id = props.axisId || props.id;
        if (!id) return null;

        const axis = props.get(id);

        const getBoundAxisMethod = boundContextHelper(props.getChart(), axis);
        const removePlotLine = getBoundAxisMethod(axis && axis.removePlotLine);

        this.removePlotLineFixed = removePlotLine;
    }

    componentWillUnmount () {
        this.removePlotLineFixed(this.props.id);
    }

    componentDidUpdate (prevProps) {
        this.removePlotLineFixed(prevProps.id);
        const { ...rest } = this.props;
        this.props.addPlotLine(rest);
    }
}

export default PlotLine;
```

Gonna post a little snippet asap how to reproduce the problem.

**Comment by whawker** [comment]
Ah of course! Annoyed with myself for failing to a `componentDidUpdate` for these components.

It took me a little longer than I had expect to implement your suggested fix, as the `PlotBand.Label`/`PlotLine.Label` components were trying to update a removed band/line.

Is it possible for you to try building you application against the master branch, and see if these issues are fixed?

**Comment by whawker** [comment]
P.s. I've publish `1.3.3` as a pre release, which might be easier than trying to use master `npm install react-jsx-highcharts@1.3.3-pre.1`

**Comment by geforcefan** [comment]
I can confirm that the reported bugs are now fixed. I guess the highstock package is not updated yet. But this was good for the comparison since I just needed to import from highstock and then from highcharts to figure out whether the bugs was fixed or not. Thanks :)

**Comment by whawker** [comment]
Fantastic. Just published as a stable release `react-jsx-highcharts@1.3.3` and `react-jsx-highstock@1.3.3`
