### ISSUE TITLE
Slow Performance with large data sets

### ISSUE THREAD

**Issue by JPNZ4** [whawker/react-jsx-highcharts#160]
#### Description
I'm testing react-jsx-highcharts in my application with some fairly large data sets. Once I reach 5000-10,000 data points per graph my performance starts to deteriorate quickly, it will work up to around 100,000 data points but extremely slowly. I have re-created the same scenario is vanilla JS and it works with no performance issue.

To test the performance I'm moving my mouse around the graph with the tooltip on, as it gets slower the tooltip fails to keep up with the mouse and then around 50,000 data point and upwards it may take up to 5 seconds to render the tooltip.

After running some performance tests in chrome dev tools, I noticed that the more data points I add the longer the painting takes. When I dive deeper, its the composite layers that are taking up the most time in the performance tools. Screenshot attached below, this in one graph with 50,000 data points and I'm just moving the mouse around the graph.

![50k highcharts graph](https://user-images.githubusercontent.com/17604706/46310395-b2bdcd00-c61b-11e8-93c4-4778ca128710.PNG)

In comparison to a Vanilla JS application with three of the same graph with 1 million data points each.

![vanillajs 3x 1mill graphs](https://user-images.githubusercontent.com/17604706/46310566-37a8e680-c61c-11e8-9c3f-5562ce06a9e5.PNG)

The vanillaJS application is the same as this https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/line-boost/ and the react-jsx-highcharts is the same as the front page demo but adding larger datasets.

Is there anything I can do to improve the performance of this library or would this possibly be a react issue?

#### Versions
* React JSX Highcharts version: 3.2.1
* Highcharts version: 6.1.4
* React version: 16.5.1

**Comment by whawker** [comment]
Hi @JPNZ4, have you tried using the boost module, like in the vanilla JS example?

```js
import Highcharts from 'highcharts';
import addBoostModule from 'highcharts/modules/boost';

// Apply additional modules
addBoostModule(Highcharts);
```

**Comment by JPNZ4** [comment]
Ah, sorry, I though I had done so, but no. That has fixed the problem and now gives similar results to the vanilla JS example. Thanks @whawker .
