### ISSUE TITLE
Correct way to change chart line type? And minor issue with RangeSelector.

### ISSUE THREAD

**Issue by Jaguar1** [whawker/react-jsx-highcharts#161]
#### Description
Hello,

Is this the correct way to change chart line type?
Please pay attention at the select element at the bottom.
In this case I toggle between SplineSeries and ColumnSeries.
Is this a correct approach? Notice in this example RangeSelector chart disappears the first time you change option in select drop down.

Regards,
Vladimir

#### How to reproduce
Change option in select drop down to toggle between SplineSeries and ColumnSeries types.

#### Live demo demonstrating bug
https://stackblitz.com/edit/react-ys3cpv?file=DemoChart.js

#### Versions
* React JSX Highcharts version: 2.0.2
* Highcharts version: 5.0.14
* React version: 16

**Comment by whawker** [comment]
Hi @Jaguar1, I would suggest using the `<Series />` component directly and modifying the `type` prop.

The `ColumnSeries` etc, are just [helpers](https://github.com/whawker/react-jsx-highcharts/blob/master/packages/react-jsx-highcharts/src/components/ColumnSeries/ColumnSeries.js#L12) for the main series component.

It seems you can modify the type of series in the Navigator by changing the [`naviagtor.series.type`](https://api.highcharts.com/highstock/navigator.series.type). I suspect this would not work for multiple series of different types though.

Example here: https://stackblitz.com/edit/react-5cucui?file=DemoChart.js

**Comment by Jaguar1** [comment]
That was helpful. Thanks a lot!
