### ISSUE TITLE
Highcharts 6.2.0 breaks Series componentWillUnmount

### ISSUE THREAD

**Issue by anajavi** [whawker/react-jsx-highcharts#164]
#### Bug or Feature Request?

Bug. Might be in highcharts itself.

#### Description

Upgrading to Highcharts 6.2.0 breaks Series componentWillUnmount.
https://github.com/whawker/react-jsx-highcharts/blob/9c20dfbc12e2f16a12e5c1fe4ff1ae3da61b8ae0/packages/react-jsx-highcharts/src/components/Series/Series.js#L78

Error:
```
Cannot read property 'bind' of null
```
#### How to reproduce

Any series unmount triggers this.

#### Live demo demonstrating bug
Navigate to series and back to index on:
https://stackblitz.com/edit/github-vtzme3?file=src/index.js

#### Versions
* React JSX Highcharts version: 3.2.1
* Highcharts version: 6.2.0
* React version: 16.5.2

**Comment by anajavi** [comment]
Probably this commit in highcharts:
https://github.com/highcharts/highcharts/commit/dc77c44c1a87109ef7e8580e4b55be1989d075df

The series.remove is now set to null after series.destroy()

**Comment by whawker** [comment]
Legend, thanks @anajavi!

**Comment by anajavi** [comment]
This is very likely to happen in future in Axis:
https://github.com/whawker/react-jsx-highcharts/blob/4649e05a1aaa7d31c3deab654c5f72a30d2e1b63/packages/react-jsx-highcharts/src/components/Axis/Axis.js#L67

Do you think it should be wrapped too?

**Comment by whawker** [comment]
Yeah, it's probably best we guard against it.

**Comment by whawker** [comment]
Thanks @anajavi, I'll publish 3.3.0-beta.1 now.

**Comment by anajavi** [comment]
Quick testing with chrome & IE11 seems to be okay.

**Comment by anajavi** [comment]
Find out something that helps debugging. Importing Highcharts from es-module version gives file and line number when it throws:
```javascript
import Highcharts from 'highcharts/es-modules/masters/highcharts.src';
import 'highcharts/es-modules/masters/highcharts-more.src';
```

It also gives slightly smaller app bundle.
