### ISSUE TITLE
Refactor series components

### ISSUE THREAD

**Issue by anajavi** [whawker/react-jsx-highcharts#166]
Is there a reason why all the different Series components have their own classes, although their code is mostly the same?

Many of them could be written with a HOC like this:
```jsx
import React, { Component } from 'react';
import Series from '../Series';
import PropTypes from 'prop-types';

// This HOC returns Series component with injected type
export default function withSeriesType(seriesType, componentName) {

  class SeriesComponent extends Component {
    render () {
      return (
        <Series {...this.props} type={seriesType} />
      );
    }
  }
  SeriesComponent.propTypes = {
    id: PropTypes.oneOfType([ PropTypes.string, PropTypes.func ])
  };
  SeriesComponent.displayName = componentName;
  return SeriesComponent;
}
export const ColumnSeries = withSeriesType("column", "ColumnSeries");
export const LineSeries = withSeriesType("line", "LineSeries");
```

edit: working example

**Comment by whawker** [comment]
No specific reason to be honest, probably just an oversight on my part. The HOC would definitely reduce the amount we need to test.

There are a few series types to watch out for
- [BarSeries](https://github.com/whawker/react-jsx-highcharts/blob/master/packages/react-jsx-highcharts/src/components/BarSeries/BarSeries.js) - Inverts the chart
- [FunnelSeries](https://github.com/whawker/react-jsx-highcharts/blob/master/packages/react-jsx-highcharts/src/components/FunnelSeries/FunnelSeries.js), [PyramidSeries](https://github.com/whawker/react-jsx-highcharts/blob/master/packages/react-jsx-highcharts/src/components/PyramidSeries/PyramidSeries.js), [PieSeries](https://github.com/whawker/react-jsx-highcharts/blob/master/packages/react-jsx-highcharts/src/components/PieSeries/PieSeries.js) & [VariablePieSeries](https://github.com/whawker/react-jsx-highcharts/blob/master/packages/react-jsx-highcharts/src/components/VariablePieSeries/VariablePieSeries.js) - Don't require a parent axis
- [BellCurveSeries](https://github.com/whawker/react-jsx-highcharts/blob/master/packages/react-jsx-highcharts/src/components/BellCurveSeries/BellCurveSeries.js), [HistogramSeries](https://github.com/whawker/react-jsx-highcharts/blob/master/packages/react-jsx-highcharts/src/components/HistogramSeries/HistogramSeries.js) & [ParetoSeries](https://github.com/whawker/react-jsx-highcharts/blob/master/packages/react-jsx-highcharts/src/components/ParetoSeries/ParetoSeries.js) - Require parent series, but not data

**Comment by anajavi** [comment]
HOC:
```jsx
import React, { Component } from 'react';
import Series from '../Series';
import PropTypes from 'prop-types';

// This HOC returns Series component with injected type
export default function withSeriesType(seriesType, componentName, opts) {
  const { additionalProps, additionalPropTypes } = opts ? opts: {};

  class SeriesComponent extends Component {
    render () {
      return (
        <Series {...this.props} type={seriesType} {...additionalProps} />
      );
    }
  }
  SeriesComponent.propTypes = {
    id: PropTypes.oneOfType([ PropTypes.string, PropTypes.func ]),
    ...additionalPropTypes
  };
  SeriesComponent.displayName = componentName;
  return SeriesComponent;
}
```

VariablePieSeries:
```jsx
export default withSeriesType('variablepie','VariablePieSeries', { additionalProps: {requiresAxis: false }});
```
BellCurveSeries:
```jsx
export default withSeriesType('bellcurve','BellCurveSeries', { additionalPropTypes: { baseSeries: PropTypes.string.isRequired }});
```
AreaSeries:
```jsx
export default withSeriesType('area','AreaSeries');
```
That leaves the BarSeries.

Just thinking how the src & test folders should be structured after this, it doesn't make much sense to have folder for each component.

**Comment by whawker** [comment]
Yeah that works for me.

Could we not just expose the series types straight from the `src/index.js` file?

```js
export const AreaSeries = withSeriesType('area', 'AreaSeries');
export const LineSeries = withSeriesType('line', 'LineSeries');
// etc?
```

**Comment by whawker** [comment]
Although, we could make the HOC return a functional component?

```jsx
// This HOC returns Series component with injected type
export default function withSeriesType(seriesType, componentName, opts = {}) {
  const { additionalProps, additionalPropTypes } = opts;
  const SeriesComponent = props => (
    <Series {...this.props} {...additionalProps} type={seriesType} />
  )
  SeriesComponent.propTypes = {
    id: PropTypes.oneOfType([ PropTypes.string, PropTypes.func ]),
    ...additionalPropTypes
  };
  SeriesComponent.displayName = componentName;
  return SeriesComponent;
}
```
(Also note default argument for  `opts`)
