### ISSUE TITLE
Maps examples don't work on IE11

### ISSUE THREAD

**Issue by anajavi** [whawker/react-jsx-highcharts#168]
#### Bug or Feature Request?
Bug

#### How to reproduce

The examples show up empty on IE11

#### Live demo demonstrating bug
https://whawker.github.io/react-jsx-highcharts/examples/SimpleLine/index.html

**Comment by anajavi** [comment]
Same thing sparkline demo, although I think it is because of this line:
https://github.com/whawker/react-jsx-highcharts/blob/e017643a96df38228db8f3a9d2caf3e9f4143f69/packages/react-jsx-highcharts/src/components/HighchartsSparkline/HighchartsSparkline.js#L54

IE11 Object does not have assign.

**Comment by whawker** [comment]
Do you think it could be related to the removal of [`transform-object-rest-spread`](https://github.com/whawker/react-jsx-highcharts/blob/v3.2.1/packages/react-jsx-highcharts/.babelrc#L2)?

Looks like that makes it default to using Babel's extend rather than Object.assign? https://babeljs.io/docs/en/babel-plugin-proposal-object-rest-spread

**Comment by anajavi** [comment]
The babel-plugin-proposal-object-rest-spread is included by default, because it is part of es2018.

**Comment by anajavi** [comment]
The maps one might be this in react-request:
https://github.com/jamesplease/react-request/blob/6231ae04d726755f0a588ec7df1c3347e3a2bfba/src/fetch.js#L182

**Comment by anajavi** [comment]
The sparkline is easy to fix, but the maps examples need:
- a fix to react-request
- a polyfill
- another fetch library, like https://github.com/tkh44/holen
- leave it as is

**Comment by whawker** [comment]
The simplest fix seems to be adding an [Object.assign polyfill](https://unpkg.com/es6-object-assign@1.1.0/dist/object-assign-auto.min.js) to the [template.html](https://github.com/whawker/react-jsx-highcharts/blob/master/examples/template.html) page.

Or is that too hacky? I'm fine with it personally.

**Comment by anajavi** [comment]
Nothing is too hacky for me.

**Comment by whawker** [comment]
Good spot on that one, should be fixed now.
