### ISSUE TITLE
SeriesProvider don't removes handleSeriesAdded Event when component will unmount

### ISSUE THREAD

**Issue by geforcefan** [whawker/react-jsx-highcharts#17]
**handleSeriesAdded** is called after a Series is unmounted, because the registered Event (in **providerSeries**) isn't removed after the component is unmounted.

` Highcharts.addEvent(getChart(), 'addSeries', this.handleSeriesAdded);`

 This will do the trick:

```
    componentWillUnmount() {
        const { getChart } = this.props;
        Highcharts.removeEvent(getChart(), 'addSeries', this.handleSeriesAdded);
    }
```

When not doing this, react will warn you (because you can't set states on unmounted components) 

```
Warning: setState(...): Can only update a mounted or mounting component. 
This usually means you called setState() on an unmounted component. 
This is a no-op. Please check the code for the SeriesProvider(t) component.
```

**Comment by whawker** [comment]
Hi, sorry I've been on holiday the past few days. Looking into these issues now.

**Comment by whawker** [comment]
Good spot! And thank you for the detailed bug report and suggested fix. I'll need to add you as a contributor 😄

**Comment by geforcefan** [comment]
Thanks for your efforts, gonna check your all your fixes right now. I think react-jsx-highcharts is a very good library and I am glad I found this. Very solid implementation. Id be glad to help you on this since I am heavily using the highcharts with very complex scenarios.

**Comment by whawker** [comment]
That's good to hear! Thank you very much, I look forward to it.
