### ISSUE TITLE
Question: Is there is an easy way to run the examples locally instead of stackBlitz?

### ISSUE THREAD

**Issue by alexliu-github** [whawker/react-jsx-highcharts#170]
I am new to highcharts, would like to run through some of the examples locally. Is there an easy way to run it locally after cloning it?
Thanks in advance.

**Comment by whawker** [comment]
Hi @alexliu-github, we have an examples repo - https://github.com/whawker/react-jsx-highcharts-examples

1. `git clone git@github.com:whawker/react-jsx-highcharts-examples.git` - Clone the examples repo
1. `npm install` - Install dependencies
1. `npm start`

This will run the examples as a Create React App, which includes hot reloading, so you'll be able to play around with the examples there.

**Comment by alexliu-github** [comment]
Got it up and running, thank you, Will.
