### ISSUE TITLE
Planning for next major release

### ISSUE THREAD

**Issue by anajavi** [whawker/react-jsx-highcharts#171]
Highcharts 7 should be here soon, so I thought the next major release could be planned.

Here's my list of breaking changes I like to see for discussion:
1. Drop equality checks from prop changes, do shallow check instead. This should give better performance
2. Drop support for Highcharts 5 (what about dropping 6 too?)
3. Add support for Highcharts 7
4. Drop support for React < 16.3. Enables the use of new lifecycle methods, if needed
5. Remove FlagSeries as it is now called FlagsSeries

**Comment by whawker** [comment]
Good idea planning for the next release.

I'm happy with those suggestions, except for dropping React < 16.3 support. 

The main use I have for this project is at my place of work, where it is part of large React web app currently using React 16.2. We do plan to update to the latest version of the React, but I can't see us doing that before year end, due to other commitments. It looks as if Highcharts 7 will come out mid November.

Other features I'd like to consider are
* Proper [`colorAxis`](https://api.highcharts.com/highcharts/colorAxis) support.
* Improved responsive capabilities

**Comment by anajavi** [comment]
What does improved responsive capabilities mean?

**Comment by whawker** [comment]
There is a [responsive example](https://whawker.github.io/react-jsx-highcharts/examples/Responsive/index.html), but to be honest it is pretty poor. Trying to do anything more complicated doesn't particularly work very well.

I wonder if there is something we can do with [`responsive.rules`](https://api.highcharts.com/highcharts/responsive) instead.

**Comment by anajavi** [comment]
Wrapping the whole chart in something like https://github.com/souporserious/react-measure might do it.
That could be wired to do setSize on chart, and making the responsive.rules to run.

**Comment by anajavi** [comment]
I ran a quick test with Highcharts 7 from the repository. Nothing seems to break yet.

**Comment by whawker** [comment]
Great news.

I think with the number of annotations Highstock 7 adds, we should add better support for them.

**Comment by anajavi** [comment]
Something like this?
```jsx
import React, { Component, Children, cloneElement, isValidElement } from 'react';
import PropTypes from 'prop-types';
import uuid from 'uuid/v4';
import { isFunction } from 'lodash-es';
import { attempt } from 'lodash-es';
import Hidden from '../Hidden';
import getModifiedProps from '../../utils/getModifiedProps';

class Annotation extends Component {

  static propTypes = {
    getChart: PropTypes.func.isRequired // Provided by ChartProvider
  };

  static defaultProps = {
    id: uuid
  };

  constructor (props) {
    super(props);

    this.state = {
      rendered: false
    };
  }

  componentDidMount () {
    const chart = this.props.getChart();

    // Create Highcharts Plot Band on Axis
    const opts = this.getAnnotationConfig();
    chart.addAnnotation(opts);

    this.setState({
      rendered: true
    });
  }

  componentDidUpdate (prevProps) {
    if (getModifiedProps(prevProps, this.props) === false) return;

    const chart = this.props.getChart();
    // Plot Bands cannot be updated, we have to remove and re-add
    const opts = this.getAnnotationConfig();
    chart.removeAnnotation(opts.id);
    chart.addAnnotation(opts);
  }

  componentWillUnmount () {
    const chart = this.props.getChart();
    attempt(chart.removeAnnotation, this.id);
  }

  getAnnotationConfig = () => {
    const { id, children, ...rest } = this.props;
    if (!this.id) {
      this.id = isFunction(id) ? id() : id
    }

    return {
      id: this.id,
      ...rest
    }
  }

  render () {
    const { children } = this.props;
    if (!children || !this.state.rendered) return null;

    const annotationChildren = Children.map(children, child => {
      if (isValidElement(child) === false) return child;
      return cloneElement(child, { id: this.id });
    });

    return (
      <Hidden>
        {annotationChildren}
      </Hidden>
    );
  }
}

export default Annotation;

```

**Comment by whawker** [comment]
Exactly like that, amazing! 

Although will the massive amount of annotation types available, I wonder if we should provide helper types, like we do for all the different series types?

**Comment by anajavi** [comment]
New v4 todo list suggestion.

Breaking changes:
- Drop immutable, lodash.isEqual
- Make Series & friends PureComponent
- Drop Highcharts < 7
- Drop React < 16.2 (that gives us Fragment)
- Remove FlagSeries as it is now called FlagsSeries


Features:
- Annotation component
- colorAxis support
- better responsiveness (yet to be defined)

These features aren't breaking and don't necessarily need a major version.

Other:
Upgrade react-day-picker on highstock-datepickers to fix deprecated lifecycle methods. The package does not seem to be popular according to [npm download counts](https://www.npmjs.com/package/react-jsx-highstock-datepickers). Maybe the package could be deprecated? What do you think?

**Comment by anajavi** [comment]
Highcharts seems to be dropping older browser support: https://github.com/highcharts/highcharts/issues/9225

How do you feel about dropping support for IE < 11?

Most of the lodash functions could then be replaced with native ones.

I could setup a branch and start doing some of the changes.

**Comment by whawker** [comment]
Good spot, happy to drop IE10 support. This would bring in line with the company policy on the product I mainly use this library for.

**Comment by anajavi** [comment]
Let's drop it then.

By the way, npm now installs 3.3.1-alpha.1 by default. It has broken sankey series, which is fixed in master.

**Comment by anajavi** [comment]
Decided to keep immutable and isEqual checks. Not enough meaningful breaking changes without those.

Major release postponed if Highcharts 7 does not break things.

**Comment by whawker** [comment]
@anajavi Highcharts 7 has just been released, running some tests now. Let me know if you spot anything?

**Comment by anajavi** [comment]
Tests pass highcharts 7, and everything seems to render okay. I think it is alright.

**Comment by whawker** [comment]
I think we'll need to add a prop for Styled by CSS

Previously you just needed to
```js
import Highcharts from 'highcharts/js/highcharts'

export default withHighcharts(MyChart, Highcharts)
```

However with Highcharts 7, you need to `import from Highcharts from 'highcharts'` add pass [`styledMode=true`](https://api.highcharts.com/highcharts/chart.styledMode) as a chart property.

I haven't checked for definite yet, but  I think from past experience this will need to be an initialisation option, and not something we can set via `chart.update`

**Comment by anajavi** [comment]
Lets make a hc7 branch?

**Comment by whawker** [comment]
Good idea, we should definitely add support for the new series types anyway.

**Comment by whawker** [comment]
Just created the `highcharts-v7` branch

**Comment by anajavi** [comment]
I created WIP pull request #194, let's continue discussion there.
