### ISSUE TITLE
"TypeError: Cannot read property '2' of undefined" in SolidGauge

### ISSUE THREAD

**Issue by matsomo** [whawker/react-jsx-highcharts#173]
#### Bug or Feature Request?
Bug

#### Description
TypeError happens when data is supplied to the data property in a Series component in SolidGauge. 

#### How to reproduce
Create a SolidGauge chart an supply data to the data property in a Series component

#### Live demo demonstrating bug
https://stackblitz.com/edit/react-rmyjp9

#### Versions
* React JSX Highcharts version: 3.3.0
* Highcharts version: 6.2.0
* React version: 16.5.0

**Comment by whawker** [comment]
Hi @matsomo, in React JSX Highcharts you need to pass the prop `gauge` to enable this functionality

```jsx
<HighchartsChart gauge plotOptions={plotOptions} pane={paneOptions}>
```

Instead of
```jsx
<HighchartsChart chart={{ type: 'solidgauge' }} plotOptions={plotOptions} pane={paneOptions}>
```

Apologies, I should make this clearer in the docs.

**Comment by matsomo** [comment]
Thanks for the fast response
