### ISSUE TITLE
Redraw chart only after all series are added

### ISSUE THREAD

**Issue by anajavi** [whawker/react-jsx-highcharts#177]
#### Bug or Feature Request?
Performance improvement.

#### Description
With lots of series and datapoints in them, mounting chart can be slow. This is because every series does redraw when it mounts.

> Potentially that could be done with an [`addSeries`](https://api.highcharts.com/highcharts/chart.events.addSeries) event that we debounce, so only the final addSeries event triggers a redraw?

> Well we don't need to know which series is last, all we care about is that the `addSeries` handler is no longer being triggered.
> 
> [Example here](https://stackblitz.com/edit/base-chart-example-e9uqbc?file=index.js)

#### Versions
* React JSX Highcharts version: 3.3.0
* Highcharts version: 6.2.0
* React version: 16.6

**Comment by anajavi** [comment]
I made a quick&dirty test with debouncing. Removed redraw from Series render and placing it like this in BaseChart:
```javascript
  debouncedHandleAfterAddSeries = debounce(() => {
    this.chart.redraw();
  }, 100);

  initHighcharts = () => {
    if (!this.domNode) {
      return;
    }

    const { chartCreationFunc, callback, polar, gauge, children, ...rest } = this.props;

    const opts = {
      chart: {
        events: {
          afterAddSeries: this.debouncedHandleAfterAddSeries
        }
      },
```

Redraw calls went down from 96 to 26. Full render time went down from about 3.5s to 1 - 1.5s.

So I would say it is worth a try.

**Comment by whawker** [comment]
Wow that's amazing! 

The code around this stuff hasn't changed since the very first prototype of this project so is definitely overdue for optimisation.

We just need to make sure that library users can still provide their own `onAfterAddSeries` handler that doesn't override our own

**Comment by whawker** [comment]
Makes sense, we could like do the same with axes and the AxisProvider too.

**Comment by anajavi** [comment]
Batching axis creations had some visible side effects. I did not check what caused them though.
