### ISSUE TITLE
Capture custom panning event in jsx based Highchart

### ISSUE THREAD

**Issue by rsoni0809** [whawker/react-jsx-highcharts#180]
I need help for feature of panning in React-jsx-highcharts.
I am trying to capture Highchart panning custom event in my line chart. So that I should be able to capture whether 2 finger panning happening from left to right or right to left and based on that I can pass parameter to load dynamic data in Highchart. Kindly help to understand how can I add custom event for panning in react-jsx-highchart. If anyone faced same issue please help to understand best solution

**Comment by whawker** [comment]
Here is an [example](https://stackblitz.com/edit/base-chart-example-j1lakb?file=index.js), I've extended the pan function to fire `pan` events on both axes with ["getExtremes"](https://api.highcharts.com/class-reference/Highcharts.Axis#getExtremes) information.

Then I've added an `onPan` event handler to the `XAxis` component.

**Comment by rsoni0809** [comment]
Thanks for this approach but when I tried same to check in touch screens I am not able to capture any event neither in onPan nor with H.fireEvent(xAxis, 'pan', xAxis.getExtremes()); 
As my approach to capture pan event on touch screen, based on xAxis[0].getExtremes().max and min point and based on pan direction  i can decide whether it is left or right pan and then pass data points accordingly.
I updated your example bit to fit mine but need help to capture event on my code. 

https://stackblitz.com/edit/react-pzwvph?file=index.js

Kindly help for this
Thanks

**Comment by whawker** [comment]
You've gone the wrong way from the example I created.

This function should be left alone, it just allows you to hook into the panning event in Axis components

```js
(function (H) {
  H.wrap(H.Chart.prototype, 'pan', function (proceed) {
    const xAxis = this.xAxis[0];
    const yAxis = this.yAxis[0]
    H.fireEvent(xAxis, 'pan', xAxis.getExtremes());
    H.fireEvent(yAxis, 'pan', yAxis.getExtremes());

    proceed.call(this, arguments[1], arguments[2]);
  });
})(Highcharts);
```

This hook is passing in the values you wanted as the event data.

Therefore `this.handlePan` just becomes

```js
handlePan = e => {
  const { min, max } = e
  if (min < max) {
    console.log("left->right swipe pan");
  } else if(min > max){
    console.log("right->left swipe pan");
  }
}
```

[Example here](https://stackblitz.com/edit/react-hqkvgd?file=index.js)

**Comment by rsoni0809** [comment]
Hi Will, Thanks for your quick response again. I got this hook since it is just event register. 
But this time also I have same point in your example: I am not able to reach inside handler "handlePan" when panning in highchart in mobile device. Please verify from your end if i am wrong from my side

**Comment by rsoni0809** [comment]
I found out alternative way to manupulate touchstart, touchmove and end event in JS but I want to do this with highchart native way which you suggested but that would be really great if this handlePan event be firing on left or right 2 finger swiping which is not happening with suggested code. I hope we can get some generic solution which will be good solution for all panning event.

Thanks,

**Comment by whawker** [comment]
You could try using the the [selection](https://api.highcharts.com/highcharts/chart.events.selection) event? 

It fires events on both pinching and panning on mobile, so you might have to find some way of figuring out the user intention for just panning. [Example here](https://stackblitz.com/edit/react-hqkvgd?file=index.js)

If that doesn't work, you'll have to raise an issue on the main Highcharts repo and ask about touch events and panning, then provide an example of how this works with vanilla Highcharts, and we can try to adapt it.
