### ISSUE TITLE
Update annotations?

### ISSUE THREAD

**Issue by knod** [whawker/react-jsx-highcharts#182]
#### Bug or Feature Request?
Not sure. There may already be a way to do this.

#### Description
First off, I can't figure out how to have just one annotation for the chart, not for every series, so ignore that part of the example for now. That aside, how do I update an annotation that should be based off of a dynamic value? One that's handed in as a prop?

#### How to reproduce
I think the examples will show it better.

#### Live demo demonstrating bug

This has a vertical line. There's a button at the bottom. When you press that button, a random number is generated and it's sent to the chart. The vertical line's x-position should then be at that x location, but it always stays in the same place:

- Version with just a function with an object: https://stackblitz.com/edit/base-chart-example-h9cxt7
- Version with lifecycle method for updating annotation: https://stackblitz.com/edit/base-chart-example-exy6bu
- Version with `onAddSeries()`: https://stackblitz.com/edit/base-chart-example-gq4kck

I took my cue on annotations from https://github.com/whawker/react-jsx-highcharts/issues/136.

#### Versions
* React JSX Highcharts version: ^3.3.0
* Highcharts version: ^6.2.0
* React version: 16.3.2

**Comment by anajavi** [comment]
Here's a quick & dirty example of updating annotations:
https://stackblitz.com/edit/base-chart-example-ejsoey?file=MyChart.js

The MyChart component is itself managing the annotations and keeping them in this.chartAnnotations.

**Comment by knod** [comment]
@anajavi : Hmm, interesting. How can we get it to appear when the component is mounted? Also, is `ant` even needed anymore?

**Comment by knod** [comment]
Forget that first question. We can just call `this.updateAnnotations()` in `getChart()`.

**Comment by knod** [comment]
Is there a way to create an annotation without `.addAnnotation()`?

**Comment by knod** [comment]
So it occurred to me that what you could do is create a data point just for the annotation and then attach the annotation to it. I started simple by removing the annotation stuff and made a new line: `<LineSeries name="X" data={[this.props.x]} />`. Thing is, it doesn't update its position when x changes either. How do I get a line to change when the value of its props change?

**Comment by knod** [comment]
The chart's `.componentDidUpdate()` does run: https://stackblitz.com/edit/base-chart-example-6yc4is?file=index.js

**Comment by knod** [comment]
That same link should show a plot line updating now. That's all I really need for this problem, but I'm going to need to be able to update line positions. Is there a solution for that?

**Comment by knod** [comment]
lol, math was never my strong suit. Thanks for pointing that out. I guess if I had any advice for people of the future it'd be to use a plot line instead of an annotation. Maybe that's not the ideal way to do it for this purpose, but it's a bit cleaner.

**Comment by anajavi** [comment]
For anybody landing here through search: as of 3.4.0 there is now component for annotations.

[Example](https://whawker.github.io/react-jsx-highcharts/examples/AreaWithAnnotations/index.html)
