### ISSUE TITLE
highstock navigator "panning across the dataset"

### ISSUE THREAD

**Issue by stevej2608** [whawker/react-jsx-highcharts#185]
I've implemented the `react-jsx-highcharts` highstock [example](https://github.com/whawker/react-jsx-highcharts/tree/master/packages/react-jsx-highstock#example-3). It displays OK but I've found that the dataset does not pan when I move the slider on the navigator. 

I'd like to see the data panning in the same way as the highstock demo [single line series](https://www.highcharts.com/stock/demo/basic-line).

I'm new to highcharts, I've looked at the navigator [API](https://api.highcharts.com/highstock/navigator) and it indicates that the dataset panning is the default.

Is this capability available, if so what do I do to enable it?

Cheers.

**Comment by whawker** [comment]
So turns out this is simpler than I thought to implement. 🤦‍♂️ 

All you need to do is include the `<Scrollbar />` component. [Example here](https://stackblitz.com/edit/base-chart-example-cm35bl?file=MyChart.js)
