### ISSUE TITLE
Possible to use React components in chart text?

### ISSUE THREAD

**Issue by knod** [whawker/react-jsx-highcharts#187]
#### Bug or Feature Request?
Feature request, I think.

#### Description
Maybe this already exists or maybe it's not possible.

Allow use of react components in chart where text or html now goes. Bonus if it can call functions from the current context.

Example use 1 (pretend it's actually useful code):
```js
var XTitle = function (title) {
  var clickHandler = function () { return true };
  return (<div onClick={clickHandler}>{title}</div>);
}

// ...
<XAxis.Title useReact = { true }>{ <XTitle title='My title' /> }</XAxis.Title>
```

Example use 2 (pretend it's actually useful code):
```js
var PlotLineLabel = function (children) {
  var clickHandler = function () { return true };
  return (<span onClick={clickHandler}>{ `I'm a ${children}` }</span>);
}

// ...
<PlotLine
  useReact = { true }
  value     = { 5 }
  label     = {{ text: <PlotLineLabel>Plot Line</PlotLineLabel> }} />
```

**Comment by whawker** [comment]
It might be possible using [React Portals](https://reactjs.org/docs/portals.html).

For instance, you could target the XAxis title with
```jsx
ReactDOM.createPortal(
  <div>Something</div>,
  document.querySelector('.highcharts-xaxis .highcharts-axis-title')`
)
```

I think there might be some issues with rendering though, i.e. wait for Chart to render, then render custom components into created DOM elements

Needs some investigation, I'll have a think.

**Comment by whawker** [comment]
See suggestion [here](https://github.com/whawker/react-jsx-highcharts/issues/215#issuecomment-505956430), but this is not something we plan to support going forward
