### ISSUE TITLE
Two bars per row in XRangeSeries

### ISSUE THREAD

**Issue by matsomo** [whawker/react-jsx-highcharts#191]
#### Bug or Feature Request?
Help needed

#### Description
I'm trying to display two bars per row in a XRangeSeries similar to this post: https://forum.highcharts.com/highcharts-usage/more-than-one-time-bar-per-task-t41237/

I've managed to create something similar, but without the remaining space being distributed equally between the two bars: https://stackblitz.com/edit/react-s7hgt3

This approach also feels very hacky since I'm using decimal points to move the bar along the y-axis, using negative numbers will render a new empty row above the first one.

I've tried to recreate the grouped data structure in this example, but I'm not
getting it to work with React: https://jsfiddle.net/BlackLabel/vjswy3kg/

#### Live demo demonstrating bug
Problem solved with gantt without React:
https://jsfiddle.net/BlackLabel/vjswy3kg/

My example: https://stackblitz.com/edit/react-s7hgt3

#### Versions
* React JSX Highcharts version: 3.3.0
* Highcharts version: 6.2.0
* React version: 16.5.0

**Comment by whawker** [comment]
It might be worth waiting for #175 to be completed, when hopefully  we will have proper Highcharts Gantt support. Rather than hacking a standard Highcharts chart to _look_ like a Gantt chart?

**Comment by jvskriubakken** [comment]
Hi @whawker 

This is one of my colleagues, working on "plan b", since we have tight time scheme, which is trying to achieve our gantt-chart goals using highcharts with x-range series.

**Comment by jvskriubakken** [comment]
Just so that I understand you right. You mean that the highcharts xrange series is hacky gantt chart?

We will take youre advice and use higcharts-gantt and the official react wrapper. 

Thanks!

**Comment by whawker** [comment]
Yes, that is what I mean. 

It seems to me that if you were able to build Gantt charts with XRange charts, Highsoft wouldn't have released a separate Gantt product?

**Comment by jvskriubakken** [comment]
> Yes, that is what I mean.
> 
> It seems to me that if you were able to build Gantt charts with XRange charts, Highsoft wouldn't have released a separate Gantt product?

Yes, I've suspected that my self. But however without real fact :) It could also be limited in functionality, but working well at what it do :) But I believe you :)
