### ISSUE TITLE
yAxis and tooltip units

### ISSUE THREAD

**Issue by pinkynrg** [whawker/react-jsx-highcharts#192]
I was trying to:
- add units to yAxis so that it shows next to the numeric value of the axis - for 1 or more yAxis.
- add units to a shared tooltip - possibility to use different units if there are series of different unit nature.

I tried with no luck, how could I accomplish the above?

Thanks a lot.

**Comment by whawker** [comment]
I think what you're looking for is [axis label formatters](https://api.highcharts.com/highcharts/yAxis.labels.formatter) and [series tooltip](https://api.highcharts.com/highcharts/series.line.tooltip) formatters/suffix?

**Comment by pinkynrg** [comment]
I was able to find my way. Thanks!
