### ISSUE TITLE
Switch webpack to rollup

### ISSUE THREAD

**Issue by anajavi** [whawker/react-jsx-highcharts#193]
#### Bug or Feature Request?

Build enhancement

#### Description

I just found out that webpack 4 by default produces UMD builds that cannot be required in node, nor automatically mocked with jest. The workarounds are quite hacky, so I am thinking about switching to rollup. Rollup seems to be used by most libraries nowadays.

**Comment by whawker** [comment]
It's an interesting thought, I'm aware [Rollup is apparently better for libraries](https://twitter.com/dan_abramov/status/849684006698455044) than Webpack, although I have never actually used Rollup before.

In terms of requiring in Node, I'm not sure what the use case for that might be? Do you mean in terms on unit testing? My first thought was isomorphic React apps, however that's not possible with this library anyway, as [Highcharts can't be rendered on the server side](https://github.com/highcharts/highcharts/issues/7058#issuecomment-322685679).

I'd like to do it bit more reading on Rollup before we go ahead. I finally feel like I have a decent grasp of Webpack concepts after struggling with it initially. So I want to make sure I understand exactly what is going on, beyond the magic.

**Comment by anajavi** [comment]
No worries, it's not urgent matter, and perhaps webpack will fix the problems.

Highcharts can't be used in isomorphic app, but it certainly can be rendered server side as our tests are already doing that. Simple use case for that would be charts included in emails.

I made a quick test with rollup, and it produced 10kB bigger bundle. I guess it was because it includes bigger parts of lodash.

I think the webpack is pretty well optimized in this project.

Let's close this issue for now?

**Comment by anajavi** [comment]
@JustFly1984 react-jsx-highcharts is not importing whole of lodash. Instead it is using tree shakable lodash-es.

There are lodash functions that should be replaced, like find and findIndex, but the eslint plugin suggests replacing them with code that does not work on IE11. With IE11 the replacements are sometimes a bit more complex than simple one-liners.

find for array could be replaced with the following snippet:
```javascript
function find(arr, condition) {
  if(!Array.isArray(arr)) return;
  return typeof arr.find === function ? arr.find(condition): arr.filter( condition )[0];
}
```

The problem with rollup is, that although[ lodash-webpack-plugin](https://github.com/lodash/lodash-webpack-plugin) should work with rollup, it is not documented and I could not get it to work.

**Comment by anajavi** [comment]
Closing this, as it can wait.
