### ISSUE TITLE
Example of multi chart like CandleStick and volume chart with Stock Tools GUI

### ISSUE THREAD

**Issue by arpitprod** [whawker/react-jsx-highcharts#195]
#### Feature Request?
react example of this [code](https://www.highcharts.com/stock/demo/stock-tools-gui) 

#### Description
1. Highchart added 2 more scripts for show Stock Tools GUI - [annotations-advanced](https://code.highcharts.com/modules/annotations-advanced.js) and [stock-tools](https://code.highcharts.com/modules/stock-tools.js) 
but how to import in react without know which function need to import

2. volume chart data is not showing in my code

#### How to reproduce

This is my react code. Here I'm importing this [ohlcv](https://www.highcharts.com/samples/data/aapl-ohlcv.json) data

	import React, { Component } from 'react';
	import Highcharts from 'highcharts/highstock';
	import fs from 'fs';
	import ohlcvdata from './utils/ohlcvdata';
	import addAnnotationsModule from 'highcharts/modules/annotations'
	import addAnnotationsAdvancedModule from 'highcharts/modules/annotations-advanced';
	import addStockToolsModule from 'highcharts/modules/stock-tools';

	import {
		HighchartsStockChart,
		Chart,
		withHighcharts,
		XAxis,
		YAxis,
		Title,
		Legend,
		AreaSplineSeries,
		SplineSeries,
		Navigator,
		RangeSelector,
		Tooltip,
		Subtitle,
		PlotBand,
		CandlestickSeries,
		ColumnSeries
	} from 'react-jsx-highstock';

	import { createRandomData } from './utils/data-helpers';
	import DateRangePickers from 'react-jsx-highstock-datepickers';
	import 'react-jsx-highstock-datepickers/dist/index.css';

	addAnnotationsModule(Highcharts);
	addAnnotationsAdvancedModule(Highcharts);
	addStockToolsModule(Highcharts);

	const annotationsArr = [
		{
			labels: [{
				point: { // See https://api.highcharts.com/highstock/annotations.labels.point
					x: 1198108800000, // Value on xAxis (timestamp)
					xAxis: 'xAxis', // XAxis ID = always "xAxis" in React JSX Highstock
					y: 0.6953, // Value on yAxis
					yAxis: 'myYAxisId' // YAxis ID
				},
				text: 'Hello'
			}]
		}
	]

	class App extends Component {

		getChart = chart => {
			this.chart = chart
		}

		addAnnotationsOnSeriesAdd = () => {
			window.setTimeout(() => {
				annotationsArr.forEach(annotation => {
					this.chart.addAnnotation(annotation)
				})
			})
		}

		constructor(props) {
			super(props);

			const now = Date.now();
			const unitSales = createRandomData(now, 1e8);
			this.state = {
				ohlc: [],
				volume: [],
				campaigns: [
					{
						from: unitSales[9][0],
						to: unitSales[23][0],
						title: 'US TV advert campaign'
					},
					{
						from: unitSales[50][0],
						to: unitSales[57][0],
						title: 'UK Radio advert campaign'
					}
				]
			};
			this.fetchOhlcvData = this.fetchOhlcvData.bind(this);
			this.renderNavPlotBand = this.renderNavPlotBand.bind(this);
		}

		componentDidMount() {
			this.fetchOhlcvData();
		}

		fetchOhlcvData() {
			const data = ohlcvdata.ohlcvdata();
			console.log('ohlcvdata - ', data);

			// split the data set into ohlc and volume
			var ohlc = [],
					volume = [],
					dataLength = data.length,
					i = 0;

			for (i; i < dataLength; i += 1) {
					ohlc.push([
							data[i][0], // the date
							data[i][1], // open
							data[i][2], // high
							data[i][3], // low
							data[i][4] // close
					]);

					volume.push([
							data[i][0], // the date
							data[i][5] // the volume
					]);
			}
			console.log('ohlc - ', ohlc);
			console.log('volume - ', volume);

			this.setState({
				ohlc,
				volume
			});
		}

		renderNavPlotBand({ from, to }) {
			const id = `nav-band-${from}-${to}`;
			return (
				<PlotBand key={id} from={from} to={to} color="rgba(68, 170, 213, 0.3)" />
			);
		}

		render() {
			const { ohlc, volume, campaigns } = this.state;

			return (
				
					<HighchartsStockChart callback={this.getChart}>
						{/* <DateRangePickers axisId="yAxis" /> */}
						<Chart onAddSeries={this.addAnnotationsOnSeriesAdd} zoomType="x" />

						<Title>CandleStick Chart Example</Title>

						<Legend>
							<Legend.Title>Key</Legend.Title>
						</Legend>

						<RangeSelector>
							<RangeSelector.Button count={1} type="day">
								1d
							</RangeSelector.Button>
							<RangeSelector.Button count={7} type="day">
								7d
							</RangeSelector.Button>
							<RangeSelector.Button count={1} type="month">
								1m
							</RangeSelector.Button>
							<RangeSelector.Button count={1} type="ytd">
								YTD
							</RangeSelector.Button>
							<RangeSelector.Button count={1} type="year">
								1y
							</RangeSelector.Button>
							<RangeSelector.Button type="all">All</RangeSelector.Button>
							<RangeSelector.Input boxBorderColor="#7cb5ec" />
						</RangeSelector>

						{/* <Tooltip /> */}
						<Tooltip padding={10} hideDelay={250} shape="square" split />

						<XAxis type="datetime">
							<XAxis.Title>Time</XAxis.Title>
						</XAxis>

						<YAxis id="myYAxisId" labels={{align: 'right', x: -3}} lineWidth={2} height='60%' resize >
							<YAxis.Title>OHLC</YAxis.Title>
							<CandlestickSeries
								id="candleStick"
								name="CandleStick"
								keys={['x', 'open', 'high', 'low', 'close']}
								data={ohlc}
							/>
						</YAxis>

						<YAxis id="volume" labels={{align: 'right', x: -3}} offset={0} lineWidth={2} top='65%' height='35%' >
							<YAxis.Title>Volume</YAxis.Title>
							<ColumnSeries id="volume" name="Volume" keys={['x', 'volume']} data={volume} yAxis={1} />
						</YAxis>

						<Navigator>
							<Navigator.Series seriesId="candleStick" />
							{/* <Navigator.Series seriesId="volume" /> */}
							<Navigator.XAxis labels={{ x: 0, y: 12 }}>
								{campaigns.map(this.renderNavPlotBand)}
							</Navigator.XAxis>
						</Navigator>

					</HighchartsStockChart>
			);
		}
	}

	export default withHighcharts(App, Highcharts);

#### Versions
* React JSX highstock version: 3.4.0
* Highcharts version: 7.0.1
* React version: 16.7.0

**Comment by arpitprod** [comment]
thanks @whawker, stock tools are not dropping lines to chart. Please check

**Comment by whawker** [comment]
Looks like it's related to this Highcharts bug highcharts/highcharts#9740. Charts in React JSX Highcharts are created dynamically (using `chart.update()` behind the scenes).

To implement the workaround suggested by Highcharts, I would suggesr adding a chart `onUpdate` handler which updates the navigation bindings.

```jsx
handleUpdate = e => {
  const chart = e.target;
  chart.navigationBindings.update();
}
```

Updated example here: https://stackblitz.com/edit/react-d18w7v?file=index.js

**Comment by arpitprod** [comment]
thanks a lot
one last thing is when we move left stock tool bar then moving icons showing behind new icon.
![chart](https://user-images.githubusercontent.com/19798516/50515470-f2853b00-0aca-11e9-9109-b3c83f749910.gif)

**Comment by whawker** [comment]
Not sure about that one. You might need to post an issue on the Highcharts repo about that.

**Comment by arpitprod** [comment]
but this working fine in Highcharts [example](https://www.highcharts.com/stock/demo/stock-tools-gui)

**Comment by arpitprod** [comment]
and when we click minimize button of stock tools then stock tools are not minimizing
