### ISSUE TITLE
Chart loading time is too much

### ISSUE THREAD

**Issue by arpitprod** [whawker/react-jsx-highcharts#196]
I am trying this [code](https://stackblitz.com/edit/react-qtatfv?file=MyChart.js), and it's working fine but when I opened this [link](https://react-qtatfv.stackblitz.io/) to other browser or incognito window then it's taking too much time and not loading many times. 

This error showing in the browser console
`Uncaught (in promise) Error: Preset not sepcified in configuration
    at Object.config (webcontainer.a966dcc4085d3fff5bb.js:15)
    at t.config (webcontainer.a966dcc4085d3fff5bb.js:15)
    at Object.PREVIEW_INSTANTIATE_BUNDLE (preview-3a0c9433aa42f56dbd90b.js:1)
    at preview-3a0c9433aa42f56dbd90b.js:1
    at Array.map (<anonymous>)
    at Object.dispatch (preview-3a0c9433aa42f56dbd90b.js:1)
    at preview-3a0c9433aa42f56dbd90b.js:1`

**Comment by whawker** [comment]
Have you tried that code within a Create React App or something? 

You shouldn't use Stackblitz for performance testing - Stackblitz is downloading the Node dependencies and compiling the code in the browser, so isn't a true representation of a what happens in a real application. These would usually be done as part of a build process before deployment.

**Comment by arpitprod** [comment]
sorry, I didn't realize this. Yes, This performance issue is not in create-react-app
