### ISSUE TITLE
mouse wheel scrolling and zoom in/out functionality in highchart and highstock chart

### ISSUE THREAD

**Issue by arpitprod** [whawker/react-jsx-highcharts#197]
#### Bug or Feature Request?

I need mouse wheel zoom In/Out and scrolling in [this](https://stackblitz.com/edit/react-qtatfv?file=style.css) stock chart. and I found [this](http://jsfiddle.net/highcharts/6etwu5b4/) highchart zoom in/out code. I tried myself with import MapNavigation from react-jsx-highstock but this error showing 
`Attempted import error: 'MapNavigation' is not exported from 'react-jsx-highstock'.`

**Comment by arpitprod** [comment]
why Date Picker is not working [here](https://stackblitz.com/edit/react-qtatfv?file=MyChart.js)?

**Comment by shankhajeet** [comment]
Was it solved or added? I am trying to get a similar zoom-in and out feature on the mouse wheel scroll.
