### ISSUE TITLE
setExtremes won't fire

### ISSUE THREAD

**Issue by supasonk-hw** [whawker/react-jsx-highcharts#198]
#### Bug or Feature Request?
Bug

#### Description
The event setExtremes won't fire when set to axis element.

#### How to reproduce

```
<XAxis {...LineChartConfig.xAxisConfig} onSetExtremes={() => { console.log('fire') }}>
 </XAxis>


```
#### Live demo demonstrating bug
https://stackblitz.com/edit/base-chart-example-rredgk?file=MyChart.js

#### Versions
* React JSX Highcharts version: 3.4.0
* Highcharts version: 6.0.7
* React version: 16.6.3

**Comment by whawker** [comment]
When are you expecting it to fire?

For instance if you make the chart zoomable (e.g. by adding a `zoomType`). Then you can see it being fired when clicking and dragging to select a portion of the chart.

```jsx
<HighchartsChart>
  <Chart zoomType="x" />
</HighchartsChart>
```

**Comment by whawker** [comment]
@supasonk-hw any response on the above?
