### ISSUE TITLE
Drill down  next level data also highlighted for next level how to avoid?

### ISSUE THREAD

**Issue by bdevika** [whawker/react-jsx-highcharts#199]
#### Bug or Feature Request?
1.how to limit the level of the drill?
2. How to maintain the color of drill down data? currently, it renders with   random color for data of next level
3. how to dynamically change the chart type which should reflect its drill-down data  using 'Series' component 

#### Versions
* React JSX Highcharts version: ^3.3.0
* Highcharts version: ^16.0.2
* React version: ^16.5.2

**Comment by whawker** [comment]
We don't really have proper support for drilldown yet (see #29), but here are a few pointers

1. I'm not sure on that, you'll have to ask Highcharts themselves.
1. Maintaining the colour should be possible via [`colorByPoint`](https://api.highcharts.com/highcharts/series.column.colorByPoint)
1. As previously stated we don't have drilldown support, I don't think this is possible in React JSX Highcharts

[Drilldown example](https://stackblitz.com/edit/base-chart-example-ungq6k?file=MyChart.js) (uses workaround)
[Vanilla JS Highcharts equivalent]( https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/column-drilldown/)
