### ISSUE TITLE
Include documentation

### ISSUE THREAD

**Issue by elisechant** [whawker/react-jsx-highcharts#2]
I think you should merge the /examples to master as it's acting as documentation, such as https://github.com/whawker/react-jsx-highcharts/pull/1.
If the reason you haven't done this is because you don't want them to be published to npm, why not add a .npmignore file and list /examples in it? As well, you could add /dist to the .gitignore

**Comment by whawker** [comment]
Yep, fair point. I guess the examples would be useful to have in both branches. I'll merge your PR.

@elisechant Excuse my ignorance, but is it possible to .gitignore the dist folder, but still include it when I publish to NPM?

**Comment by elisechant** [comment]
Cool :) I was wondering for ages where the code was! ha! oh yeah gh-pages branch!

And yes, but you need to include an .npmignore (where you dont ignore /dist), otherwise npm falls back to the .gitignore (and ignores /dist) https://stackoverflow.com/questions/31642477/how-to-publish-a-npm-package-with-distribution-files https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package
