### ISSUE TITLE
RangeSelector.selected breaks highcharts 7

### ISSUE THREAD

**Issue by mjdiamond** [whawker/react-jsx-highcharts#201]
#### Bug or Feature Request?

Possibly a Bug

#### Description - How to reproduce

When you use Highcharts 7 and Highstock, if you set a value for "selected" in RangeSelector, the chart lines/areas don't render

This doesn't happen if you don't set a "selected" value or use Highcharts 5

#### Live demo demonstrating bug

https://stackblitz.com/edit/react-vktsz2?file=DemoChart.js

#### Versions
* React JSX Highstock version: 3.4.0
* Highcharts version: 7.0.2
* React version: 16.7.0

**Comment by whawker** [comment]
Yep this is definitely a bug, just trying to figure out the root cause.

**Comment by mjdiamond** [comment]
I don't know if this helps, but the same thing happened to me about two weeks ago with a different parameter, if i recall correctly i was using Highcharts 6.x (no highstock) and if i used:

`<Chart backgroundColor="transparent" />`

the same thing happened, the chart was there but the lines/areas did not render. I solved it by setting that value using plotOptions instead, but in this case it doesn't work with RangeSelector.selected

By the way, thank you for all your work man, it is amazing.

**Comment by mjdiamond** [comment]
Found a quick workaround, for anyone who needs it:

As stated, you can't set a **RangeSelector.selected** value because it breaks the chart, but you can set **XAxis.range** to the same value (converted to milliseconds) of the RangeSelector that you want to pre-select, and as the values match, it gets selected automatically

In my bug example id had three selectors (10days, 15days, 20days) and i wanted to select the [1] (15days), by doing:

`<RangeSelector selected={1}>
. . .
</RangeSelector>`

Instead, you can do:

`<RangeSelector>
. . .
</RangeSelector>
. . .
<XAxis range={10 * 24 * 60 * 60 * 1000}>`

_That would be 15 days * 24 hs * 60 min * 60 sec * 1000 millisec_

Fixed working example here:
https://stackblitz.com/edit/react-4mvpcc?file=DemoChart.js

Cheers!

**Comment by whawker** [comment]
@mjdiamond the easiest solution seems to be using the `RangeSelector` **after** the axes

i.e. https://stackblitz.com/edit/react-d9rpm4?file=DemoChart.js

It's not the best solution, but it prevents me having to keep track of internal Highcharts events that seem to be renamed across versions.
