### ISSUE TITLE
How do I put a static straight line at a specific Y?

### ISSUE THREAD

**Issue by rclai** [whawker/react-jsx-highcharts#205]
Sorry if this is the wrong place to ask, but I have a multi-series step line chart, and was wondering how to put a static emphasized horizontal line at a specific Y value? It probably doesn't need to be part of a series, is there something on the grid that I can mess with to do this?

**Comment by rclai** [comment]
Nevermind, looks like I can do it via the Annotation.

**Comment by whawker** [comment]
Might also be worth looking at Plotlines or Plotbands?

**Comment by rclai** [comment]
Is it literally just this?

```
<YAxix>
  <PlotLine value={500 />
</YAxis>
```
