### ISSUE TITLE
Charts are visibly refreshing when updated

### ISSUE THREAD

**Issue by pinkynrg** [whawker/react-jsx-highcharts#209]
On version 3.3 this is not happening.

From version 3.4 it almost looks like that updated charts disappear and reappear in a blink of an eye, but it is visible.

**Comment by kMeillet** [comment]
I got the exact same problem.

I'm using Highstock with react-jsx-highcharts.

Navigator is enabled (set to 1mn).

LineSeries work well.

But ColumnSeries refresh the whole chart.

**Comment by whawker** [comment]
Apologies for the late reply, my son was born 5 weeks ago, and I haven't had time to look after my open source stuff. Looking into this now.

**Comment by whawker** [comment]
@pinkynrg can you please give more information on how to reproduce what you are seeing. Ideally a CodeSandbox/Stackblitz reproducing the problem, or even information on which series types/browser you are using.

@pinkynrg and @kMeillet by any chance, is the issue you're seeing on Firefox or Safari? Just wondering if it's related to this bug https://github.com/highcharts/highcharts/issues/9245

**Comment by pinkynrg** [comment]
Right now I don't have a lot of time but I can tell you right now that the
issue is happening on Chrome too.

**Comment by whawker** [comment]
How many data points do the series on your charts general have? Are you using Highcharts boost module?

**Comment by pinkynrg** [comment]
Generally not more than 300 points per chart so no, I'm not using Highcharts boost, since I don't think the data load is high enough to justify its use.

**Comment by whawker** [comment]
Would either of you be able to post an example of your code? It's difficult to debug in the dark here.

**Comment by jhartling** [comment]
Here's a reproduction: https://stackblitz.com/edit/base-chart-example-h2gjjk

**Comment by whawker** [comment]
Thanks @jhartling, I have managed to reproduce on vanilla Highcharts, so I have raised the follow issue https://github.com/highcharts/highcharts/issues/10883
