### ISSUE TITLE
DelayRender can throw if React component is unmounted

### ISSUE THREAD

**Issue by kMeillet** [whawker/react-jsx-highcharts#210]
1) Make empty chart : init with empty series array : []
2) Chart render with empty series.

3) Load async data every second with setInterval. Every second, a new array is created.
4) That cause fast redraw of chart (every second).

5) Try to visit another page (or unmount component) just after data fetch but before chart redraw.
6) You should see an error in your console from DelayRender component.

---> Interval tick.
---> State update.
---> Series component render with updated state (call a DelayRender ?).
---> Unmount component (visit another page, ...).
---> DelayRender handle state update but the whole component tree is unmounted (including himself) ?

```js
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in DelayRender (created by Axis.Provider(AxisTitle))
    in Axis.Provider(AxisTitle) (created by Context.Consumer)
    in Chart.Provider(Axis.Provider(AxisTitle)) (created by Context.Consumer)
    in Highcharts.Provider(Chart.Provider(Axis.Provider(AxisTitle))) (at Chart2D.js:114)
    in Axis (created by Context.Consumer)
    in Chart.Provider(Axis) (created by Context.Consumer)
    in Highcharts.Provider(Chart.Provider(Axis)) (created by XAxis)
    in XAxis (created by Context.Consumer)
    in Chart.Provider(XAxis) (created by Context.Consumer)
    in Highcharts.Provider(Chart.Provider(XAxis)) (at Chart2D.js:113)
    in div (created by BaseChart)
    in BaseChart (created by HighchartsStockChart)
    in HighchartsStockChart (created by Context.Consumer)
    in Highcharts.Provider(HighchartsStockChart) (at Chart2D.js:85)
    in div (at Chart2D.js:147)
    in Unknown (created by HighchartsWrappedComponent)
    in HighchartsWrappedComponent (at Dashboard.js:150)
```

**Comment by whawker** [comment]
Apologies for the late reply, my son was born 5 weeks ago, and I haven't had time to look after my open source stuff. Looking into this now.

**Comment by whawker** [comment]
Could you post an example of your code? The DelayRender component should only be mounted once, it should not be to be remounted every time the series data is updated.
