### ISSUE TITLE
Feature Request: Use HTML in PlotBand.Label

### ISSUE THREAD

**Issue by corby** [whawker/react-jsx-highcharts#215]
b.t.w.: Love this library

#### Bug or Feature Request?
Have PlotBand.Label pay attention to the useHTML=true tag

#### Description
When I set the useHTML=true flag it would be nice to be able to use the embedded react element in the HTML

#### How to reproduce
```
<XAxis min={0} max={10}>
  <PlotBand from={1} to={5} color={'blue'}>
    <PlotBand.Label align={'center'} textAlign={'center'} verticalAlign={'top'} useHTML={true}>
      <img src={a.icon_url} alt={'icon'} style={{height:25px, width:25px}} onClick={this.handleClick}/>
    </PlotBand.Label>
  </PlotBand>
</XAxis>
```

#### Versions
"react-jsx-highstock": "^3.6.0"
"highcharts": "^7.1.2",
"react": "latest"

**Comment by corby** [comment]
P.S. Using the text attribute in PlotBand.Label works as a workaround, but it has to be pure HTML, not react.

**Comment by anajavi** [comment]
This could be done with React Portals, but in very hacky way:
1. pass element with id to plotband text: <span id="my-id" />
2. wait for highcharts to render it
3. myspan = document.getElementById("my-id")
4. render children to myspan with: return ReactDOM.createPortal(props.children, myspan)

I think it is too hacky, as there is no any kind of guarantee that highcharts does not rerender the passed element whenever it wants.

**Comment by whawker** [comment]
Yeah it is a bit hacky to make it work, I'm not sure I'd want to add it as a properly supported feature as it seems brittle.

[Here is an example](https://stackblitz.com/edit/base-chart-example-tupgc9?file=PlotBandPortal.js) of a `PlotBandPortal` component I created, that I use instead of the normal `PlotBand.Label` component, that seems to do what you're looking for.

**Comment by whawker** [comment]
@corby does that address your issue?
