### ISSUE TITLE
original zoom when update hightsotck chart

### ISSUE THREAD

**Issue by hamcher** [whawker/react-jsx-highcharts#219]
how to make original zoom when update the data of hightstock chart

**Comment by whawker** [comment]
I'm not sure exactly what you mean by "original zoom", but you could do a `chart.zoomOut()` using a React JSX Highcharts `callback`

[Example](https://stackblitz.com/edit/base-chart-example-72uxsv?file=MyChart.js)

**Comment by hamcher** [comment]
thanks
