### ISSUE TITLE
HighchartsStock with RangeSelector during unmount throws error

### ISSUE THREAD

**Issue by theappbanq** [whawker/react-jsx-highcharts#22]
First of all, nice job for implementing this great highcharts react component.

I started to follow one of the highstock examples that has range selector; everything works well except when you change the route and component needs to unmount; it throws the following error.
`Uncaught TypeError: Cannot read property 'rangeSelector' of undefined`
When I remove the range selector everything goes normal.
Anybody has any suggestions?

This is the code.

```
<HighchartsStockChart>
  <Chart zoomType="x" />

  <Title>Highstocks Example</Title>

  <Legend>
    <Legend.Title>Key</Legend.Title>
  </Legend>

  <RangeSelector>
    <RangeSelector.Button count={1} type="day">1d</RangeSelector.Button>
    <RangeSelector.Button count={7} type="day">7d</RangeSelector.Button>
    <RangeSelector.Button count={1} type="month">1m</RangeSelector.Button>
    <RangeSelector.Button type="all">All</RangeSelector.Button>
  </RangeSelector>

  <Tooltip />

  <XAxis>
    <XAxis.Title>Time</XAxis.Title>
  </XAxis>

  <YAxis id="price">
    <YAxis.Title>Price</YAxis.Title>
    <AreaSplineSeries id="profit" name="Profit" data={data1} />
  </YAxis>

  <YAxis id="social" opposite>
    <YAxis.Title>Social Buzz</YAxis.Title>
    <SplineSeries id="twitter" name="Twitter mentions" data={data2} />
  </YAxis>

  <Navigator>
    <Navigator.Series seriesId="profit" />
    <Navigator.Series seriesId="twitter" />
  </Navigator>
</HighchartsStockChart>
```

**Comment by whawker** [comment]
Damn another unmounting issue. I can see you've made a fix commit above, planning to open a pull request?

**Comment by SumBeam** [comment]
@whawker Hey, thanks for your reaction. I'm running into the same issues.

I can create a pull request for you with this fix.

After this is fixed, can you make a prerelease of highstock and highcharts package on npm so I can test the new version?

Somehow I can't build the packages myself and include it to test into my own project..

**Comment by whawker** [comment]
No worries of course, thanks for the PR!

Published
* `react-jsx-highcharts@1.3.4-pre.1`
* `react-jsx-highstock@1.3.4-pre.1`

**Comment by SumBeam** [comment]
Thanks for the update! This problem is fixed with your new release :)

Got another unmount issue back for it, but I will create a new issue for that.

**Comment by theappbanq** [comment]
@whawker Sorry for the late reply, I didn't get any notification regarding your comment. Next time I would propose a pull request.
