### ISSUE TITLE
dont work in ie

### ISSUE THREAD

**Issue by suunryo** [whawker/react-jsx-highcharts#222]
#### Bug or Feature Request?
it's not work in ie

#### Description
error code is ' return function (...i) '.
you can search in react-jsx-highcharts/dist/react-jsx-highcharts.min.js
ie is not supported this

#### How to reproduce
fix

#### Versions
* React JSX Highcharts version: 
* Highcharts version: 
* React version:

**Comment by anajavi** [comment]
The examples are broken in IE11. Not sure what is wrong with them, the IE debugger does not help much.

**Comment by anajavi** [comment]
debounce-raf causes this bug by using object spread https://github.com/hyperdivision/debounce-raf/issues/1

**Comment by suunryo** [comment]
IE does not support spread(...) operator (Es6) syntax.
but, it appears in the react-jsx-highcharts.min.js
you can search (...i) in this file

**Comment by anajavi** [comment]
Fixing this now requires pulling code of debounce-raf to this project. Otherwise everyone using react-jsx-highcharts needs to add webpack hack mentioned in debounce-raf ticket.

The other way would be to fix the code in debounce-raf, maybe like this: https://vanillajstoolkit.com/helpers/debounce/

What do you think @whawker ? Should we pull the code, it is very short anyway?

**Comment by whawker** [comment]
Interesting thanks for investigating everyone.

I think we should be able to pull in the workaround from https://github.com/hyperdivision/debounce-raf/issues/1 into our own [`webpack.config.js`](https://github.com/whawker/react-jsx-highcharts/blob/master/packages/react-jsx-highcharts/webpack.config.js#L50-L56)

**Comment by anajavi** [comment]
The workaround works only for the UMD bundle. The ESM build still pulls debounce-raf straight from node_modules.

**Comment by whawker** [comment]
Good point. Yeah I think pulling the code into this project as a util, and removing the `debounce-raf` dependency is our best bet.

**Comment by anajavi** [comment]
I don't have any projects supporting IE 11 anymore. Probably the browser will go away in the next months as Windows 7 support is ending in January 2020.

How do you feel about dropping support for IE 11 altogether in next major version?

**Comment by whawker** [comment]
Happy to drop IE11 support in the next major, but I'll likely add a wiki page to highlight workarounds (if they exist), as people will still raise issues despite what it states on the readme

**Comment by anajavi** [comment]
I think the same workaround as in debounce-raf works for webpack.

**Comment by suunryo** [comment]
So,, please update its version on npm. thanks

**Comment by whawker** [comment]
Published as 3.6.1
