### ISSUE TITLE
Gauge example not works

### ISSUE THREAD

**Issue by freliberty** [whawker/react-jsx-highcharts#225]
I try gauge example but it doesn't works. (react-jsx-highcharts/examples/Gauge/App.js)

`Cannot read property '0' of undefined  at eval (highcharts.js:378)`

if i remove Panne component, I have :
` b.init is not a function  at c.Chart.initSeries (highcharts.js:272)`

Can you check or update your exemple? Thx

**Comment by iamiota** [comment]
````
import Highcharts from 'highcharts'
import addHighchartsMore from 'highcharts/highcharts-more'
import addSolidGaugeModule from 'highcharts/modules/solid-gauge'

addHighchartsMore(Highcharts)
addSolidGaugeModule(Highcharts)
````
Add them to the top.
I wrote an example:
https://codesandbox.io/embed/shy-breeze-w0zsd

**Comment by freliberty** [comment]
Thx you for the example. It's work now.
