### ISSUE TITLE
No Data Text and Style Customization 

### ISSUE THREAD

**Issue by attiqe** [whawker/react-jsx-highcharts#231]
#### Description
I know that to show the no data, I need to add the module *addNoDataModule* but I want to customize the text and style. 

#### Live demo demonstrating bug
https://stackblitz.com/edit/rjh-no-data-ckgqxs

#### Versions
* Highcharts version: 7.1.3
* React version: 16.9.0

**Comment by anajavi** [comment]
Here's a working example:
https://stackblitz.com/edit/rjh-no-data-x6lgup?file=MyChart.js

**Comment by attiqe** [comment]
Awesome thanks.
