### ISSUE TITLE
React.createElement: type is invalid

### ISSUE THREAD

**Issue by kpchand** [whawker/react-jsx-highcharts#233]
#### Description

Here is the code for the 'Graph' component:

```
import React from 'react';
import Highcharts from 'highcharts/highstock';
import {HighchartsStockChart, Chart, Title, Tooltip, YAxis, CandlestickSeries, LineSeries, Navigator, withHighcharts} from 'react-jsx-highstock';
import {getHCDataset} from '../../lib/highChartsUtils';


class Graph extends React.Component {

    render() {
        console.log("here");
        const {instructions, apiData} = this.props;
        const graphData = getHCDataset(instructions, apiData);
        const ohlcData = graphData[0];
        const lineData = graphData.slice(1);
        console.log("ohlc data: ", ohlcData);
        console.log("rest of data: ", lineData);
        return (
          <HighchartsStockChart>
              <Chart/>
              <Title>Index EOD Analysis</Title>

              <Tooltip shared={true} split={false} />

              <YAxis>
                  <YAxis.Title>Price</YAxis.Title>
                  <CandlestickSeries id="ohlc" data={ohlcData.data} />
              </YAxis>

              {lineData.map(d => (
                  <YAxis>
                      <YAxis.Title>d.name</YAxis.Title>
                      <LineSeries data={d.data}/>
                  </YAxis>
              ))}
              <Navigator>
                  <Navigator.series seriesId="ohlc" color="black"/>
              </Navigator>
          </HighchartsStockChart>
        );
    }
}

export default withHighcharts(Graph, Highcharts);

```

Console logs for prop values(Redacted for clarity):

ohlc data: 
{
  "name": "OHLC",
  "data": [
    [
      1553731200000,
      11463.65,
      11588.5,
      11452.45,
      11570
    ],
    [
      1553817600000,
      11625.45,
      11630.35,
      11570.15,
      11623.9
    ],
    .....
}

rest of data:
[
  {
    "name": "Net Seller Index",
    "data": [
      [
        1553731200000,
        56533
      ],
     ...
    ]
  }
]

#### How to reproduce
Errors:

Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check your code at Graph.js:36.
    in Graph (created by HighchartsWrappedComponent)
    in HighchartsWrappedComponent (at Fetcher.js:40)
    in Fetcher (at Form.js:83)
    in div (created by Styled(MuiBox))
    in Styled(MuiBox) (at Form.js:82)
    in Form (at src/index.js:24)
    in div (created by Styled(MuiBox))
    in Styled(MuiBox) (at src/index.js:23)
    in Provider (at src/index.js:19)
    in App (at src/index.js:33)

react-dom.development.js:26563 Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `Graph`.
    at http://localhost:3000/static/js/1.chunk.js:141202:38
    at createFiberFromTypeAndProps (http://localhost:3000/static/js/1.chunk.js:141205:17)
    at createFiberFromElement (http://localhost:3000/static/js/1.chunk.js:141225:19)
    at createChild (http://localhost:3000/static/js/1.chunk.js:129698:32)
    at reconcileChildrenArray (http://localhost:3000/static/js/1.chunk.js:129967:29)
    at reconcileChildFibers (http://localhost:3000/static/js/1.chunk.js:130334:18)
    at reconcileChildren (http://localhost:3000/static/js/1.chunk.js:132681:32)
    at updateFragment (http://localhost:3000/static/js/1.chunk.js:132874:7)
    at beginWork$1 (http://localhost:3000/static/js/1.chunk.js:134753:18)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/1.chunk.js:115002:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/1.chunk.js:115051:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/1.chunk.js:115104:35)
    at beginWork$$1 (http://localhost:3000/static/js/1.chunk.js:140350:11)
    at performUnitOfWork (http://localhost:3000/static/js/1.chunk.js:139255:16)
    at workLoopSync (http://localhost:3000/static/js/1.chunk.js:139231:26)
    at performSyncWorkOnRoot (http://localhost:3000/static/js/1.chunk.js:138792:15)
    at http://localhost:3000/static/js/1.chunk.js:126952:28
    at unstable_runWithPriority (http://localhost:3000/static/js/1.chunk.js:159671:16)
    at runWithPriority$2 (http://localhost:3000/static/js/1.chunk.js:126898:14)
    at flushSyncCallbackQueueImpl (http://localhost:3000/static/js/1.chunk.js:126947:11)
    at flushSyncCallbackQueue (http://localhost:3000/static/js/1.chunk.js:126935:7)
    at scheduleUpdateOnFiber (http://localhost:3000/static/js/1.chunk.js:138210:13)
    at Object.enqueueSetState (http://localhost:3000/static/js/1.chunk.js:128740:9)
    at DelayRender.push../node_modules/react/cjs/react.development.js.Component.setState (http://localhost:3000/static/js/1.chunk.js:155087:20)
    at http://localhost:3000/static/js/1.chunk.js:146210:18
(anonymous) @ react-dom.development.js:26563
createFiberFromTypeAndProps @ react-dom.development.js:26566
createFiberFromElement @ react-dom.development.js:26586
createChild @ react-dom.development.js:15059
reconcileChildrenArray @ react-dom.development.js:15328
reconcileChildFibers @ react-dom.development.js:15695
reconcileChildren @ react-dom.development.js:18042
updateFragment @ react-dom.development.js:18235
beginWork$1 @ react-dom.development.js:20114
callCallback @ react-dom.development.js:363
invokeGuardedCallbackDev @ react-dom.development.js:412
invokeGuardedCallback @ react-dom.development.js:465
beginWork$$1 @ react-dom.development.js:25711
performUnitOfWork @ react-dom.development.js:24616
workLoopSync @ react-dom.development.js:24592
performSyncWorkOnRoot @ react-dom.development.js:24153
(anonymous) @ react-dom.development.js:12313
unstable_runWithPriority @ scheduler.development.js:818
runWithPriority$2 @ react-dom.development.js:12259
flushSyncCallbackQueueImpl @ react-dom.development.js:12308
flushSyncCallbackQueue @ react-dom.development.js:12296
scheduleUpdateOnFiber @ react-dom.development.js:23571
enqueueSetState @ react-dom.development.js:14101
push../node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:325
(anonymous) @ DelayRender.js:46
requestAnimationFrame (async)
componentDidMount @ DelayRender.js:44
commitLifeCycles @ react-dom.development.js:21933
commitLayoutEffects @ react-dom.development.js:25266
callCallback @ react-dom.development.js:363
invokeGuardedCallbackDev @ react-dom.development.js:412
invokeGuardedCallback @ react-dom.development.js:465
commitRootImpl @ react-dom.development.js:25002
unstable_runWithPriority @ scheduler.development.js:818
runWithPriority$2 @ react-dom.development.js:12259
commitRoot @ react-dom.development.js:24843
finishSyncRender @ react-dom.development.js:24220
performSyncWorkOnRoot @ react-dom.development.js:24194
(anonymous) @ react-dom.development.js:12313
unstable_runWithPriority @ scheduler.development.js:818
runWithPriority$2 @ react-dom.development.js:12259
flushSyncCallbackQueueImpl @ react-dom.development.js:12308
flushSyncCallbackQueue @ react-dom.development.js:12296
scheduleUpdateOnFiber @ react-dom.development.js:23571
enqueueSetState @ react-dom.development.js:14101
push../node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:325
(anonymous) @ BaseChart.js:82
requestAnimationFrame (async)
componentDidMount @ BaseChart.js:107
commitLifeCycles @ react-dom.development.js:21933
commitLayoutEffects @ react-dom.development.js:25266
callCallback @ react-dom.development.js:363
invokeGuardedCallbackDev @ react-dom.development.js:412
invokeGuardedCallback @ react-dom.development.js:465
commitRootImpl @ react-dom.development.js:25002
unstable_runWithPriority @ scheduler.development.js:818
runWithPriority$2 @ react-dom.development.js:12259
commitRoot @ react-dom.development.js:24843
finishSyncRender @ react-dom.development.js:24220
performSyncWorkOnRoot @ react-dom.development.js:24194
scheduleUpdateOnFiber @ react-dom.development.js:23560
scheduleRootUpdate @ react-dom.development.js:26932
updateContainerAtExpirationTime @ react-dom.development.js:26958
updateContainer @ react-dom.development.js:27058
(anonymous) @ react-dom.development.js:27639
unbatchedUpdates @ react-dom.development.js:24345
legacyRenderSubtreeIntoContainer @ react-dom.development.js:27638
render @ react-dom.development.js:27729
./src/index.js @ index.js:33
__webpack_require__ @ bootstrap:785
fn @ bootstrap:150
0 @ dataFetchers.js:37
__webpack_require__ @ bootstrap:785
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.chunk.js:1
index.js:1375 The above error occurred in one of your React components:
    in Hidden (created by NavigatorAxis)
    in NavigatorAxis (created by Context.Consumer)
    in DelayRender (created by Axis.Provider(NavigatorAxis))
    in Axis.Provider(NavigatorAxis) (created by Context.Consumer)
    in Chart.Provider(Axis.Provider(NavigatorAxis)) (created by Context.Consumer)
    in Highcharts.Provider(Chart.Provider(Axis.Provider(NavigatorAxis))) (created by NavigatorXAxis)
    in NavigatorXAxis (created by Navigator)
    in Navigator (created by Context.Consumer)
    in Chart.Provider(Navigator) (created by Context.Consumer)
    in Highcharts.Provider(Chart.Provider(Navigator)) (at Graph.js:35)
    in div (created by BaseChart)
    in BaseChart (created by HighchartsStockChart)
    in HighchartsStockChart (created by Context.Consumer)
    in Highcharts.Provider(HighchartsStockChart) (at Graph.js:18)
    in Graph (created by HighchartsWrappedComponent)
    in HighchartsWrappedComponent (at Fetcher.js:40)
    in Fetcher (at Form.js:83)
    in div (created by Styled(MuiBox))
    in Styled(MuiBox) (at Form.js:82)
    in Form (at src/index.js:24)
    in div (created by Styled(MuiBox))
    in Styled(MuiBox) (at src/index.js:23)
    in Provider (at src/index.js:19)
    in App (at src/index.js:33)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.

#### Versions

+-- highcharts@7.0.0
+-- highcharts-react-official@2.2.2
+-- react-jsx-highstock@3.6.1
| `-- react-jsx-highcharts@3.6.1

**Comment by anajavi** [comment]
In:
```jsx
              <Navigator>
                  <Navigator.series seriesId="ohlc" color="black"/>
              </Navigator>
```

You have Navigator.series (lowercase) where it should be Navigator.Series (uppercase).
