### ISSUE TITLE
ColumnSeries Color When number repeat

### ISSUE THREAD

**Issue by pablomagalhaes** [whawker/react-jsx-highcharts#242]
#### Bug or Feature Request?

Hi, I have one problema with ColumnSeries.
Because i need to repeat color when number repeat like example below

#### Description

i need to repeat color when number repeat like example below:

    <HighchartsChart plotOptions={plotOptionsB}>
        <Chart />
      <Legend />
        <XAxis categories={[]} />
        <YAxis>
            <ColumnSeries color='#FF0000' data={[1]} />
            <ColumnSeries  color='#FF0000' data={[1]} />
            <ColumnSeries  color='#FF02bb' data={[2]} />
            <ColumnSeries  color='#FF02bb' data={[2]} />
        </YAxis>
      </HighchartsChart>

But This is a Loop 

#### How to reproduce

Using ColumnSeries

#### Live demo demonstrating bug

https://stackblitz.com/edit/base-chart-example-xsurfm

#### Versions
* React JSX Highcharts version: Last
* Highcharts version: 
* React version:  Last

**Comment by whawker** [comment]
Hi @pablomagalhaes did you past the correct example link there? It seems to be unrelated to your issue?

**Comment by whawker** [comment]
I may be misunderstanding your issue, but are you looking to get columns to be the same color, if their data value is the same?

Something like this: https://stackblitz.com/edit/base-chart-example-dpuheo?file=MyChart.js ?

**Comment by pablomagalhaes** [comment]
Thank you so much
