### ISSUE TITLE
How to color only side in AreaSplineSeries

### ISSUE THREAD

**Issue by pablomagalhaes** [whawker/react-jsx-highcharts#243]
#### Bug or Feature Request?

Request

#### Description
I need color only RIGHT side of AreaSplineSeries in vertical 

#### How to reproduce

https://codesandbox.io/s/wrapping-lineseries-in-a-div-causes-yaxis-to-not-show-numbers-ncvj6?fontsize=14

#### Live demo demonstrating bug

https://codesandbox.io/s/wrapping-lineseries-in-a-div-causes-yaxis-to-not-show-numbers-ncvj6?fontsize=14

#### Versions
* React JSX Highcharts version: 
* Highcharts version: 
* React version:

**Comment by pablomagalhaes** [comment]
hI @anajavi - Is work, but i need to show line or curve lines. You understand me? 
Fill is transparent but i need the line bords.

**Comment by anajavi** [comment]
Then [negativeFillColor](https://api.highcharts.com/highcharts/series.areaspline.negativeFillColor): transparent should do the trick.

**Comment by pablomagalhaes** [comment]
Thanks @anajavi - It's work!
