### ISSUE TITLE
Switching StyleByCSS dynamically

### ISSUE THREAD

**Issue by biskit** [whawker/react-jsx-highcharts#244]
#### Bug or Feature Request?
Bug

#### Description
Trying to switch between two themes dynamically, but cannot

#### How to reproduce
In code do
```
        if (dark) {
            require('../../node_modules/highcharts/css/themes/dark-unica.css');
        } else {
            require('../../node_modules/highcharts/css/highcharts.css');
        }
```
if you toggle dark to false, the theme does not change

#### Versions
* React JSX Highcharts version: 
3.6.0
* Highcharts version: 
7.1.2
* React version: 
16.8.4

**Comment by whawker** [comment]
I don't think that's how `require` works, I don't think it will unload the previous CSS files when you switch.

You might be best adding a stylesheet with an id, and changing the `href` it points to?

```html
<link rel="stylesheet" id="theme" href="https://code.highcharts.com/css/highcharts.css" />
```

Then using a lifecycle method, switch the value of that `href` prop

```js
  componentDidUpdate (prevProps, prevState) {
    const { isDarkTheme } = this.state

    if (prevState.isDarkTheme !== isDarkTheme) {
      const styleSheetElem = document.getElementById('theme')
      styleSheetElem.setAttribute('href', isDarkTheme ? DARK_THEME_CSS : LIGHT_THEME_CSS)
    }
  }
```

Example [here](https://base-chart-example-1d26aj.stackblitz.io)
Code [here](https://stackblitz.com/edit/base-chart-example-1d26aj?file=index.html)

**Comment by biskit** [comment]
It seems like it will work as your example clearly demonstrates. I also use react-router v4 and there's routing based on link that conflicts with this (as react-router takes control of it and stumbles).

**Comment by biskit** [comment]
Was loading resource locally and there were issues with MIME checking but all sorted out. It works and it's brilliant. Thanks for making this npm.
