### ISSUE TITLE
ScrollBar reset to top position

### ISSUE THREAD

**Issue by AppleWeed21** [whawker/react-jsx-highcharts#246]
### Bug

Hi, I've an issue with react-jsx-highcharts, I explain :

I've my CustomChart with his properties on a Dashboard component extends from React.Component. 

My CustomChart component have a scrollbar property wich is enabled (true) when many datas are displaying (> 10) and disabled (false) when only 1 data is displayed.

My problem is when I click on 1 data I apply some filters wich display to me only 1 data on my CustomChart but CustomChart keep labels on Y Axis.

The CustomChart with filters work only on the first 10 datas cause CustomChart screen has been scrolled at least once in the other cases and can't re-scroll to top automatically when filters are applied.

That's I try to do is to scroll automatically to top when 1 data are clicked for display only this last one on screen without bugs.

If someone have any ideas for fix it.

Thank you in advance for your help.

**Comment by anajavi** [comment]
Can you please provide a reproduction in stackblitz?

For example, create a fork of https://stackblitz.com/edit/base-chart-example

**Comment by AppleWeed21** [comment]
My App is a big app with so many depedencies so I can't reproduct the bug dynamically but  I can give you some pictures and explain it :

At the begining my chart is uploaded with data :
![datas](https://user-images.githubusercontent.com/16223446/68199832-0dfc8480-ffbf-11e9-9bd8-9985775d2117.png)

If I scroll at least 1 time and click on 1 data I apply filter which is selected this data :
![data-onclick](https://user-images.githubusercontent.com/16223446/68199963-47cd8b00-ffbf-11e9-907b-937bf68396ee.png)

When data clicked I've this bug :
![data-clicked](https://user-images.githubusercontent.com/16223446/68200018-5ddb4b80-ffbf-11e9-8a6f-2acacdc8c3fa.png)

But If I scroll to top my data is loaded and displayed : 
![data-unique](https://user-images.githubusercontent.com/16223446/68200073-764b6600-ffbf-11e9-917c-f1f5fde3c9b1.png)
 
If I click on data without scrolling my chart the filter get applied and data has been correctly displayed without scrolling to top : 
![data-onCLick-noScroll](https://user-images.githubusercontent.com/16223446/68200266-cb877780-ffbf-11e9-97ac-4a0ab06d9e07.png)

![data-unique-noScroll](https://user-images.githubusercontent.com/16223446/68200273-ce826800-ffbf-11e9-94a7-3587641a573e.png)

Actually, as you can see,  my solution is to keep the scrollbar on and get to top manually to display the data clicked.

**Comment by anajavi** [comment]
I am sorry, but this interaction is just too complex to debug without a reproduction.

**Comment by AppleWeed21** [comment]
I know is too complex cause of many dependencies in my project so for the moment I always let the scrollbar enabled and I will see later for debug with colleagues.

Thank you for your time.
