### ISSUE TITLE
Scroll Bar implementation on chart level for Mobile View 

### ISSUE THREAD

**Issue by Praveen8529** [whawker/react-jsx-highcharts#258]
-Need  a help-
 
I am trying to implement scroll bar for mobile and Ipad version but could'nt get through the implementation. can you please suggest how to implement below code in React.
 
chart: {
        scrollablePlotArea: {
            minWidth: 1200
        }
    }

I need to restrict the width of the chart and once it come to that point, need to enable the scrool.
#### Live demo demonstrating bug
https://stackblitz.com/edit/react-vogkqt?file=BenchMarkChart.js

Thanks for the Quick reply

**Comment by anajavi** [comment]
Can you please elaborate.

**Comment by Praveen8529** [comment]
> Can you please elaborate.

-Need a help-

I am trying to implement scroll bar for mobile and Ipad version but could'nt get through the implementation. can you please suggest how to implement below code in React.

chart: {
scrollablePlotArea: {
minWidth: 1200
}
}

I need to restrict the width of the chart and once it come to that point, need to enable the scrool.

Live demo demonstrating bug
https://stackblitz.com/edit/react-vogkqt?file=BenchMarkChart.js

Thanks for the Quick reply

**Comment by Praveen8529** [comment]
Working Code using Plain JS - https://stackblitz.com/edit/react-hketvd?file=index.js

**Comment by anajavi** [comment]
I upgraded highcharts in your example to v7.2.1 and the scrollbar appeared. Is this what you were looking for?

https://stackblitz.com/edit/react-qc6ppq?file=BenchMarkChart.js

**Comment by Praveen8529** [comment]
yes, on top of this how can we implement below code in React using 'react-jsx-highstock'

chart: {
scrollablePlotArea: {
minWidth: 1200
}

**Comment by anajavi** [comment]
Here's an example with scrollablePlotArea: https://stackblitz.com/edit/react-mamemq?file=BenchMarkChart.js

**Comment by Praveen8529** [comment]
Yes. I am cleared.

Thanks for the quick help :)
