### ISSUE TITLE
Support colors

### ISSUE THREAD

**Issue by will-stone** [whawker/react-jsx-highcharts#26]
Adding `colors` to plotOptions, or to Chart component as a prop appears to have no effect.

PS still loving this project over that _other_ React Highcharts wrapper :-) I'll try to patch and submit merge requests where I can, but can't see where this would go. Is it here? https://github.com/whawker/react-jsx-highcharts/blob/master/packages/react-jsx-highcharts/src/components/BaseChart/BaseChart.js#L34

**Comment by whawker** [comment]
Glad you like it! 😀 

Hmm I'm surprised that doesn't work, when you say passed "as a prop" do you mean...

```jsx
<HighchartsChart colors={['#2f7ed8', '#0d233a', '#8bbc21', '#910000', '#1aadce', 
   '#492970', '#f28f43', '#77a1e5', '#c42525', '#a6c96a']}>
 // etc
</HighchartsChart>
```

`colors` wouldn't be passed as part of `plotOptions` as that is not how you pass it via Highcharts config.

**Comment by will-stone** [comment]
Ahh, gotcha. I was misunderstanding how the config translated into props. I still find it a little confusing. It appears some top level config have their own components and some are expected to go on the HighchartsChart as props. Maybe all top-level config chould be components, and those that don't have child keys (like colors) use children? e.g.
```
<HighchartsChart>
...
<colors>
  {['#2f7ed8', '#0d233a', '#8bbc21', '#910000', '#1aadce', 
   '#492970', '#f28f43', '#77a1e5', '#c42525', '#a6c96a']}
</colors>
...
</HighchartsChart>
```

**Comment by Crizzooo** [comment]
I'm unable to get any color styling, whether it is a property on HighchartsChart plotOptions={{ colors }}, or directly placed as aprop on HighchartsChart or Chart. Is this supported? Do you have an example?

**Comment by whawker** [comment]
I would personally recommend using the [CSS styled](https://www.highcharts.com/docs/chart-design-and-style/style-by-css) version of Highcharts. Then you use any colours you like.

[Example here](https://whawker.github.io/react-jsx-highcharts/examples/StyleByCSS/index.html)
