### ISSUE TITLE
Possibility to manually update chart

### ISSUE THREAD

**Issue by tukanoidd** [whawker/react-jsx-highcharts#262]
#### Bug or Feature Request?
Feature: Ability to update chart manually

#### Description
Hello, I've been having a problem that for some reason my chart doesn't want to update when I'm trying to update it with signalR even tho the data is changing (rechecked at least 20 times). So I thought that maybe there is an issue with react not updating the chart when it should so I wanted to ask for a feature that lets me use something like chart.update() or make some changes to update configuration as said here https://api.highcharts.com/class-reference/Highcharts.Chart#update. If there is already an option how to do it, I'm sorry for bothering but still I would appreciate some help with this.

#### Versions
* React JSX Highcharts version: 3.6.1
* Highcharts version: 7.2.1
* React version: 16.12.0

**Comment by anajavi** [comment]
If you upgrade to version 4.0.0 you can use the useChart hook to access the chart.

```jsx
const ChartExporter = () => {
  const chart = useChart();
  // do things with chart

  return null;
}

<HighchartsChart>
  <ChartExporter />
</HighchartsChart>
```

**Comment by tukanoidd** [comment]
I will try that, thank you
