### ISSUE TITLE
How to enable drillup option ?

### ISSUE THREAD

**Issue by DhanushkumarSivaji** [whawker/react-jsx-highcharts#263]

**Comment by DhanushkumarSivaji** [comment]
OnDrillDown i am using an api call to update a table . But after clicking the back button that means drillup i need to make another api call to render the previous values .

How to access drillup function . Please help me with that.

**Comment by anajavi** [comment]
Can you please provide more information. The versions used and reproducible example preferably in stackblitz:
```
<!-- For example, create a fork of https://stackblitz.com/edit/base-chart-example -->

#### Versions
* React JSX Highcharts version: 
* Highcharts version: 
* React version: 
```

I am not sure if drilldown actually works, see #29

**Comment by DhanushkumarSivaji** [comment]
Sry for the late rply

 const events = {
          click: (obj)=> this.onDrilldownSeries(obj)
          };

from the above option, i can able to call a function while drilldown. But i need to call a fucntion on 
Drill up (i.e Back button).  How to achieve this.
