### ISSUE TITLE
 react-jsx-highcharts _ Treemap events (DrillDown & DrillUp)

### ISSUE THREAD

**Issue by DhanushkumarSivaji** [whawker/react-jsx-highcharts#268]
const events = {
click: (obj)=> this.onDrilldownSeries(obj)
};

from the above option, I can able to call a function while drill-down. But I need to call a function on
Drill up (i.e Back button). How to achieve this.

https://stackblitz.com/edit/react-8ova6a?file=Treemap.js

in the above URL. I added an alert in every drill down. Likewise, the same I need in drill-up too.

**Comment by anajavi** [comment]
onSetRootNode seems to be firing both on drilldown and drillup of Treemap.

The treemap drilldown does not seem to be related to other drilldowns in Highcharts. 

Example: https://stackblitz.com/edit/react-aws5f5?file=Treemap.js

**Comment by DhanushkumarSivaji** [comment]
> onSetRootNode seems to be firing both on drilldown and drillup of Treemap.
> 
> The treemap drilldown does not seem to be related to other drilldowns in Highcharts.
> 
> Example: https://stackblitz.com/edit/react-aws5f5?file=Treemap.js

**Comment by DhanushkumarSivaji** [comment]
hi Anajavi,

thanks for the quick response. In the treemap, how can I get the value of the particular treemap data? For eg: in the above-mentioned working demo, if I click ' Kerala ' in a treemap. How can I get its name kerala on the onSetNodeFunction?

**Comment by anajavi** [comment]
You can try setting:
```jsx
  onSetRootNode(event) {
    console.log(event);
  }
```

The event object contains property newrootid, which is the id of clicked country or region.
More information can be found in https://api.highcharts.com/highcharts/series.treemap.events.setRootNode
