### ISSUE TITLE
How to get the value of the treemap data on clicking it ? onSetRootNode

### ISSUE THREAD

**Issue by DhanushkumarSivaji** [whawker/react-jsx-highcharts#269]
Hi,
 I can able to call a function on both drill-up and drill-down. But i don't know how to get the value of the particular field when clicking it. For eg: if i click 'Kerala' in treemap the alert show the value of Kerala.

How to achieve this one?

Here is the example for the above mentioned question.

https://stackblitz.com/edit/react-pktqmu?file=Treemap.js

**Comment by anajavi** [comment]
I already answered here https://github.com/whawker/react-jsx-highcharts/issues/268#issuecomment-581153481

You can try setting:
```jsx
  onSetRootNode(event) {
    console.log(event);
  }
```

The event object contains property newrootid, which is the id of clicked country or region.
With the id you should be able to locate correct text to display.

More information can be found in https://api.highcharts.com/highcharts/series.treemap.events.setRootNode
