### ISSUE TITLE
How to enable click event in react-jsx-highmaps ?

### ISSUE THREAD

**Issue by DhanushkumarSivaji** [whawker/react-jsx-highcharts#271]
https://stackblitz.com/edit/react-dcevkw?file=Map.js 

Please have a look at it . and suggest me how to enable click event in it ?

**Comment by anajavi** [comment]
> https://stackblitz.com/edit/react-dcevkw?file=Map.js

Your example link says: "Yikes! The page you requested couldn't be found."

**Comment by anajavi** [comment]
I will close this now, as the example does not exist.

Please fill the issue template form next time too.
