### ISSUE TITLE
Some documentation around withHighcharts

### ISSUE THREAD

**Issue by sghosh14** [whawker/react-jsx-highcharts#275]
Thank you so much for this awesome wrapper!!

#### Feature Request?
Can you please add more withHighcharts examples and documentation and how it is beneficial?

#### Versions
* React JSX Highcharts version: 
* Highcharts version: 
* React version: 
ALL LATEST

**Comment by anajavi** [comment]
Can you please elaborate? What kind of documentation you mean?

**Comment by shrestharthghosh** [comment]
like how to practically use it, where it should be used and some example that would help us identify the advantage of using it.

**Comment by sghosh14** [comment]
dont this is a real issue.
