### ISSUE TITLE
Stacked Bar Chart Series

### ISSUE THREAD

**Issue by Connotating** [whawker/react-jsx-highcharts#278]
#### Question?
Is there a way to use stacked bar/column charts? Do I set it in plot options, or is it a series?

#### Description
```
 <ColumnSeries name="Column" color="pink" data={(Object.values(data.first).map((element)=>{
            return parseInt(element.one)
            }))} />
 <ColumnSeries name="Column" color="pink" data={(Object.values(data.first).map((element)=>{
            return parseInt(element.two)
            }))} />
const plotOptions = {
		series:{},
                stacked:true
		};	
```
#### Versions
* React JSX Highcharts version: 
* Highcharts version: 
* React version:

**Comment by anajavi** [comment]
Here's an quick example of stacked column chart:
https://stackblitz.com/edit/react-fxs2xj?file=MyChart.js
