### ISSUE TITLE
lose prototype of series after drill down

### ISSUE THREAD

**Issue by FalkNisius** [whawker/react-jsx-highcharts#279]
#### Bug or Feature Request?
should be a bug

#### Description
I have a highchart with column chart and drilldown function.
Some times data is changed for the chart, depending on user input.
After drilldown and drillup, changing of data fails with :
`Uncaught TypeError: Cannot read property 'dataSorting' of undefined
    at f.setData (highcharts.src.js:30654)
    at Series.js:106 `

#### How to reproduce
A console.log show that series is normally `f {eventOptions: {…}, chart: d.Chart, userOptions: {…}, tooltipOptions: {…}, stickyTracking: false, …}` before setData is called.
In the error case series is only: `f {remove: null}`
I think the prototype is lost, somewhere in useEffect.
The same code runs fine with highcharts 6.x 7.x and react-jsx-highcharts 3.6.1.

#### Live demo demonstrating bug
```
import React, { PureComponent } from 'react'
import PropTypes from 'prop-types'

import Highcharts from 'highcharts'

import applyExporting from 'highcharts/modules/exporting'
import applyOffline from 'highcharts/modules/offline-exporting'
import applyDrilldown from 'highcharts/modules/drilldown'
import applyDebugger from 'highcharts/modules/debugger'

import {
    Chart,
    ColumnSeries,
    HighchartsChart,
    Title,
    Tooltip,
    withHighcharts,
    XAxis,
    YAxis
} from 'react-jsx-highcharts'

applyExporting(Highcharts)
applyOffline(Highcharts)
applyDrilldown(Highcharts)
applyDebugger(Highcharts)

const plotDrillOptions = {...}

class DrillDownChart extends PureComponent {
drillDown = (e) => {...}
drillUp = (e) => {...}

    render () {
        const series = this.props.seriesBase)
     
        return (
            <HighchartsChart plotOptions={this.props.plotOptions} displayErrors={false}>
                <Chart zoomType="x" type="column" onDrilldown={this.drillDown} onDrillup={this.drillUp}/>

                <Title>{this.props.title}</Title>

                {this.props.legend}

                <Tooltip/>

                <XAxis type="category"/>

                <YAxis min={0}>
                    {series.map(column => <ColumnSeries id={column.id} key={column.id} name={column.name}
                                                        data={column.data} />)}
                </YAxis>
            </HighchartsChart>
        )
    }
}

DrillDownChart.propTypes = {
    title: PropTypes.string.isRequired,
    series: PropTypes.array.isRequired,
    plotOptions: PropTypes.object.isRequired,
    legend: PropTypes.object
}

DrillDownChart.defaultProps = {
    plotOptions: plotDrillOptions,
}

export default withHighcharts(DrillDownChart, Highcharts)

```
#### Versions
* React JSX Highcharts version: react-jsx-highcharts 4.0.1 
* Highcharts version: highcharts 8.0.4
* React version: react 16.13.1

**Comment by anajavi** [comment]
I'm pretty sure this a change in Highcharts.

To confirm it: can you please try your example with react-jsx-highcharts 4.0.1 and highcharts 7? It complains about peer dependency, but should mostly work.

**Comment by FalkNisius** [comment]
same on react-jsx-highcharts 4.0.1 and highcharts 7.2.1

**Comment by FalkNisius** [comment]
The value of `seriesRef.current` is changed from an Object hold the pointers to chart, userOptions to an Object hold only a remove function. I assume it is a react problem. You changed the implementation from a class component (not a PureComponent) in 3.6.1 to a functional an memoized Component in 4.0.1. I don't know why the reference is changed, perhaps as a workaround it can be to take the reference, first time occurs valid, put them to the context, and use the context if the reference becomes wrong.

**Comment by anajavi** [comment]
> I investigate a little bit more to Your source code, and detect, that the useEffect hook for changing axis can replace seriesRef.current. In my case the XAxis have the type "categories" and the YAxis change the ColumnSeries complete, not only some values, that are stacked columns.

Can you please make a reproducible example with https://stackblitz.com/edit/base-chart-example ? It would really help to understand the problem.
