### ISSUE TITLE
Setting 'visible' prop on series not working

### ISSUE THREAD

**Issue by busla** [whawker/react-jsx-highcharts#28]
Thanks for contributing this. Great stuff. Finally we can have initial animation when charts are renderd 👍 

On another note, the visible prop doesn´t seem to work:
http://api.highcharts.com/highcharts/series%3Ccolumn%3E.visible

I´m trying to hide all categories except the first two.

Example from working code:

```javascript
  prepareSeries(surveys) {
    const series = surveys.map((s, i) => {
      const parties = s.results.list.sort((a,b) => a.ratio - b.ratio).reverse()
        .map(p => {
          return {name: p.text, y: p.ratio}
      })
      return({
        visible: (i > 1) ? false:true,
        name: s.election.text,
        data: parties
      })
    })
    return series
  }

**Comment by busla** [comment]
Oops, found it:

https://github.com/whawker/react-jsx-highcharts/blob/master/packages/react-jsx-highcharts/src/components/Series/Series.js

**Comment by whawker** [comment]
It appears to be working for me, could you post a fuller example?

Demo: https://codesandbox.io/s/zrk0v6zrpl

**Comment by busla** [comment]
Should have been more descriptive, it works fine, just missing the visible props.

**Comment by busla** [comment]
Found it in the code and used visible as props
