### ISSUE TITLE
How to obtain the same responsive of official package

### ISSUE THREAD

**Issue by lezan** [whawker/react-jsx-highcharts#282]
#### Bug or Feature Request?
I do not know if it is a bug or intended behaviour, but I am not able to figure out how to obtain the same result.

#### Description
I am switching from react-official to react-jsx because with the last I can have more performance on update, but I am some issue obtain the same responsability.
With the official package I wrap chart into a container with responsability, and then I set  HighchartsReact container with height and width of 100%, something like that.
```
const style = {
    height,
    width: '100%',
};

<Row>
    <Col>
        <div id={nameChart} className="chart" style={style}>
            { chartElement !== null ? chartElement : null }
        </div>
    </Col>
</Row>
```
and then
```
<HighchartsReact
    highcharts={Highcharts}
    constructorType="chart"
    containerProps={{ style: { height: '100%', width: '100%' } }} // <- This one.
    options={chartOptions}
/>
```
With react-jsx I try to the same, I just switch the last part
```
<HighchartsChart
     containerProps={{ style: { height: '100%', width: '100%' } }}
    plotOptions={plotOptions}
>
    <Chart
        type={typeChart}
    />
    ...
```
Doing like that I am not able to obtain responsability on height, because chart does not change his dimension.
I also try to do 
```
<HighchartsChart
     style={{ height: '100%', width: '100%' }}
    plotOptions={plotOptions}
>
    ...
```
but same result.
#### How to reproduce
Just try to resize window on the two examples.

#### Live demo demonstrating bug
With react-jsx: https://stackblitz.com/edit/base-chart-example-dycbqd.
With highcharts-react: https://stackblitz.com/edit/react-q2junp.

#### Versions
* React JSX Highcharts version: 4.0.1
* Highcharts version: 8.0.4
* React version: 16.13.1

Thanks!

**Comment by whawker** [comment]
Hi @lezan, glad to hear you're interested in switching!

I would personally recommend using Highcharts "[styled by CSS](https://whawker.github.io/react-jsx-highcharts/examples/StyleByCSS/index.html)" (see the `styledMode` prop) rather than the config way above

Then it would be a case of adding a CSS rule for the `.highcharts-container` div, to obtain the behaviour you desire.

If this isn't an option for legacy reasons, I might look into adding `containerProps` support for easier migration from the official package,

**Comment by lezan** [comment]
Hi @whawker, thanks for you answer.
Using styledMode made the trick.

Actualy my concern is about uniforming all styles and I am trying to migrate them setted by setOptions to css, due due styledMode.

I will try to look into how I can add containerProps to react-jsx, and if I get it, I will try to PR it.

**Comment by whawker** [comment]
Pretty much, although it would be good to deconstruct `containerProps` first. So it would just be

```jsx
<div {...containerProps} className={`chart ${className}`} ref={domNodeRef}>
```

**Comment by potofpie** [comment]
@whawker  I am having a little trouble understanding this thread. How would you achieve something like this example with your package? I just want the graph to fill the height of a `MuiCard`. 

Example: http://jsfiddle.net/joq86mgs

Great job btw, it is much more intuitive than official package.
