### ISSUE TITLE
How to set useUTC to false

### ISSUE THREAD

**Issue by muhaimincs** [whawker/react-jsx-highcharts#285]
#### Bug or Feature Request?
Missing documentation

#### Description
How do I call chart time to set the `useUTC` to false

**Comment by whawker** [comment]
Hi @muhaimincs, admittedly it's a little hidden in the [documentation](https://github.com/whawker/react-jsx-highcharts/wiki/Supported-Features) but it does state
> For the features not currently "supported" by React JSX Highcharts, you can still pass them as props to the main `<HighchartsChart />` or `<HighchartsStockChart />`.

For your specific use case you can pass a `time` object to your component - see line 20 and 23 [here](https://stackblitz.com/edit/base-stockchart-example-pqceb6?file=MyChart.js)
