### ISSUE TITLE
How do I prepare rangeInput

### ISSUE THREAD

**Issue by muhaimincs** [whawker/react-jsx-highcharts#286]
#### Bug or Feature Request?
Bug

#### Description
Unable to find rangeInput docs

**Comment by whawker** [comment]
There is an example here? https://whawker.github.io/react-jsx-highcharts/examples/Highstocks/index.html

**Comment by muhaimincs** [comment]
I mean combine the rangeInput and custom datepicker in the same chart

**Comment by whawker** [comment]
I'm not sure you can, that's why the custom component example exists showing you how to replace functionality with custom React components and the hooks we expose.

**Comment by muhaimincs** [comment]
So we may need to do custom component for zoom part too

**Comment by whawker** [comment]
Zoom is controlled by the `<Chart>` in line with the [Highcharts docs](https://api.highcharts.com/highcharts/chart.zoomType)

I.e. see our [Highstocks example](https://api.highcharts.com/highcharts/chart.zoomType) we have

```jsx
<Chart zoomType='x' />
```

**Comment by muhaimincs** [comment]
Sorry to trouble you. I didn't mean that kind of zoom. What I meant is zoom from the `rangeInput`. By the way, do you have any idea why chart is blank at initial data load. It only appear if I click on zoom button
