### ISSUE TITLE
Pie chart does not re-render on sorted data

### ISSUE THREAD

**Issue by louis269279** [whawker/react-jsx-highcharts#293]
#### Bug or Feature Request?
Possible bug

#### Description
This might be by design, but when we wish to sort a pie chart that is already rendered, the data we pass to PieSeries changes, but the pie chart that is rendered does not change.

#### How to reproduce
See demo link. When you click the button to change the data, pie doesn't change. In the code, you can enable a workaround to set "updatePoints" to false, which forcefully changes the pie chart, and hence fixes the problem.

#### Live demo demonstrating bug
https://stackblitz.com/edit/stockchart-updatepoints-false-pwvint

#### Versions
* React JSX Highcharts version:  Latest
* Highcharts version: Latest
* React version: Latest

**Comment by anajavi** [comment]
The Highcharts seems to update data based on id of a data point.

If you remove id property from initData your chart will reorder.
```javascript
const initData = [
  { name: "TChekToken", y: 1000},
  {name: "Visabase12EC", y: 206},
  { name: "NBS", y: 2000},
  { name: "Comdata", y: 195}
]
```

See if https://www.highcharts.com/docs/advanced-chart-features/data-sorting helps you with sorting the data.
