### ISSUE TITLE
Loading component

### ISSUE THREAD

**Issue by will-stone** [whawker/react-jsx-highcharts#30]
I'd submit a pull request but thought it best to discuss with you first (and improve on my code 😄 ). How about a Loading component? Something like this:

```
import React from 'react'
import { provideChart } from 'react-jsx-highcharts'

class Loading extends React.Component {
  showLoading() {
    const chart = this.props.getChart()
    chart.showLoading('Loading...')
  }

  hideLoading() {
    const chart = this.props.getChart()
    chart.hideLoading()
  }

  render() {
    this.props.isLoading ? this.showLoading() : this.hideLoading()
    return false
  }
}

export default provideChart(Loading)
```

And then used like so:
```
<HighchartsChart>
  ...  
  <Loading isLoading={this.props.isLoading} />
  ...
</HighchartsChart>
```

**Comment by whawker** [comment]
Good idea, although most components in this library work on `componentDidMount`/`componentWillUnmount` hooks to trigger show/hide behaviour on Highcharts, rather than working off a prop; 

```jsx
import React, { Component } from 'react';

class Loading extends Component {
  componentDidMount () {
    const chart = this.props.getChart();
    chart.showLoading('Loading...');
  }

  componentWillUnmount () {
    const chart = this.props.getChart();
    chart.hideLoading();
  }

  render() {
    return null;
  }
}

export default Loading
```
It's also preferable the the `provideChart` HOC is applied in the `index.js` as it makes the component easier to test.
```js
import Loading from './Loading ';
import provideChart from '../ChartProvider';
export default provideChart(Loading );
```

-----------------
I would love it if we could we could pass some child components to `Loading` so we can render our own Loading icon. 

Perhaps we can use React 16's new `createPortal`  behaviour to render content into the [`.highcharts-loading`](https://github.com/highcharts/highcharts/blob/d854eb4132c83d1c73e069ea9b30300ad30d329f/js/parts/Dynamics.js#L174) div?

Possible something like...
```jsx
render () {
    const { children, getChartContainer } = this.props; // getChartContainer doesn't exist ATM
    return ReactDOM.createPortal(children, getChartContainer.querySelector('.highcharts-loading'));
}
```

**Comment by will-stone** [comment]
Sounds good. However, if the data is being polled and passed in, how would you notify the Loading component that data is being fetched without a prop?

**Comment by whawker** [comment]
Something like
```jsx
constructor (props) {
  super(props};
  this.state = { isLoading: true };
}

componentWillMount () {
  fetch('web.url').then(res => {
    this.setState({ isLoading: false });
  });
}

render () {
  const { isLoading } = this.state;
  return (
    <HighchartsChart>
      {isLoading && <Loading />}
      // etc
    </HighchartsChart>
  );
}
```

Although, now I see it written out like that, it's possible overly complicated... hmm what're your thoughts?

**Comment by will-stone** [comment]
No, that makes sense. Really, the only change is
```
<Loading isLoading={isLoading}/>
```
to
```
{isLoading && <Loading />}
```

I'm happy with that solution 😄

**Comment by whawker** [comment]
Hi @will-stone I've just published the new `<Loading />` component in 2.0.3, here is [an example](https://whawker.github.io/react-jsx-highcharts/examples/Loading/index.html) of it's usage.

**Comment by will-stone** [comment]
That's great, thanks!

**Comment by brucevanhorn2** [comment]
Does this also work on HighchartsStockChart?

**Comment by whawker** [comment]
@brucevanhorn2 yep, anything that is available for HighchartsChart should work for HighchartsStockChart too

**Comment by sghosh14** [comment]
is see that you cant really pass anything other than string, is there way we can pass react component
