### ISSUE TITLE
RangeSelector does not render if before XAxis

### ISSUE THREAD

**Issue by hukka** [whawker/react-jsx-highcharts#305]
#### Bug or Feature Request?
I'm guessing bug, or missing warning/documentation.

#### Description
RangeSelector does not render (into the DOM, at least), if it comes before XAxis in the component hierarchy. All the Highstock examples in the actual example dir has it later, and they work, but the example in the README has them in opposite order and does not work.

#### How to reproduce
Make any graph where RangeSelector is given first in the JSX.

#### Live demo demonstrating bug
https://stackblitz.com/edit/base-chart-example-broken-rangeselector?file=MyChart.js compared to https://stackblitz.com/edit/base-chart-example-working-rangeselector?file=MyChart.js

#### Versions

    "highcharts": "8.1.0",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-jsx-highcharts": "4.1.0",
    "react-jsx-highstock": "^4.1.2"

**Comment by anajavi** [comment]
The rangeselector seems to always use the first xAxis in a chart. So it won't work before one is created.

This should be fixed in readme.
