### ISSUE TITLE
RangeSelector input inoperable before range is modified in other ways

### ISSUE THREAD

**Issue by hukka** [whawker/react-jsx-highcharts#306]
#### Bug or Feature Request?
Bug

#### Description
https://whawker.github.io/react-jsx-highcharts/examples/Highstocks/index.html shows the RangeSelector inputs as empty boxes which cannot be edited before the range is modified at least once using the buttons or the navigator.

#### Live demo demonstrating bug
https://whawker.github.io/react-jsx-highcharts/examples/Highstocks/index.html

**Comment by anajavi** [comment]
Related bug in highcharts: https://github.com/highcharts/highcharts/issues/11669

**Comment by anajavi** [comment]
This seems to be fixed in highcharts v9.0.1.

Note: the examples are still using v8.

@whawker can you please regenerate the examples or point them directly to the https://github.com/whawker/react-jsx-highcharts-examples repository?
