### ISSUE TITLE
Incorrect rendering for charts with two YAxis (Highcharts 8.1.1+)

### ISSUE THREAD

**Issue by natalan** [whawker/react-jsx-highcharts#312]
#### Bug or Feature Request?
Bug

#### Description
Rendering a chart with multiple yAxis will result in only one axis rendered. Resizing the window (triggering reflow) fixes the problem. Rendering the same object without react-jsx-highcharts but using regular Highcharts doesn't show the same problem.

#### How to reproduce
See a live demo. Two <YAxis/> each with its own Series component.

#### Live demo demonstrating bug
Both line and column series rendered with Highcharts 8.1.0: https://stackblitz.com/edit/multiple-yaxis-works?file=MyChart.js
Only the line series is rendered Highcharts 8.1.1+ (note, the example is with the latest version) https://stackblitz.com/edit/multiple-yaxis-broken?file=MyChart.js

#### Versions
* React JSX Highcharts version: 4.1.0
* Highcharts version: everything above 8.1.1 is broken
* React version: 16.13.1

**Comment by anajavi** [comment]
This is a known bug in Highcharts > 8.1.0: https://github.com/highcharts/highcharts/issues/13995

The only workaround is to remove height and size from ```<Chart />```

**Comment by anajavi** [comment]
Also the stackblitz example needs to be updated to react-jsx-highchart@^4.1.1, otherwise the setSize is anyway called.

**Comment by natalan** [comment]
@anajavi thanks for triaging and suggesting to drop `height` here! this works as a workaround while waiting for  highcharts/highcharts#13995 regression fix

**Comment by natalan** [comment]
This issue is fixed in Highcharts 8.2.2

**Comment by anajavi** [comment]
The fix has not been released yet. It is only fixed on highcharts github master.

Let's keep this open for visibility.

**Comment by anajavi** [comment]
Fix for this is released in highcharts@9.0.0.

#325 is related.
