### ISSUE TITLE
Trigger redraw of entire chart if chart options change

### ISSUE THREAD

**Issue by stellafang** [whawker/react-jsx-highcharts#313]
#### Bug or Feature Request?
Ability to trigger redraw of the chart with new chart options (i.e. a different timezone set)

#### Description
Might be related to [issue 311](https://github.com/whawker/react-jsx-highcharts/issues/311 )

Updating the `timezoneOffset` in the `time` prop does not update the chart. Changing such set up parameters for a chart should trigger a redraw the entire chart,
`<HighchartsStockChart time={{useUTC: true, timezoneOffset:timezoneOffset }}>`

Question.. is there a way to manually trigger redrawing of the entire chart when a prop changes from maybe the useEffect hook?

#### How to reproduce
1. Create a react component with HighchartsStockChart that passes a changing time prop
2. Trigger update to time prop
3. Observe that the chart does not change because the chart is not redrawn with these new options.
(I'm "working around" this by storing the timezone in localStorage and triggering an entire page reload to see a newly configured chart)

#### Versions
* React JSX Highcharts version: 4.1.2
* Highcharts version: 8.1.0
* React version: 16

**Comment by anajavi** [comment]
I guess a separate ```<ChartTime />``` component would be needed for this currently.

For example:
```jsx
const ChartTime = ({ useUTC, timezoneOffset }) => {
  const chart = useChart();
  useEffect(() => {
    chart.update({time: { useUTC, timezoneOffset }});
  }, [useUTC, timezoneOffset]);
}
```

Maybe it should be included in the library though.

**Comment by stellafang** [comment]
@anajavi Yes that would be helpful. Is there a way I can do this with the current library as is right now for a temporary workaround?

**Comment by anajavi** [comment]
> @anajavi Yes that would be helpful. Is there a way I can do this with the current library as is right now for a temporary workaround?

The above component might work as is, I haven't tested it. Just put it inside ```<HighchartsStockChart>```.

**Comment by stellafang** [comment]
@anajavi So this worked! But the way the chart redraws is by shifting the x-axis rather than shifting the points in the chart and keeping the xaxis the same. Is there a way to keep the x-axis (time interval) the same and instead shift the chart points accordingly instead?

**Comment by anajavi** [comment]
@stellafang can you please make a reproducible example with https://stackblitz.com/edit/base-chart-example

**Comment by stellafang** [comment]
@anajavi nevermind that, I was just forgetting to change the dates with the timezone. These hooks are super helpful! I think itd be great to get some documentation about it up. thanks for your help!!
