### ISSUE TITLE
Possible to change color of point in lineseries?

### ISSUE THREAD

**Issue by micke232** [whawker/react-jsx-highcharts#317]
I would like to have it possible to change each point in a lineseries individually based on some parameters. I could not find any support for this?

**Comment by anajavi** [comment]
I haven't tried, but it should work something like this:
```jsx
const coloredData = [{ y: 216.4, color: '#AAF'}, {y: 100, color: '#FAA' }];
return (
  <LineSeries data={coloredData} />
)
```

**Comment by anajavi** [comment]
Depending on use case you could also use coloraxis: https://api.highcharts.com/highcharts/colorAxis

Wrap the series in ```<ColorAxis>```
