### ISSUE TITLE
Navigator unmount error

### ISSUE THREAD

**Issue by ben-lucidfusion** [whawker/react-jsx-highcharts#32]
When using **Navigator** in a HighchartsStockChart, as soon as my main component unmounts (like navigating to another page using react router) I get spammed with this error when the mouse moves:

**highstock.js:436 Uncaught TypeError: Cannot read property 'normalize' of undefined
    at HTMLDocument.a.mouseMoveHandler**

If I remove the Navigator component, everything seems to be fine.

**Comment by whawker** [comment]
Hmm, seems that Highcharts destroys the chart navigator with [`this.scroller.destroy()`](https://github.com/highcharts/highcharts/blob/master/js/parts/Chart.js#L1864)

The Navigator is mounted on [both `this.scroller` and `this.navigator`](https://github.com/highcharts/highcharts/blob/master/js/parts/Navigator.js#L2042) so now React JSX Highcharts does the same.

**Comment by jhartling** [comment]
It's still possible to run in to this issue if you include a Scrollbar before a Navigator.

Example: https://stackblitz.com/edit/base-chart-example-p1ekth?file=MyChart.js

It doesn't occur when the Scrollbar is included after the Navigator.
