### ISSUE TITLE
How to read coordinate when the line is clicked at any point in line chart?

### ISSUE THREAD

**Issue by geomy** [whawker/react-jsx-highcharts#326]
#### Bug or Feature Request?
How to read coordinate at any point in line chart?
#### Description
I want to read coordinates (x and y values) in Line chart(LineSeries component). Is this feature exists or is there any workaround to achieve this in our package

#### Versions
* React JSX Highcharts version: 
* Highcharts version: 
* React version:

**Comment by anajavi** [comment]
Do you mean something like in this highcharts demo?
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/plotoptions/series-point-events-mouseover/

**Comment by geomy** [comment]
Exactly Anajavi, I am drawing line by component based implementation.
see this below

  <HighchartsProvider Highcharts={Highcharts}>
                <HighchartsChart>
                    <Chart />
                    <Title>TRANSACTIONS</Title>
                    <Legend layout="vertical" align="right" verticalAlign="middle" />
                    <Tooltip split={true} padding={10} hideDelay={300} />
                    <XAxis categories={[1,2,3,4,5,6]}>
                        <XAxis.Title>Data</XAxis.Title>
                    </XAxis>
                    <YAxis>
                        <YAxis.Title>Amount</YAxis.Title>
                        <LineSeries name="Transactions" data={[12,34,56,8,989,10]}  />
                    </YAxis>
                </HighchartsChart>
            </HighchartsProvider>

Then how can I achieve configuration from demo link you shared above. 

Thanks for quick response.

**Comment by anajavi** [comment]
Here's a quick example:
https://stackblitz.com/edit/base-chart-example-yq8lkg?file=MyChart.js

**Comment by geomy** [comment]
Thank you so much Anajavi
