### ISSUE TITLE
How/Why is this so much better that the official lib?

### ISSUE THREAD

**Issue by potofpie** [whawker/react-jsx-highcharts#327]
#### Bug or Feature Request?
Hello! This is not a bug or feature request, just a question for my education. 

#### Description
After using your package I saw significant performance improvement and am seeking to understand the general how/why in hopes that it will help me optimize my project even further.  

#### How to reproduce
The main issue we had was when clicking between tabs with a large quality of graphs the page would freeze loading indicators included. This made for a unacceptable user experience sending back to the drawing board. 

#### Live demo demonstrating bug
highcharts-react-official example: https://stackblitz.com/edit/base-chart-example-b9x6ac
react-jsx-highcharts example: https://stackblitz.com/edit/base-chart-example-b9x6ac

#### Versions
* React JSX Highcharts version: N/A
* Highcharts version: N/A
* React version:  N/A

Also thanks for making this!

**Comment by anajavi** [comment]
> highcharts-react-official example: https://stackblitz.com/edit/base-chart-example-b9x6ac
> react-jsx-highcharts example: https://stackblitz.com/edit/base-chart-example-b9x6ac

I think you accidentally posted the same example twice.
