### ISSUE TITLE
Highmaps?

### ISSUE THREAD

**Issue by mandajoan** [whawker/react-jsx-highcharts#34]
I am trying to use React with Highmaps. Currently using the react-highcharts package but am running into issues when trying to call the build in methods (example. .hide() ) in a method outside the config object. 

I want utilize the state constructor in React to update the config object and think your documentation would be the approach I would like to take. 

**The question is then, does react-jsx-highcharts work with highmaps?**

Thank you!

**Comment by whawker** [comment]
Unfortunately there is no support for Highmaps at the moment. I haven't really used Highmaps so I'm not as familiar with it's internal workings.

I can have a look though! Or PRs are more than welcome!

**Comment by mandajoan** [comment]
I would appreciate if you had a chance to take a look at what I have going on... I am going to set up a repo for my project. Can I have you take look once that's up? I am having an issue getting the highcharts methods to work. Right now I am using react-highcharts as a wrapper, so I am not sure if there is a conflict with the package and highmaps or if some how highmaps/highcharts just doesn't like that I am using React. 
 @whawker

**Comment by mandajoan** [comment]
Depending on how I figure this out, I will see about a PR!

**Comment by whawker** [comment]
@mandajoan if you're still looking for Highmaps support, I've just published a beta version. https://www.npmjs.com/package/react-jsx-highmaps

Example: https://stackblitz.com/edit/base-map-example-svixuf?file=MyMap.js
