### ISSUE TITLE
Add ColorAxis component causes error in highcharts.js

### ISSUE THREAD

**Issue by narsters** [whawker/react-jsx-highcharts#346]
#### Bug or Feature Request?
Bug

#### Description
Adding ColorAxis component causes error in highcharts.js  This in turn causes the chart not to render.

#### How to reproduce
Add a <ColorAxis /> component to a chart.  I tried with various props like min={0} max={10} and stops={[[0, '#00ff00'], [0.5, '#ffff00'], [1, '#ff0000']]}.  I get the same error every time "this[a] is undefined"

#### Live demo demonstrating bug
https://stackblitz.com/edit/react-mlvwri?file=src%2Fchart.js

#### Versions
* React JSX Highcharts version: 4.3.1
* Highcharts version: 9.2.2
* React version: 17.0.2

**Comment by anajavi** [comment]
You need to add coloraxis module first:
```js
import addColorAxis from 'highcharts/modules/coloraxis';

addColorAxis(Highcharts);
```

**Comment by narsters** [comment]
Perfect, that worked!
