### ISSUE TITLE
I would like to know the x-axis plot band widths dynamically with events redraw and load

### ISSUE THREAD

**Issue by gudapraveenkumar** [whawker/react-jsx-highcharts#352]
Highcharts events like redraw and load are not working

I want to know the width of plotbands on x-axis and when I looked into the documentation of Highcharts I found that we can add the events object with redraw and load methods while creating an instance of Highcharts. I tried adding this events to the Highstocks react components as props but did not worked.

### In Highcharts:
<img width="502" alt="Screenshot 2021-09-29 at 09 05 40" src="https://user-images.githubusercontent.com/33131034/135219580-102be397-3ad9-42cc-accb-28b6a2abd253.png">

### In react-jsx-highcarts

  const chartOptions = useMemo(() => {
       return {
          // animation: false,
         width: recentChartWidth,
         height: 180,
         events: {
            redraw: plotBandWidthHandler,
            load: plotBandWidthHandler
         }

     }
  }, [recentChartWidth])

`<HighchartsStockChart plotOptions={plotOptions}>`

    <Chart {...chartOptions} />

    <GenericOptions {...genericOptions} />

     <XAxis {...xAxis}>
       {(dayBands || []).map((plotBand) => (
         <PlotBand key={`{plotBand.label?.text}`} {...plotBand} />
       ))}
     </XAxis>

     <YAxis {...yAxis}>
       {(seriesData || []).map((series, index) => (
          <Series key={index} id={index} {...series} />
        ))}
      </YAxis>

`</HighchartsStockChart>`

Unfortunately with the above code I the **plotBandWidthHandler** is not called. Correct me if I'm passing the events props to a wrong react component.

**Comment by anajavi** [comment]
redraw event handler should work like this:
```jsx
<Chart onRedraw={plotBandWidthHandler} />
```

**Comment by gudapraveenkumar** [comment]
@anajavi thanks it worked but the thing is I'm getting the old chart object instead of current chart object as parameter on every redraw

**Comment by anajavi** [comment]
> but the thing is I'm getting the old chart object instead of current chart object as parameter on every redraw

Does the handler get current chart object with vanilla highstock?

Also can you make an example with a fork of https://stackblitz.com/edit/base-chart-example

**Comment by gudapraveenkumar** [comment]
This is the handler called on reDraw, in the console log if you see I was trying to get the width of the plot band.

` const handleOnRedraw = useCallback((data) => {

    if (data?.target && data?.target?.xAxis && data?.target?.xAxis.length > 0) {

      if (data?.target?.xAxis[0]?.plotLinesAndBands?.length > 0) {

      // Here I'm getting the previous plotband widths

         console.log('plot band width  =', data?.target?.xAxis[0]?.plotLinesAndBands[0].svgElem.getBBox().width)

      }

    }

  }, [])`  

This is what I get this in **data** param

![Screenshot 2021-09-30 at 19 18 23](https://user-images.githubusercontent.com/33131034/135501356-e5b9530c-10d1-4209-93c6-43dd00912649.png)

**Comment by anajavi** [comment]
If you are still experiencing the problem, please open a new issue with a reproduction.
