### ISSUE TITLE
Highcharts 6 question

### ISSUE THREAD

**Issue by caguthrie** [whawker/react-jsx-highcharts#36]
I see there is a dependency on highcharts@^5.0.0, has this been tested with highcharts 6?

**Comment by whawker** [comment]
Yes, but there were a few issues which I haven't debugged yet. Which feature of Highcharts 6 were you looking to use?

**Comment by caguthrie** [comment]
Nothing specific.  Just was curious on the general functionality with
Highcharts 6.  Ran into this from the Highcharts blog (great article) and
really appreciate the work you've put into this, this is really awesome
stuff and a obviously a huge boon for any highcharts/react user.  Thanks

**Comment by whawker** [comment]
Cool, glad you like it! 

Well now I've released version 2, Highcharts 6 is my next thing to look at, although there are a lot of new features so could take a while, I'll keep you updated.

**Comment by shadowfool** [comment]
I'm interested in this as well. Not sure if it's just me being unfamiliar with the highcharts change log from 5->6 but it seems like the boost module was introduced in 5 but not implemented fully until 6. Having the ability to use the boost module in this module would be a huge upgrade.

**Comment by ricopella** [comment]
First off, love this project and this is exactly the approach my company would like to take while building with highcharts. However, something we're planning on using often is the Sankey Diagram, which was introduced in Highcharts 6. That wouldn't happen to be one of the first version 6 feature's you're planning on tackling, would it?

**Comment by whawker** [comment]
Hi @ricopella, yes ideally that would be. There just seems to be a bug with Highstocks v6 and this library, which I really change figure out. As soon as I get to the bottom of it though, Sankey charts will be a priority!

**Comment by whawker** [comment]
Hi @caguthrie, @shadowfool and @ricopella - I've just published `react-jsx-highcharts` and `react-jsx-highstock` version 2.1.0 which adds support for Highcharts 6!

See the [Sankey](https://whawker.github.io/react-jsx-highcharts/examples/Sankey/index.html) and [Stream Graph](https://whawker.github.io/react-jsx-highcharts/examples/StreamGraph/index.html) examples!

**Comment by shadowfool** [comment]
Great, I'll try it out with boost later.

**Comment by danloiterton** [comment]
@shadowfool, any luck with the boost module? How do you import modules with this library anyway? I've tried simply adding `import 'highcharts/modules/boost';` but it doesn't seem to work

By the way @whawker, thanks for this module - it's really great!

**Comment by shadowfool** [comment]
@danloiterton I haven't tried it myself yet but it looks like the way you'd do this is by wrapping Highcharts with boost. 
@whawker whawker does something similar in this ticket https://github.com/whawker/react-jsx-highcharts/issues/62

His example:
```jsx
import Highcharts from 'highcharts/highstock';
import HighchartsMore from 'highcharts/highcharts-more';

HighchartsMore(Highcharts);
```

Perhaps we need updated documentation on these features?

**Comment by whawker** [comment]
@shadowfool is correct with his implementation, and that this is more a Highcharts feature than React JSX Highcharts, but I can make a reference to it in the documentation.

Ideally I'd migrate the examples to CodeSandbox/StackBlitz which would make this kind of thing way more obvious, rather than using browser based globals like I do currently.

**Comment by sorenhoyer** [comment]
Works, but how can we supply the configuration options for the boost module? https://www.highcharts.com/docs/advanced-chart-features/boost-module - boost.useGPUTranslations & boost.seriesThreshold is pretty important

**Comment by whawker** [comment]
I would imagine... (using a functional React component)

```jsx
import React from 'react';
import { HighchartsChart, withHighcharts } from 'react-jsx-highcharts';
import Highcharts from 'highcharts';
import Boost from 'highcharts/modules/boost.js';

Boost(Highcharts);

const boostOptions = {
  useGPUTranslations: true,
  seriesThreshold: 20
};

const MyComponent = () => (
  <HighchartsChart boost={boostOptions}>
   // Chart components here
  </HighchartsChart>
);
export default withHighcharts(MyComponent, Highcharts);
```

[This page](https://github.com/whawker/react-jsx-highcharts/wiki/Supported-Features) about support features in the wiki may help.

**Comment by sorenhoyer** [comment]
Cool, works just fine :)
