### ISSUE TITLE
Cannot read properties of undefined (reading 'forExport') in Next

### ISSUE THREAD

**Issue by Tarasikee** [whawker/react-jsx-highcharts#364]
#### Bug or Feature Request?

Bug

#### Description

I am using react-jsx-highcharts with NextTS and having issues with a rendering component. On the screenshot below, you will see an error I am getting.

#### How to reproduce
Probably try to use react-jsx-highcharts with NextJs

#### Live demo demonstrating bug
![image](https://user-images.githubusercontent.com/51419482/169514376-72dc9a8d-27c4-430e-ae7d-dc9c3d14bd5d.png)
Error I am receiving.

![image](https://user-images.githubusercontent.com/51419482/169515154-bcab6301-470d-44c6-b0ce-12d7762ab43b.png)
Code of my component

#### Versions
* React JSX Highcharts version: ^4.3.2
* Highcharts version: ^10.1.0
* React version: 18.0.0
* Next version: 12.1.5
* Typescript version: 4.6.3

**Comment by anajavi** [comment]
The react-jsx-highcharts v4 has known problems with React 18.

Can you check if installing react-jsx-highcharts@^5.0.0-alpha.0 resolves your problem?

**Comment by Tarasikee** [comment]
@anajavi, thanks a lot, that solved my issue. The only thing I worry about is whether using the alpha version in production is a good idea.

**Comment by anajavi** [comment]
v5 final is now released.
