### ISSUE TITLE
Setting draggableY to plotOptions not working correctly 

### ISSUE THREAD

**Issue by KevinDoherty94** [whawker/react-jsx-highcharts#365]
#### Bug or Feature Request?
I believe this is a bug or possibly user error

#### Description
Currently I am trying to make the data points draggable like in this example https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/dragdrop/resize-column
but it’s not working. I have the plotOptions as a variable and assigning it to plotOptions as explained in the docs on this repository. I am however using <HighchartsStockChart> and my plot options are set the same way as the example above. Any help greatly appreciated.

#### How to reproduce
By creating a line graph chart and setting plotOptions to this example https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/dragdrop/resize-column 

#### Versions
* React JSX Highcharts version: 
* Highcharts version: 
* React version:

**Comment by anajavi** [comment]
I guess you have to apply draggable-points module like this:
```jsx
import draggablePoints from 'highcharts/modules/draggable-points';

draggablePoints(Highcharts);
```

Example:
https://stackblitz.com/edit/base-chart-example-cqs5hp?file=MyChart.js

**Comment by KevinDoherty94** [comment]
Thanks anajavi works perfectly now. Definitely user error on my part
