### ISSUE TITLE
Change the range of the chart from the code

### ISSUE THREAD

**Issue by cheatsnake** [whawker/react-jsx-highcharts#370]
#### Question?
How do I change the range of the chart from the code?

#### Description
To change the range of the chart in the application, I use Range Selector, where I can specify buttons with the desired range. 
```js
<RangeSelector selected={1} buttonSpacing={10}>
    <RangeSelector.Button count={1} type="hour">1h</RangeSelector.Button>
    <RangeSelector.Button count={3} type="hour">3h</RangeSelector.Button>
    <RangeSelector.Button type="all">All</RangeSelector.Button>
</RangeSelector>
```
But how change range without whithout clicking on this buttons? For example, I dynamically receive data from the server and I need to call the range change event from javascript code. But how?

**Comment by anajavi** [comment]
Is it possible to change range with plain highcharts? I could not find any examples of it.
