### ISSUE TITLE
`ordinal` does not work for X axis.

### ISSUE THREAD

**Issue by uvarov-frontend** [whawker/react-jsx-highcharts#372]
#### Bug or Feature Request?
`ordinal` does not work for X axis.

#### Description
I was desperate to find a solution to the problem, for some reason, `ordinal` does not work for me.
But it works on pure Highcharts: https://jsfiddle.net/uvarov_frontend/ebwhc324/6/

#### How to reproduce
Open demo

#### Live demo demonstrating bug
https://stackblitz.com/edit/base-chart-example-znspu9?file=MyChart.js

#### Versions
* React JSX Highcharts version:  5.0.0
* Highcharts version: 10.2.1
* React version: 18.2.0

**Comment by anajavi** [comment]
```ordinal``` is part of highstock.

So if you import highstock instead of highcharts it will work:
```jsx
import Highcharts from 'highcharts/highstock';
```

**Comment by uvarov-frontend** [comment]
Святая корова! Это действительно работает! Спасибо!
