### ISSUE TITLE
Tooltip formatter scope

### ISSUE THREAD

**Issue by juwilliams** [whawker/react-jsx-highcharts#41]
Hey again,

Is there a recommended way to use the tooltip for correct access to the chart scope? The scope of this is redefined to the parent in my experiments and therefore I'm not able to make use of custom tooltip formatting.

![screen shot 2017-11-13 at 2 29 59 pm](https://user-images.githubusercontent.com/10916150/32744920-2b2bf032-c87f-11e7-9062-fec1d026db03.png)

![screen shot 2017-11-13 at 2 25 58 pm](https://user-images.githubusercontent.com/10916150/32744769-a9773b0a-c87e-11e7-91c9-a20d84b1647d.png)

![screen shot 2017-11-13 at 2 29 43 pm](https://user-images.githubusercontent.com/10916150/32744923-2fdb530c-c87f-11e7-9a61-de0f69d05794.png)

Thanks!

**Comment by whawker** [comment]
If you avoid using the arrow function syntax, the function will just be called with the default Highcharts scope. Like [this example](https://github.com/whawker/react-jsx-highcharts/blob/gh-pages/examples/SynchronisedCharts/App.js#L45) which uses a normal function to avoid changing the scope.

**Comment by juwilliams** [comment]
Oh yeah! I forgot about the contextual change due to anonymous functions. Thanks for the reminder!
