### ISSUE TITLE
Labels support

### ISSUE THREAD

**Issue by Gandy123** [whawker/react-jsx-highcharts#42]
Hi, 

thank you for your awesome job. I wonder is it possible to use highcharts labels ("https://code.highcharts.com/modules/series-label.js") with react-jsx-highcarts ? If you'll look at the simple example on highcharts site and your example they are the same except for the labels for line graphs.

**Comment by whawker** [comment]
It seems there is nothing for the library to add here. 

All you would need to do is apply the series-label module to the Highcharts object. See line 7 and 8 in the example [here](https://stackblitz.com/edit/react-ewdgiu?file=SplineChart.js)

**Comment by Gandy123** [comment]
Thank you, this was very usefull
