### ISSUE TITLE
Cannot read property 'padding' of undefined

### ISSUE THREAD

**Issue by TiagoSaAdvizr** [whawker/react-jsx-highcharts#44]
Hello, 
First of nice work! 
Secondly, I have been trying to implement your example [StyleByCSS](https://github.com/whawker/react-jsx-highcharts/blob/gh-pages/examples/StyleByCSS/App.js) but I am getting this error: 
What am I missing? everything works fine, except tooltip. 
```
main.js:1822 Uncaught TypeError: Cannot read property 'padding' of undefined
    at u.Tooltip.init (main.js:1822)
    at new u.Tooltip (main.js:1822)
    at n.value (adviser.entry.js:60548)
    at CallbackQueue.notifyAll (adviser.entry.js:7138)
    at ReactReconcileTransaction.close (adviser.entry.js:17784)
    at ReactReconcileTransaction.closeAll (adviser.entry.js:7796)
    at ReactReconcileTransaction.perform (adviser.entry.js:7743)
    at ReactUpdatesFlushTransaction.perform (adviser.entry.js:7730)
    at ReactUpdatesFlushTransaction.perform (adviser.entry.js:6898)
    at Object.flushBatchedUpdates (adviser.entry.js:6981)
```

My code: 
```
    <HighchartsChart plotOptions={plotOptions}>
        <Tooltip
          borderWidth={3}
          shadow={false}
          hideDelay={0}
          padding={8}
          headerFormat={'<b>Something</b>'}
          pointFormat={'{series.name}: <b>{point.percentage:.1f}%</b>'}
          valueSuffix={'%'}
        />
        <PieSeries
            id="my-pie"
            name="Asset Allocation"
            data={chartData.series[0].data}
        />
    </HighchartsChart>
```

Thanks

Note:
If we pass padding inside style prop, it doesn't crash, but `pointFormat`, `valueSuffix`, `headerFormat`are not set. 
```
<Tooltip
          borderWidth={3}
          shadow={false}
          hideDelay={0}
          padding={8}
          headerFormat={'<b>Something</b>'}
          pointFormat={'{series.name}: <b>{point.percentage:.1f}%</b>'}
          valueSuffix={'%'}
          style={{padding: 8}}
/>
```

**Comment by TiagoSaAdvizr** [comment]
Apparently we are looking for `padding` inside `style` if I do this:  
```<Tooltip style={{padding: 8}}/>```
If works fine.

**Comment by whawker** [comment]
I'm not too sure on this one, I'm struggling to reproduce it. Could you provide a bit more information?

Such as;
* Highcharts version?
* Are you exporting your Chart using `withHighcharts`?
* Are you using server side rendering?

Sorry for the late reply, been on holiday for the past 2 weeks!

**Comment by TiagoSaAdvizr** [comment]
Hi @whawker thanks for you reply,
- Version
-- 6.0.3
- Are you exporting your Chart using `withHighcharts`?
-- Yes
- Are you using server side rendering?
-- No,  Client side

No worries, I gave up.
End up writing a wrapper of my own, it was for a very small proof case. 

Thank you.
