### ISSUE TITLE
File missing in npm package: src/components/withHighcharts.js

### ISSUE THREAD

**Issue by surmistry** [whawker/react-jsx-highcharts#47]
NPM package does not match git repo 
Assuming nothing is rendering because of the missing withHighcharts( App, Highcharts ); line causing an Error: withHighcharts is not a function

![screen shot 2017-12-01 at 2 51 06 pm](https://user-images.githubusercontent.com/4741146/33500564-3b3b20ac-d6a7-11e7-9167-37049ef19c19.png)

**Comment by whawker** [comment]
Which version number is displayed in the `package.json`? `withHighcharts` wasn't added until 2.0.0

**Comment by surmistry** [comment]
Thanks for getting back so fast, i'm on 1.4.2, but I ran npm update react-jsx-highcharts and it didn't update, what's the CLI to get the latest package?

**Comment by whawker** [comment]
That would be `npm install --save react-jsx-highcharts@^2.0.0`

**Comment by surmistry** [comment]
Got it compiling properly on 2.0.2 and it's saying that the requested series still doesn't exist (highcharts.com/errors/17) and I CTRL+C/V this file into my App.js file? https://github.com/whawker/react-jsx-highcharts/blob/gh-pages/examples/Treemap/App.js

**Comment by surmistry** [comment]
Removing the <ExampleCode /> component is the only thing I changed

**Comment by whawker** [comment]
Treemaps require the additional Highcharts modules `treemap` and `heatmap`.

You need to import the additional modules and apply them to the Highcharts obj.

i.e.
```js
import Highcharts from 'highcharts';
import heatmapModule from 'highcharts/modules/heatmap';
import treemapModule from 'highcharts/modules/treemap';
heatmapModule(Highcharts);
treemapModule(Highcharts);
```
or

```js
import Highcharts from 'highcharts';

// Requires must come after all import statements
require('highcharts/modules/heatmap')(Highcharts);
require('highcharts/modules/treemap')(Highcharts);
```

**Comment by surmistry** [comment]
I figured as much, wasn't sure whether TreemapSeries was doing an include there and then noticed /Series folder was empty and got confused hahah
I wanted to design my own Treemap algorithm and wanted to use this library as a bridge to have access to 'highcharts' then compile into react.  I'm assuming that I'd be able to declare a new treemap protoType and pass the string to layoutAlgorithm?

*(amazing tech support btw)*
[https://i.imgur.com/KoDE3UM.gifv](url)

**Comment by whawker** [comment]
No worries 😄 

I would think so, although to be honest I haven't used Treemaps all that much myself.

**Comment by surmistry** [comment]
Yeah I've been prowling for a good custom React Treemaps lib and was running on fumes 
I can update you on progress if you'd like :joy:

**Comment by whawker** [comment]
Sure thing! I'm going to close this issue, seems as the originally issue was fixed.

**Comment by surmistry** [comment]
_update:_
@whawker You can define your own custom algorithm and pass it into layoutAlgorithm={} 
It's really intuitive, except for the width-height params are not quite in px/em/%  but that's just how they're defining their highchart library https://www.highcharts.com/docs/chart-and-series-types/treemap!! Great library continuing to prove it's abilities to facilitate HighchartsJS
