### ISSUE TITLE
Publish v2.0 to npm

### ISSUE THREAD

**Issue by HUSSTECH** [whawker/react-jsx-highcharts#48]
Hey, is version 2.0+ going to be making its way to npm anytime soon? Unfortunately `npm install` and `yarn add` do not support multiple packages in a repo, so I couldn't just add the latest version of this library via github directly. Thanks!

**Comment by whawker** [comment]
Hi @HUSSTECH version 2.0 is already published on NPM. I backported a fix to the 1.0 branch seems to confused NPM with that the latest version is.

`npm install --save react-jsx-highcharts@^2.0.0` should fix it in the meantime.

**Comment by HUSSTECH** [comment]
awesome thank you @whawker
