### ISSUE TITLE
YAxis numbers sometimes overlap the graph when on the right

### ISSUE THREAD

**Issue by mindjuice** [whawker/react-jsx-highcharts#50]
When rendering a `YAxis` on the `opposite` side (right), sometimes the numbers overlap the graph itself.

Live Example:
https://codesandbox.io/s/zql6o1kzx3

This only seems to happen if the `opposite` axis is rendered first.  If there is a left axis and then an `opposite` one, it works fine.  If there is only one axis, but it is `opposite`, then it overlaps.

**Comment by whawker** [comment]
I'm not sure what I can do to fix this, the [same issue](http://jsfiddle.net/3kf5t489/1/) happens with Highcharts itself.
