### ISSUE TITLE
onLoad on the Chart component doesn't work

### ISSUE THREAD

**Issue by adriantoine** [whawker/react-jsx-highcharts#53]
Hi!

First of all, thank you for your nice library!

I have found an issue which is that the `load` event doesn't seem to work, here is a minimal example: https://codesandbox.io/s/qxn6z5r589
I have copied an example from the documentation and used the `onLoad` and `onRender` callback on the `Chart` component. If you open the DevTools you'll notice that the render even is triggered but the load event is not.

Maybe there is something I didn't understand but this example should work ([here is a pure highcharts example](http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/chart/events-load/)).

Can you have a look?

Thank you!

**Comment by whawker** [comment]
Ah damn, that's annoying. 

As a workaround (depending on your use case) you might be able to use the `callback` option added in 2.0.3 - see [here](https://stackblitz.com/edit/react-ayaebf?file=index.js_)?

**Comment by adriantoine** [comment]
Hi @whawker, thanks for the quick reply! I tried the callback option, it seems to work although at the time it is executed, the `series` are not on the chart, here is the updated example: https://codesandbox.io/s/qxn6z5r589. When I log the series from the `onRender`, I get 5 series but 0 when I log them from `callback`.

**Comment by adriantoine** [comment]
I found out that for my use case, the load event wouldn't work either as the series are added after the initial load in this library.

**Comment by whawker** [comment]
What exactly were you trying to achieve with the load event?

**Comment by adriantoine** [comment]
What I need to do is to execute a drilldown when opening the graph (in my use case the graph should be shown "drilled down" to a specific point from the beginning). I rolled back to `react-highcharts` and it works great for my use case, here is an example of what I'm trying to achieve: https://codesandbox.io/s/rr82porw4q

As you can see I want to use `doDrilldown` on a specific point of a series on load but in `react-jsx-highcharts` the series are added after the initial load so this won't work as `evt.target.series` (from my example) is an empty array. I need a callback that is executed after everything is loaded and added to the graph.

**Comment by whawker** [comment]
Ah, ok. I do need to add proper support for drilldown (see #29).

**Comment by janakp2411** [comment]
Hi @whawker for now is there any workaround ?. so far I haven't started my project but very soon i will start but i am sure I need this functionality in my project.  Is there any work around to get this feature ?

**Comment by whawker** [comment]
@janakp2411 here is a workaround, it's pretty nasty and I wouldn't advise doing this way usually, but it works.

[See here](https://stackblitz.com/edit/rjh-on-load-workaround?file=MyChart.js)

**Comment by whawker** [comment]
@ricopella as all the axes and series are added to the chart dynamically, you would be best hooking into a Series render event and updating your component state.

Example here: https://stackblitz.com/edit/rjh-on-load-workaround-wvnbfx?file=MyChart.js
