### ISSUE TITLE
Multiple charts on same page share context

### ISSUE THREAD

**Issue by mattspeller** [whawker/react-jsx-highcharts#54]
Hello

I am using a layout control where a user can add multiple charts as individual components on a single page. In this case, I would like to interact with the chart instance using the underlying highcharts object so I can call the apis as needed. 

(You can see my conversation with highcharts [here](https://forum.highcharts.com/highcharts-usage/realtime-treemap-usage-resets-drilldown-on-change-t39927/))

You can see the final solution from their developers was to call drillToNode on the series. However, the navigation path to the series is a bit clunky from the react-jsx-highcharts wrapper - for example:
`        this.treemapSeries.context.Highcharts.charts[0].series[0].drillToNode(xxx); `

However it works, but it fails when we have multiple charts on the screen as the Highcharts object seems to be a singleton and contains all the instances of the chart within the single page application.

See the example below - pressing the button counts the charts attached to both instances of the HighChartsChart element. [Sandbox example](https://codesandbox.io/s/1ylkzqzp0j) 

I am pretty certain I am accessing the underlying highcharts object from the reference incorrectly, maybe even attaching the reference to the wrong element in the rendered html - however this example nicely shows the problem to obtain the series for a particular chart.

Can you provide an example how to obtain the correct underlying highcharts series object for a chart in a given context?

Thanks in advance

M@

**Comment by whawker** [comment]
Hi @mattspeller, the easiest way to get the underlying chart object is to use the `callback` prop added in version 2.0.3.

You provide a function to the callback prop, which will be called with the chart object once it is loaded.

I've modified [your example](https://stackblitz.com/edit/react-rjs6iv?file=CoupleOfLines.js) to highlight the chart and series relative to the button in the `CoupleOfLines` components.

**Comment by mattspeller** [comment]
wonderful - works a treat. I have been educating the guys on the highcharts forum how to use your wrapper :)
