### ISSUE TITLE
Multiple YAxis rerender issues

### ISSUE THREAD

**Issue by juwilliams** [whawker/react-jsx-highcharts#55]
I noticed a strange issue this evening when using multiple YAxis in a single chart. Only the first YAxis updates on rerenders triggered by prop updates.

![image](https://user-images.githubusercontent.com/10916150/33915814-9c57d326-df62-11e7-9305-a0c44d463a4b.png)

Confirmed this behavior by swapping the order of the YAxis from the image above.

Any ideas?

Thanks!

**Comment by whawker** [comment]
Would you be able to post a fuller example? It's difficult to debug those few lines out of context.

Do you mean the axes / titles themselves aren't updating? Or the series contained within them?

I've got an [example here](https://stackblitz.com/edit/react-yg2lm2?file=index.js) of two axes, each with a single series, which dynamically update their data.

**Comment by juwilliams** [comment]
Thanks again, you're example sent me down a thought tunnel that proved useful. The issue was a duplicate id prop on the two series in question. Is the 'id' prop on the series used internally as a react key?

**Comment by whawker** [comment]
It's not used as a React key, but as a means of letting the React component know which Highcharts object behind the scenes it should be interacting with. There a wiki page on IDs [here](https://github.com/whawker/react-jsx-highcharts/wiki/id-props-%28important%21%29).

**Comment by juwilliams** [comment]
Ah ok, thanks again!
