### ISSUE TITLE
Add Highmaps support

### ISSUE THREAD

**Issue by unofang** [whawker/react-jsx-highcharts#56]
Thanks for your great package!

I am doing a project to visualise a big sized dataset with longitudes and latitudes. As there is no example for map-data graphs, is there anybody know how to do the basic configuration? Thank you very much !

**Comment by whawker** [comment]
Unfortunately I haven't added support for Highmaps yet, sorry. It is definitely something I would like to add though!

**Comment by idoromm** [comment]
Would like to add that adding map support is a must for me. This project is great but having HighMaps would make it outstanding.

**Comment by whawker** [comment]
![screen shot 2018-06-15 at 07 56 43](https://user-images.githubusercontent.com/2003804/41454563-ca24868c-7071-11e8-83c2-4562e3ba03eb.png)

Making good progress on this!

**Comment by whawker** [comment]
Just published the first beta, [React JSX Highmaps 0.1.0-beta.1](https://www.npmjs.com/package/react-jsx-highmaps)!

**Comment by whawker** [comment]
@unofang @idoromm here is an example: https://stackblitz.com/edit/base-map-example-svixuf?file=MyMap.js

If you guys could play around with the beta and give me some feedback that would really help me out.

**Comment by whawker** [comment]
React JSX Highmaps has now be released

[Release notes](https://github.com/whawker/react-jsx-highcharts/releases/tag/v3.3.0)
[NPM Package](https://www.npmjs.com/package/react-jsx-highmaps)
