### ISSUE TITLE
Exporting capabilities?

### ISSUE THREAD

**Issue by Ricardo-C-Oliveira** [whawker/react-jsx-highcharts#57]
Is there a way to use highcharts exporting capabilities with this library? 
I love the declarative nature of how this library was implemented, so i was hoping that the there is a similar way to implement the chart exporting feature.

**Comment by bondz** [comment]
@Ricardo-C-Oliveira Are you looking to implement client side exporting or server side exporting?

For client side exporting.

```js
import { withHighcharts } from 'react-jsx-highcharts';

import Highcharts from 'highcharts';
import applyExporting from 'highcharts/modules/exporting';
import applyOffline from 'highcharts/modules/offline-exporting';

applyExporting(Highcharts);
applyOffline(Highcharts);

withHighcharts(Component, Highcharts);
```

That should get you offline, client-side exporting.

**Comment by Ricardo-C-Oliveira** [comment]
Oh great! This is exactly what I was looking for!

**Comment by whawker** [comment]
Thanks for the help @bondz!

**Comment by ismusidhu** [comment]
Would be good to have CSV option also.

**Comment by emoreno619** [comment]
yea, can't figure out why this works but something like

```
import * as applyExportData from 'highcharts/modules/export-data';
applyExportData(Highcharts);
```

also, any idea why this kind of implementation isn't at all mentioned in the HighCharts docs? they only [reference](https://www.highcharts.com/docs/export-module/client-side-export):
```
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/offline-exporting.js"></script>
```

**Comment by taylorbf** [comment]
Is this still the accepted answer for this question?  I am not using `withHighcharts`, that seems to have been replaced by using components directly like `HighchartsChart`, `Chart`, and `HighchartsProvider`.

**Comment by shiraleeana** [comment]
Hello @taylorbf did you get any further trying to find an answer?
I'm also looking into this. Thanks.
