### ISSUE TITLE
Stacked Area line chart?

### ISSUE THREAD

**Issue by adamalawrence** [whawker/react-jsx-highcharts#58]
Hi @whawker, does your library support stacked area charts? (https://www.highcharts.com/demo/area-stacked)

**Comment by whawker** [comment]
Yep, just need to use the `AreaSeries` component for your data, and pass in the `plotOptions` as a prop on the `HighchartsChart` component. [See here](https://stackblitz.com/edit/react-czgmxq?file=MyChart.js)
