### ISSUE TITLE
Smooth Navigator scrolling?

### ISSUE THREAD

**Issue by adamalawrence** [whawker/react-jsx-highcharts#59]
Hi @whawker, specifically for highstocks, does your library support smooth navigator scrolling, like in this demo: https://www.highcharts.com/stock/demo/basic-line

With the react-jsx-highcharts demos and my own implementations, I've noticed dragging the navbar window jumps the series to that section, rather than scrolling with the window.

Thanks!

**Comment by whawker** [comment]
I'm not sure what you mean, clicking the Navigator seems to have the same behaviour for me?

**Comment by cueas-rickmoore** [comment]
@whawker Dragging is an entirely different operation than clicking.  In your product, when the navigator is dragged, nothing happens until you stop the drag. Default behavior in Highstock is to continuously scroll the chart as you drag the navigator. Please explain how to make this work correctly in react-jsx-highcharts.

**Comment by knod** [comment]
I think what @cueas-rickmoore is talking about is 'panning'.

**Comment by adamalawrence** [comment]
This should clear things up - I made a recording of the current undesired behavior: https://imgur.com/a/LMMJyX9

**Comment by whawker** [comment]
So turns out this is simpler than I thought to implement. 🤦‍♂️ 

All you need to do is include the `<Scrollbar />` component. [Example here](https://stackblitz.com/edit/base-chart-example-cm35bl?file=MyChart.js)

**Comment by whawker** [comment]
@adamalawrence and @knod does my suggestion above fix things for you?

**Comment by knod** [comment]
@adamalawrence will have to field that one. I wasn't having a problem with horizontal panning. It just seemed like you folks may not have been talking about the same thing so I interfered. Sorry about that. It's awesome that it's such an easy fix!
