### ISSUE TITLE
Cannot render 'chart' of undefined

### ISSUE THREAD

**Issue by surmistry** [whawker/react-jsx-highcharts#60]
Hi again @whawker I'm getting this error using react-jsx-highcharts

![screen shot 2017-12-22 at 5 37 19 pm](https://user-images.githubusercontent.com/4741146/34314145-d72ff3d2-e73e-11e7-88a0-919aefd5edd9.png)

I successfully compiled my own custom algorithm in one react boilerplate I was using, then I migrated to create-react-app and found this error, here's what my imports look like: 

```javascript
import React, { Component } from 'react';
import Highcharts from 'highcharts';
import {
  HighchartsChart, Title, XAxis, YAxis, TreemapSeries, Legend
} from 'react-jsx-highcharts';
import { treeCase } from './treeCase.js';
import HighchartTreeMap from 'highcharts/modules/treemap';
HighchartTreeMap(Highcharts);
````

**Comment by whawker** [comment]
Hi @sumistry, with React JSX Highcharts v2 you need to use the `withHighcharts` wrapper to inject the Highcharts global. See [here](https://github.com/whawker/react-jsx-highcharts/wiki/Upgrading-from-1.x-to-2.x) or the [examples](https://whawker.github.io/whawker/react-jsx-highcharts)

**Comment by surmistry** [comment]
I had that at the app level on the previous react app, thanks and merry christmas
