### ISSUE TITLE
plotOptions not updating on re-render

### ISSUE THREAD

**Issue by Chikel** [whawker/react-jsx-highcharts#63]
Hi there,

It seems that chart config options are not changing on component rendering.
I have this plotOptions object inside my render function:
```
const plotOptions = {
      solidgauge: {
        dataLabels: {
          y: -30,
          borderWidth: 0,
          useHTML: true,
          format: this.getDataLabelFormat()
        }
      }
    };
```

the `this.getDataLabelFormat()` gets the data labels format on each render.
When I get a new prop that is inserted to the format, it doesn't change the data labels.
I had the same issues with other properties in plotOptions and Series props also.
It seems as though once you configure the chart, you can't alter it's props.

**Comment by whawker** [comment]
Would you mind posting an example in CodeSandbox? So I can better investigate what's going on?

**Comment by Chikel** [comment]
Hi Will, thanks for your time.
I used StackBlitz for my issue, here's my [demo](https://stackblitz.com/edit/react-8hv9hx?file=index.js).

**Comment by whawker** [comment]
Hi @Chikel, I don't believe it is possible to update `plotOptions` after initialisation.

Here is [an example](http://jsfiddle.net/18u9h72e/) using vanilla Highcharts (without React), and as you can see the Chart colour is updated, but the `plotOptions` do not get updated.

In your StackBlitz example, you might be able to achieve the desired effect, by using min `<XAxis min={2010} >`, but more complex plotOptions changes might be more difficult to replicate.

**Comment by Chikel** [comment]
I see, thanks anyway. I guess I'll need to remount the chart when my props change. I have a use case where a user filters data which change the point start.

**Comment by whawker** [comment]
@Chikel [here](https://stackblitz.com/edit/react-uqgnoh?file=index.js) an example of using `<XAxis min={}>` instead of plotOptions, if it helps.
