### ISSUE TITLE
Chrome Console Error

### ISSUE THREAD

**Issue by pythoncreate** [whawker/react-jsx-highcharts#64]
i'm getting this error in chrome dev tools.  doesn't appear to be hindering performance but wondering if anyone knows what this might be?

```
Uncaught TypeError: event.srcElement.className.StartsWith is not a function
    at HTMLDocument.onDOMModified (chrome-extension://ildhoddlaaaneelljhohbndmjbjbfgcl/content/links.js:40)
```

**Comment by whawker** [comment]
That stack trace would suggest the error is coming from a Chrome extension you have installed. Googling the extension ID (`ildhoddlaaaneelljhohbndmjbjbfgcl`) suggests is might be [Avaya Collaboration Services](https://www.reasoncoresecurity.com/manifest.json-cac3a2923ed7e6bac9e73902d9104fc340704e80.aspx), do you have that extension installed?

If you try running Chrome in Incognito mode, (which should disable the extension) do you see the same error?

**Comment by pythoncreate** [comment]
yeah i think you are right --this is an extension issue--works fine in incognito mode.  I will investigate further.  Thanks!

**Comment by whawker** [comment]
No worries!
