### ISSUE TITLE
Graph Not Redrawing Correctly When Updating Data Quickly

### ISSUE THREAD

**Issue by mindjuice** [whawker/react-jsx-highcharts#66]
I've got a graph where data is being delivered asynchronously in batches.

When the first batch or two of data is received, the graph draws correctly.  As subsequent batches of data are added however, the main graph does not always update, even though you can see the data appear in the navigator control.

The code is creating a new data array each time a new batch is received.

If I click and drag the mouse on the navigator, the main graph redraws correctly and works from that point onward.

The following is a recording that shows this happening:

https://vimeo.com/253485306

I think this is a race condition of some kind, because if I increase my batch size (thus making it take longer in between batches), then the graph updates properly.  My guess is that when the graph receives the next batch update, it has not finished updating from the previous batch and things go south from there.

Any ideas?

**Comment by whawker** [comment]
Would it be possible to post your code in CodeSandbox or something? I difficult to figure out what exactly is going wrong from just the video.

**Comment by mindjuice** [comment]
Hrmmm...yeah...it's part of a huge project that isn't open source.  I'll have to see if I can find some time to repro it with a subset of the code.

**Comment by whawker** [comment]
This looks like it might be the same issue as #69, and hence may be dependent on https://github.com/highcharts/highcharts/issues/7632.

This is a workaround suggested in #69, perhaps you could give that a go too?

**Comment by whawker** [comment]
Any luck with the suggested workaround @mindjuice?

**Comment by mindjuice** [comment]
Thanks for checking in.  I had to work on making highchairs with with nanoseconds resolution the past few days.  Now I need to work on selection handling (requesting higher-resolution data from the server when you zoom in) and I'll will be calling `setExtremes` after each data fetch anyway, so I should know in a day or two if that works.

**Comment by whawker** [comment]
@mindjuice This may be fixed in version 3, see the example [here](https://stackblitz.com/edit/rjh-rapidly-updating-data?file=MyChart.js)

Would you mind giving Version 3 a go?
