### ISSUE TITLE
To Date in Right Showing the Wrong Date

### ISSUE THREAD

**Issue by pythoncreate** [whawker/react-jsx-highcharts#68]
Hi please see my code--showing a date ten days from now

https://codesandbox.io/s/13om50k2p4

**Comment by whawker** [comment]
That is odd, in the meantime as a workaround, you can add the mix and max values in your state to the `XAxis`. Which fixes the issue.

```jsx
<XAxis min={min} max={max}>
```

P.s. As an aside, I think you are computing the initial `now` data incorrectly, 

instead of 
```js
state = {
  now: (Math.round(Date.now()) * 1000)
}
```

I think you mean
```js
state = {
  now: Math.floor(Date.now() / 1000)
}
```

**Comment by pythoncreate** [comment]
absolutely on point.  thanks so much.
