### ISSUE TITLE
Chart Not Re-Rendering Upon Change in Data/Props

### ISSUE THREAD

**Issue by pythoncreate** [whawker/react-jsx-highcharts#69]
Hi I'm passing a query input from a user to my Graph component, which is fetching data from an API based on the user query.  Looks like it is hooked up correctly and data is pulling fine, but chart isn't re-rendering.  Is there something I need to do to get the graph to respond to any updated data?

**Comment by pythoncreate** [comment]
might be hard to tell what I'm referring to without the input/search components, but here is my graph component code  https://codesandbox.io/s/13om50k2p4

**Comment by whawker** [comment]
I suspect the issue in that your `YAxis` and `AreaSplineSeries` have the same `id`. When props change React JSX Highcharts updates the wrong chart component behind the scenes.

**Comment by pythoncreate** [comment]
so when i change to this....  
```
<YAxis id="price">
            <YAxis.Title>Price</YAxis.Title>
             {this.state.loaded &&<AreaSplineSeries id="data1" name="Price" data={data1} />}
          </YAxis>
```
when i fetch data from new prop the chart shows now as blank--am i doing something wrong?

**Comment by pythoncreate** [comment]
figured it out--navigator had wrong ID.  thanks for your help!

**Comment by pythoncreate** [comment]
actually seems to be only re-generating if i play with the graph.  does this look right?


   ```
       <XAxis min={min} max={max}>
            <XAxis.Title>Date</XAxis.Title>
          </XAxis>

          <YAxis id="price">
            <YAxis.Title>Price</YAxis.Title>
             {this.state.loaded &&<AreaSplineSeries id="data1" name="Date" data={data1} />}
          </YAxis>

          <Navigator>
            <Navigator.Series seriesId="data1" />
          </Navigator>
```

**Comment by pythoncreate** [comment]
Oddly enough--if i remove the Navigator--it works fine..so not sure if i'm doing something wrong with that?

**Comment by pythoncreate** [comment]
my updated code if you need it https://codesandbox.io/s/13om50k2p4

**Comment by pythoncreate** [comment]
so, also i can see that the navigator is updating with the new data, but main chart is not (sorry for all the comments)

**Comment by whawker** [comment]
Yes, something strange going on with the navigator there. 

I can see the `Series.setData` Highcharts method is being called behind the scenes, with the correct data. However then it seems the data is be processed incorrectly by Highcharts, resulting in only a single data point. 

I have a poke around to see if I can figure out why...

**Comment by pythoncreate** [comment]
ok, much appreciated..thanks

**Comment by whawker** [comment]
I think this might be related to the open Highcharts issue [#7632](https://github.com/highcharts/highcharts/issues/7632), as it doesn't seem to present in Highcharts v5. 

I think you could use the workaround suggested in the issue there, by calling `setExtremes` manually _after_ the data changes, via the `callback` feature of React JSX Highcharts

```jsx
componentDidUpdate(prevProps, prevState) {
  if (this.props.searchTerm !== prevProps.searchTerm) {
    this.getData(this.state.now, this.props.searchTerm);
  }

  if (this.state.data1.length !== prevState.data1.length) {
    this.chart.xAxis[0].setExtremes(this.state.min, this.state.max);
  }
}

getChart = chart => {
  this.chart = chart;
}

render () {
  return (
    <HighchartsStockChart callback={this.getChart}>
      //...
    </HighchartsStockChart>
  );
}
```

**Comment by pythoncreate** [comment]
sweet that works--thank you!  the only minor issue is it looks like the 'to' date is now at tomorrow--any idea why that might be?
