### ISSUE TITLE
OnClick event stops working after new data from props

### ISSUE THREAD

**Issue by cabutler10** [whawker/react-jsx-highcharts#70]
I am experiencing an issue with onClick events not working after new data is passed to a chart. I have created a sandbox to replicate my issue;

 https://codesandbox.io/s/q8nolv1jx4

The onClick event works initially, however after clicking the 'Change Dataset' button, the onClick event stops working. Do you have any suggestions as to what might be causing this?

**Comment by whawker** [comment]
The method you have used in your CodeSandbox, creates a new function on every render - this React doc explains the issue better than I can https://reactjs.org/docs/faq-functions.html#why-is-binding-necessary-at-all

```jsx
<ColumnSeries
  id="column"
  data={props.data}
  onClick={function(e) {
    alert("OnClick works! - But we're creating a new function on every render!");
  }}
/>
```

With React you usually pass functions bound to the component

```jsx
class MyComponent extends React.Component {
  handleClick = () => {
    alert('Hello');
  }

  render () {
    return <div onClick={this.handleClick} />
  }
}
```

The reason being, the next time the component renders, the component will receive **the same function reference** as in the previous render.

I have forked your CodeSandbox, with correct code here: https://codesandbox.io/s/n0jop7968p

**Comment by cabutler10** [comment]
Thanks!
