### ISSUE TITLE
How to use a custom series for the Navigator?

### ISSUE THREAD

**Issue by georgiopandarez** [whawker/react-jsx-highcharts#71]
Hi,

I cannot see how to use a custom series for the Navigator.

Navigator.Series only takes a seriesId, and highcharts uses the showInNavigator setting otherwise. My use case is to specify a custom series for the navigator (ie the whole dataset) while only loading the specific date range into highcharts for the main graph.

**Comment by whawker** [comment]
I would suggest adding a Series to the chart as usual, but hiding it using visible=false?

```jsx
<YAxis id="myAxis">
  <LineSeries id="mySeries" data={data} visible={false} /> // visible={false} hides the series
</YAxis>

<Navigator>
  <Navigator.Series seriesId="mySeries" />
</Navigator>
```

Here is [an example](https://stackblitz.com/edit/react-1xufqw?file=MyChart.js)

**Comment by whawker** [comment]
Hi @georgiopandarez does the above suggestion solve your issue?

**Comment by georgiopandarez** [comment]
It works, I also need to have showInLegend={false} on the series.

It would be nice just being able to set the navigator series directly.

**Comment by whawker** [comment]
It's a bit difficult to do that with the current architecture, but I'll consider it when I do the React 16.3 context api rewrite #74

**Comment by jgonzalez4** [comment]
Hi, this still isn't working in the latest version (3.2.1) with latest react and highcharts. 

A series will only show in the navigator if it is visible in the main chart with the latest libraries. Ideally I'd also like to be able to pass a dataset directly to Navigator.Series like in this high stock [example](http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/navigator/series-data/)

Is it something you're thinking of fixing?
