### ISSUE TITLE
Navigator and updating data

### ISSUE THREAD

**Issue by georgiopandarez** [whawker/react-jsx-highcharts#72]
Hi,

Updating a highstock graph data with the navigator results in no graph being displayed. Clicking on the range selector brings the data back.

Removing the navigator from the graph also resolves the issue.

**Comment by georgiopandarez** [comment]
I worked around this by implementing a custom component and calling setExtremes()

    componentDidUpdate(prevProps) {
        if (!isEqual(prevProps, this.props)) {
            for (let series of this.props.getChart().series) {
                series.xAxis.setExtremes();
            }

**Comment by Sivanga** [comment]
@georgiopandarez Can you please share your workaround? Tnx!

**Comment by whawker** [comment]
Closing as stale, happy to reopen if someone can provide a StackBlitz/CodeSandbox demonstrating issue.
