### ISSUE TITLE
Use new context api where available (React 16.3)

### ISSUE THREAD

**Issue by whawker** [whawker/react-jsx-highcharts#74]
See here https://github.com/diegohaz/awesome-react-context

- [x] Update `react-jsx-highcharts`
  - [x] Use `create-react-context` to enable 16.3 context api where available
  - [x] Remove id required props
  - [x] Provide useful error messages when additional modules are not found (i.e. `highcharts-more`)
  - [x] Update tests
- [x] Update `react-jsx-highstock`
  - [x] Use `create-react-context` to enable 16.3 context api where available
  - [x] `Navigator` and `RangeSelector` should probably use provided x axis, rather than provided chart 
  - [x] Provide useful error messages when additional modules are not found (i.e. `highcharts-more`)
  - [x] Update tests
- [x] Update `react-jsx-highstock-datepickers` 
  - [x] Update `react-jsx-highstock` dependency and publish

**Comment by whawker** [comment]
Proposed changes to implement this

1. Keep the React JSX Highcharts API the same
1. However, **drop support** for React **15**
1. This would of course, by a breaking change for some users, so will form react-jsx-highcharts 3.0.0

StackBlitz experiments with new context api
React 16.3: [here](https://stackblitz.com/edit/highcharts-context-experiments-3?file=index.js)
React 16.2: [here](https://stackblitz.com/edit/highcharts-context-experiments-4?file=index.js) - uses `create-react-context` as a polyfill.

**Comment by anajavi** [comment]
As there are lifecycle changes in React 16.3, it would be easier to drop support for React < 16.3. Otherwise the new lifecycles need to be polyfilled too. https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html

The react-leaflet also has been rewritten with the new lifecycles and new context API without the polyfills:
https://github.com/PaulLeCam/react-leaflet/tree/v2

**Comment by whawker** [comment]
I hadn't planned on using the new life cycle methods in this version, as the main project I use this for is still using React 16.2, I will consider it though.

**Comment by whawker** [comment]
Additionally in version 3, I plan to 
* auto generate IDs for Axis/Series etc, (if not supplied)
* Prevent more user friendly errors when a user tries to use a Series type that is not available
    * For example using an Area Range series without Highcharts More

My main aim with this new version, is to simply the codebase to attract more collaborators, as I am struggling to find the time to support the project.

**Comment by whawker** [comment]
For those interested, I've just published `react-jsx-highcharts@3.0.0-alpha.5`, would love for people to help me test. Please post here if you discover any issues.

**Comment by anajavi** [comment]
Should the YAxis, ColumnSeries and ErrorBarSeries work without setting id attribute with the 3.0.0-alpha.5?

I'm getting strange results if I remove them from more than one YAxis.

**Comment by whawker** [comment]
That's the idea - if no id is present, it should [default to a uuid](https://github.com/whawker/react-jsx-highcharts/blob/new-context-api/packages/react-jsx-highcharts/src/components/Series/Series.js#L31)

**Comment by anajavi** [comment]
I think the problem is that every axis gets the same uuid. I put console.log(this.props.id) in Axis and it logs the same string for every axis.

**Comment by anajavi** [comment]
static assignments in the classes are run only once for each class, so every instance of Axis has the same uuid:
```javascript
  static defaultProps = {
    id: uuid(),
    children: null,
    dynamicAxis: true
  };
```

One way to solve it would be moving the id to state and have:
```javascript
  state = {
    id: this.props.id || uuid();
  }
```

**Comment by whawker** [comment]
Very strange, I'm not seeing the same issue on [my tests](https://rjh-v3-fork.stackblitz.io/AddSeries), I'll look into it

**Comment by anajavi** [comment]
I made an [example](https://stackblitz.com/edit/rjh-v3-fork-atdbsg?file=src%2FCombo%2FCombo.js) of the problem. In the example the second YAxis max={100} overrides first YAxis max={10}.

The problem goes away when id is set to either YAxis.

**Comment by anajavi** [comment]
It’s reproduced in your screenshot. The ”Jane” columns should reach the top, but instead they are on same axis as ”John”. Try adding id’s to YAxis elements, and they will change.

**Comment by whawker** [comment]
Ah yeah, I see it now, your suggested fix makes sense. 

I don't have access to my laptop for the rest of the weekend, would you mind opening a PR against the `new-context-api` branch? No worries if you're also busy though

**Comment by anajavi** [comment]
As this needs refactoring anyway, the componentWillMount contents could be moved to componentDidMount at the same time to remove the deprecated lifecycle method. That way the React 16.4 would not whine about it.

Kind of busy right now, will try it if I have the time.

**Comment by whawker** [comment]
Yeah fair point, don't worry about it, I can pick this up on Sunday evening. Cheers though.

**Comment by anajavi** [comment]
PR in #100

**Comment by anajavi** [comment]
Found another bug. In PlotLine:
TypeError: axis.addPlotLine is not a function

[example](https://stackblitz.com/edit/rjh-v3-fork-wgratx?file=src/SimpleLine/SimpleLine.js)

Also, just noticed that PlotLine and PlotBand have uuid() in defaultProps.

**Comment by whawker** [comment]
Whoops! Good spot!

**Comment by whawker** [comment]
Published `react-jsx-highcharts@3.0.0-alpha.6` which should fix the above issues. Thanks @anajavi!

**Comment by anajavi** [comment]
What are your plans regarding releasing this? Or do you still have things to do before releasing?

**Comment by whawker** [comment]
Still work to do I'm afraid, I need to update the highstock and datepickers packages, and update all the tests 😢

**Comment by anajavi** [comment]
As enzyme does not yet understand the new context, it can be made to use react 16.2 with context polyfilling by fixing version in devDependencies:
```javascript
    "react": "16.2.0",
    "react-dom": "16.2.0",
    "react-test-renderer": "16.2.0",
```

I checked the tests and there is indeed a lot of work..

**Comment by whawker** [comment]
I've updated the version first comment to display all things that still need to be done.

**Comment by whawker** [comment]
Just pushed informative error messages (on development environments), see example below

![screen shot 2018-05-23 at 13 16 29](https://user-images.githubusercontent.com/2003804/40423872-bedb887c-5e8b-11e8-8c10-240af38c2b71.png)

**Comment by anajavi** [comment]
I think the error messages work now only on ESM-build. The webpack overwrites "process.env.NODE_ENV" by default on UMD-build.

https://webpack.js.org/concepts/mode/

**Comment by whawker** [comment]
Ah yes, I thought that might happen. But it works with Create React App, which hopefully covers the majority of use cases.

**Comment by anajavi** [comment]
It might be possible to turn it off on webpack.config with something like this:
```
optimization: {
  nodeEnv: false
}
```
https://webpack.js.org/configuration/optimization/#optimization-nodeenv

I can try it out later, if it matters.

**Comment by anajavi** [comment]
It came to my mind, that it is possible to use the umd build without any kind of bundler. Then the process would be undefined and cause errors.

So it might be better to leave it as is.

**Comment by whawker** [comment]
Cool, I've just pushed the final to do list item, so can hopefully publish v3 soon. Just want to get to the bottom of #94 if I can!

**Comment by anajavi** [comment]
I think you already fixed #94. It works for me on 3.0.0-alpha.8, but fails on 2.2.1.

Nice work!

**Comment by whawker** [comment]
Well it displays a black squares initially, but doesn't render properly until you resize the browser window.

Seems to be something to do with calling `chart.reflow()` but I can't figure why that's required.

**Comment by anajavi** [comment]
I am not able to reproduce the problem with the latest alpha.

The problem might be in the css width of the containing div. Do you have stackblitz for the problem?

**Comment by whawker** [comment]
I do, code [here](https://stackblitz.com/edit/rjh-v3-fork?file=src%2FTreemap%2FTreemap.js), output [here](https://rjh-v3-fork.stackblitz.io/Treemap).

**Comment by anajavi** [comment]
While debugging #94 I noticed that chart events don't seem to be firing:
```javascript
        <HighchartsChart
          onRedraw={ () => console.log("redraw") }> // does not fire
```
Setting them in the chart config works:
```javascript
        <HighchartsChart
          chart={
            { events: {
              redraw: () => console.log("REDRAW") // fires correctly
            }
            }
          }>
```

**Comment by whawker** [comment]
Hi @anajavi those events need to be added to the `<Chart />` sub component, which maps to the [`chart`](https://api.highcharts.com/highcharts/chart) Highcharts configuration group.

```jsx
<HighchartsChart>
  <Chart onRedraw={() => console.log('Redraw')} />
```

**Comment by anajavi** [comment]
Thanks, I wasn't thinking straight.

What would you say about the following:

- Calling addSeries with redraw = false in Series component: addSeries(opts, false)
- Add chart.redraw() in HighchartsChart componentDidUpdate()

HighchartsChart componentDidUpdate() should run after all children are rendered, so it should redraw the chart. I could be wrong of course :)

I think that this could solve #94 and possibly be more performant.

**Comment by whawker** [comment]
It looks as if the parent's `componentDidUpdate` is not always called when the Child component is rendered, take [this example](https://stackblitz.com/edit/react-qs1fve?file=index.js)

I think the application state changes need to happen above (or at) the parent component for `cDU` to be called

**Comment by anajavi** [comment]
I tried it with chart.redraw and it did not help #94.

I think that the treemap is not getting right data from the chart on first run, if you check the HTML it produces, it shows that colors are set NaN:
```svg
<rect x="416.5" y="145.5" width="109" height="117" fill="rgb(NaN,NaN,NaN)" stroke="#e6e6e6" stroke-width="1" class="highcharts-point highcharts-color-0"></rect>
```

No idea why that happens, maybe a race condition in highcharts.

**Comment by whawker** [comment]
Thanks a lot for having a look. I think we might just have to launch v3 without it, and patch later on.

I'm feeling excited to launch v3, and you have waited very patiently for it.

**Comment by anajavi** [comment]
I managed to reproduce treemap problem with pure highcharts:
https://jsfiddle.net/brdjj8y7/

It can be fixed in pure highcharts by not setting yAxis in treemap config.

**Comment by whawker** [comment]
Just published v3, here are the [release notes](https://github.com/whawker/react-jsx-highcharts/releases/tag/v3.0.0).

Thanks so much @anajavi!

**Comment by anajavi** [comment]
Thanks for the mention :) And congratulations for the release, you did great work!

I'm very happy with the lifecycle rewrites, with luck there isn't more to do for React 17 compatibility. 
And now I can start testing with unstable_AsyncMode.

If you have more roadmap in your mind, just add issues or something for them.

One thing I have been thinking is using Flow typings, not terribly important though. These can be transformed to prop-types with [babel-plugin-flow-react-proptypes](https://github.com/brigand/babel-plugin-flow-react-proptypes)
