### ISSUE TITLE
Are Exporting & Legend click event handling possible

### ISSUE THREAD

**Issue by mariogaljr** [whawker/react-jsx-highcharts#78]
https://jsfiddle.net/gh/get/jquery/1.11.0/highslide-software/highcharts.com/tree/master/samples/highcharts/exporting/offline-download-demo/

As you can see the link, I'd love to add offline exporting to the chart.

Additionally, I'd love to know there would be some functions to trigger legend click event.

Thanks

**Comment by whawker** [comment]
Hi @mariogaljr, you should be able to add exporting by applying the modules to the Highcharts object, [see here](https://github.com/whawker/react-jsx-highcharts/issues/57#issuecomment-352361456)

P.s. I don't believe the legend supports click events? https://api.highcharts.com/highcharts/legend

**Comment by whawker** [comment]
[Here is an example](https://stackblitz.com/edit/react-5awj7x?file=MyChart.js) of legend item click events.
