### ISSUE TITLE
Adding Event on RangeSelector.Button is not working

### ISSUE THREAD

**Issue by mwubgadeashish** [whawker/react-jsx-highcharts#79]
```<RangeSelector selected={1}>
                    <RangeSelector.Button count={24} type="hour" onClick={this.handleClick}>P</RangeSelector.Button>
                    <RangeSelector.Button count={1} type="day">1d</RangeSelector.Button>
                    <RangeSelector.Button count={2} type="day">2d</RangeSelector.Button>
                    <RangeSelector.Button count={1} type="week">1w</RangeSelector.Button>
                    <RangeSelector.Button count={1} type="month">1m</RangeSelector.Button>
                    <RangeSelector.Button type="all">all</RangeSelector.Button>
                </RangeSelector>```

I am trying to add a click event on button and seems its not working. I have also added following line:
```
// In constructor
this.handleClick = this.handleClick.bind(this);
//added method
handleClick  = (e) => {
        console.log('Click');
    }

```

**Comment by mwubgadeashish** [comment]
I am not sure but does it has something to do with events in 

adding events in RangeSelectorButton.js
==================================
componentDidMount () {
    const button = this.getButtonIndex();
    if (button > -1) return; // Button already present

    const { count, type, children } = this.props;
    const buttons = [
      ...this.getButtons(),
      {
        count,
        type,
        text: children
      }
    ];
    this.updateRangeSelectorButtons(buttons);
  }

**Comment by mwubgadeashish** [comment]
@whawker can you please help me on this?

**Comment by whawker** [comment]
Hi sorry, was not aware RangeSelector buttons supported click events. 

I've just published `react-jsx-highstock@2.2.1` which adds support for this use case, which works in the way you assumed

```jsx
<RangeSelector selected={1}>
  <RangeSelector.Button count={24} type="hour" onClick={this.handleClick}>P</RangeSelector.Button>
  <RangeSelector.Button count={1} type="day">1d</RangeSelector.Button>
  <RangeSelector.Button count={2} type="day">2d</RangeSelector.Button>
  <RangeSelector.Button count={1} type="week">1w</RangeSelector.Button>
  <RangeSelector.Button count={1} type="month">1m</RangeSelector.Button>
  <RangeSelector.Button type="all">all</RangeSelector.Button>
</RangeSelector>
```

**Comment by mwubgadeashish** [comment]
@whawker I have update react-jsx-highstock@2.2.1 and i can see the changes but unfortunately I can not see the event has been called. On my side i have not done any changes in my code.
Please let me know if i need to make any changes on my side.

Thanks,
Ashish

**Comment by mwubgadeashish** [comment]
<img width="446" alt="screen shot 2018-03-07 at 8 30 01 am" src="https://user-images.githubusercontent.com/20344499/37104582-f19481b0-21e1-11e8-8d91-d81877082ac1.png">

**Comment by whawker** [comment]
Hi @mwubgadeashish [here](https://stackblitz.com/edit/react-p4ghrh?file=MyChart.js) is an example of Range Selector buttons with `onClick` events.

**Comment by mwubgadeashish** [comment]
I am not sure what can be the issue but things works well with your example (above) and does not work with my code: Ex: range selector shows at bottom of chart.
<RangeSelector selected={0} verticalAlign="bottom">
                    <RangeSelector.Button count={1} type="day">1 day</RangeSelector.Button>
                    <RangeSelector.Button count={1} type="week">1 week</RangeSelector.Button>
                    <RangeSelector.Button count={1} type="month">1 month</RangeSelector.Button>
                    <RangeSelector.Button type="all">All Time</RangeSelector.Button>
                </RangeSelector>

**Comment by mwubgadeashish** [comment]
@whawker 
[PredictionFullChart.txt](https://github.com/whawker/react-jsx-highcharts/files/1795022/PredictionFullChart.txt)
