### ISSUE TITLE
Cannot read property 'stockChart' of undefined

### ISSUE THREAD

**Issue by ImranChowdhry** [whawker/react-jsx-highcharts#80]
I followed your guidance on this issue, I am importing this

```
import Highcharts from 'highcharts/highstock';
import {
  HighchartsStockChart, Chart, withHighcharts, XAxis, YAxis, Title, Legend,
  AreaSplineSeries, SplineSeries, Navigator, RangeSelector, Tooltip
} from 'react-jsx-highstock';
```
I receive this error after copying your example 

The following code is used

`              <HighchartsStockChart>
                <Chart zoomType="x" />

                <Title>Highstocks Example</Title>

                <Legend>
                  <Legend.Title>Key</Legend.Title>
                </Legend>

                <RangeSelector>
                  <RangeSelector.Button count={1} type="day">1d</RangeSelector.Button>
                  <RangeSelector.Button count={7} type="day">7d</RangeSelector.Button>
                  <RangeSelector.Button count={1} type="month">1m</RangeSelector.Button>
                  <RangeSelector.Button type="all">All</RangeSelector.Button>
                  <RangeSelector.Input boxBorderColor="#7cb5ec" />
                </RangeSelector>

                <Tooltip />

                <XAxis>
                  <XAxis.Title>Time</XAxis.Title>
                </XAxis>

                <YAxis id="price">
                  <YAxis.Title>Price</YAxis.Title>
                  <AreaSplineSeries id="profit" name="Profit" data={data1} />
                </YAxis>

                <YAxis id="social" opposite>
                  <YAxis.Title>Social Buzz</YAxis.Title>
                  <SplineSeries id="twitter" name="Twitter mentions" data={data2} />
                </YAxis>

                <Navigator>
                  <Navigator.Series seriesId="profit" />
                  <Navigator.Series seriesId="twitter" />
                </Navigator>
              </HighchartsStockChart>`

![33131fba9ca9ca60adc9a77af038c295](https://user-images.githubusercontent.com/22918121/37141023-901a65da-2268-11e8-8a9c-eb9744157ee1.png)

![](https://i.gyazo.com/6a7dcc75c661b2704c6f360553860a3c.png)

**Comment by whawker** [comment]
You need to use the `withHighcharts` HOC, as explained in the [README](https://github.com/whawker/react-jsx-highcharts#common-issues) and [the wiki](https://github.com/whawker/react-jsx-highcharts/wiki/Higher-Order-Components#withhighcharts-version-200)

**Comment by ImranChowdhry** [comment]
@whawker I am sorry I just re-read this, so it needs to be it's own module? I was going to re-edit my comment. I apologize
