### ISSUE TITLE
onClick does not work for first time on Series, PieSeries..

### ISSUE THREAD

**Issue by sumitkothariqp** [whawker/react-jsx-highcharts#81]
After loading chart when I click on pie slice, it does not execute the function for first time but if I click it again then it works and for each click it works.

Issues to be persist for first click only.

**Comment by whawker** [comment]
Hi @sumitkothariqp, I'm not able to reproduce the issue mentioned ([see here](https://stackblitz.com/edit/react-xbgklq?file=PieChart.js)). Would you be able to post a broken example?

**Comment by sumitkothariqp** [comment]
Hi thanks for the update. 
I tried my code in your example and it worked. But it is still not working with my dashboard.
I am using react grid layout and redux. I am still identifying the issue at my end.

Thanks for creating react-jsx-highcharts.. really helpful.
