### ISSUE TITLE
Setting the axis scale via min and max?

### ISSUE THREAD

**Issue by meotch** [whawker/react-jsx-highcharts#83]
As far as I'm aware, this isn't possible to set in react-jsx-highcharts currently (please correct me if I'm wrong)!

In highcharts this would be done like so:

xAxis: {
    	min:-300,
        max:300
}

It would be great if we could set it as a prop in the axis component (or at all):

<XAxis min={this.props.min} max={this.props.max}>
            <XAxis.Title>{this.props.xField}</XAxis.Title>
</XAxis>

**Comment by whawker** [comment]
Hi @meotch, min and max do work on the xAxis, [see here](https://stackblitz.com/edit/react-z5srf7?file=MyChart.js) for an example

**Comment by meotch** [comment]
Closed the issue, thanks for responding so quickly!
