### ISSUE TITLE
Adjusting radius for each marker doesn't work and Y values in scatter charts appear with spaces in tooltip

### ISSUE THREAD

**Issue by meotch** [whawker/react-jsx-highcharts#84]
Currently, setting the marker radius doesn't seem to adjust the size of the marker in the chart. 

Also, spaces are being injected into the tooltip display of the y values irregularly (in vanilla highcharts, they seem to use spaces for every thousandth place ie 1,000 is 1 000). Example: http://jsfiddle.net/oogwjmeL/1/

var pair = {
name: key,
x: someValue,
y: anotherValue,
marker: {
radius: sqrdSize
}
};

**Comment by whawker** [comment]
Hi @meotch, spaces are [the default separator](https://api.highcharts.com/highcharts/lang.thousandsSep) for thousands in Highcharts; you can change this option before passing Highcharts via `withHighcharts`.

```jsx
Highcharts.setOptions({
  lang: { thousandsSep: ',' }
});

// Omitted

export default withHighcharts(MyChart, Highcharts);
```
P.s. [Here](https://stackblitz.com/edit/marker-size-example?file=MyChart.js) is an example of marker size change on a Scatter series.

**Comment by meotch** [comment]
Adding that fix only adds comma's for the Y values and Z values, X still doesn't format correctly as expected (for a Bubble Chart)
