### ISSUE TITLE
Data point hover popup & y axis label formatting

### ISSUE THREAD

**Issue by jcpny1** [whawker/react-jsx-highcharts#85]
When I hover over my line chart, I'm not getting any data point popups. Are they supported?

Also, highcharts shows the method below to format y axis labels. Is that supported? If so, I can't figure out how to represent the nested attributes in the YAxis component.
```
 yAxis: {
        labels: {
            format: '{value} km'
        }
    },
```

**Comment by totaldis** [comment]
example...
```js
<YAxis 
        id="yAxis1" 
        showFirstLabel={false} 
        labels={{ format: '{value} km' }} 
        tickPixelInterval={60}
        { ...yAxisOpt } > 
... 
</YAxis>

**Comment by jcpny1** [comment]
Terrific. Thanks.
