### ISSUE TITLE
Wrong Legend using the labelFormatter

### ISSUE THREAD

**Issue by em-ka** [whawker/react-jsx-highcharts#87]
Hi, thank you for this excellent library! It works great except I'm not able to update the `Legend` of the chart using the `labelFormatter`. To be specific the legend updates but with data valid to the chart from the previous chart data refresh. Interesting, that the `Tooltip` formatter works as expected. I prepared a simplified example, try to click on the Toggle data button several times:

[![Edit kk935onm67](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kk935onm67)

Using HighCharts 5.0.14, react-jsx-highcharts 2.2.1

**Comment by whawker** [comment]
I don't believe this is an issue with React JSX Highcharts, I think this is an issue with Highcharts itself.

As you can see from [this vanilla JS example](http://jsfiddle.net/06L3w4gw/1/) the legend is not re-render when the data is updated.

As a workaround, I would suggest manually rendering the legend when the chart is redrawn, using an event handler.

```jsx
  getChart = chart => {
    this.chart = chart;
  }

  updateLegend = () => {
    this.chart && this.chart.legend.render();
  }

  render () {
    return (
      <HighchartsChart callback={this.getChart}>
        <Chart onRedraw={this.updateLegend} />

        // Omitted
      </HighchartsChart>
    );
  }
```
See the full workaround [here](https://codesandbox.io/s/xolo1l49yo)

**Comment by em-ka** [comment]
Thank you Will, you rock! Works like a charm.
