### ISSUE TITLE
Urgent help required in using boxplot

### ISSUE THREAD

**Issue by terryyylim** [whawker/react-jsx-highcharts#88]
This is my current code, I am unable to use the BoxPlot and I'm experiencing "Uncaught Error: Highcharts error #17". Is there something I did not import or something wrong with my syntax for BoxPlotSeries?
Really need help urgently for a project due in 1 week's time, thank you in advance!

import React, {Component} from 'react';
import { withHighcharts, HighchartsChart, Chart, XAxis, YAxis, Title, Subtitle, Legend, LineSeries, BoxPlotSeries } from 'react-jsx-highcharts';
import Highcharts from 'highcharts';

render() {
      if (this.state.mount === true) {
        return(
        <div>
          <HighchartsChart>
            <Chart />

            <Title>Performance over Past 20 Levels</Title>

            <Subtitle>Source: App</Subtitle>

            <XAxis>
                <XAxis.Title>Level</XAxis.Title>
            </XAxis>

            <YAxis id="number">
              <YAxis.Title>Percentile</YAxis.Title>
              <BoxPlotSeries id="1" name="L1" data={[this.state.performanceArr[0]['minTiming'],this.state.performanceArr[0]['25thPercentile'],this.state.performanceArr[0]['medianTiming'],this.state.performanceArr[0]['75thPercentile'],this.state.performanceArr[0]['maxTiming']]} />
            </YAxis>
          </HighchartsChart>
        </div>
        )} else {
          return null;
        }
      }
    }

export default withHighcharts(StudentBoxPlot, Highcharts); // Injecting the Highcharts object

**Comment by whawker** [comment]
Hi, Box Plot is not included in the standard series set, you need to extend Highcharts with the "more" module they provide.

```js
import Highcharts from 'highcharts';
import addHighchartsMore from 'highcharts/highcharts-more';

addHighchartsMore(Highcharts);
```

**Comment by terryyylim** [comment]
Thank you for your reply! The error has disappeared, but the boxplot is still not showing, may I know if you could help me with the syntax for BoxPlot? I can't seem to find any documentation on how the syntax is supposed to be in the render method. Thank you! Also, this is an amazing package, really love it!!

**Comment by terryyylim** [comment]
bump, anyone can provide some sort of help here? thanks!!

**Comment by whawker** [comment]
I would suggesting looking at the Highcharts examples - the Box Plot series data needs to be an array of arrays.

See vanilla Highcharts example [here](http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/box-plot/)
And React JSX Highcharts examples [here](https://stackblitz.com/edit/box-plot-example?file=MyChart.js)

**Comment by terryyylim** [comment]
That'd worked!! Thanks so much, didn't notice the array was nested, my bad!! Cheers, and thank you for coming up with this package!
