### ISSUE TITLE
BarSeries not working as bar, instead shows column

### ISSUE THREAD

**Issue by sweetyv** [whawker/react-jsx-highcharts#9]
Hi, 

I am trying to work with BarSeries, but its showing columns instead. What could be the possible error?

**Comment by whawker** [comment]
Hi @sweetyv would you mind pasting in the code you're trying to render so I can help debug it?

**Comment by sweetyv** [comment]
Hi @whawker .. i added "inverted" to the BarSeries and now its working :)
Thank you very much. Really appreciate the quick response.

**Comment by whawker** [comment]
No worries, although I didn't really do anything! Glad you got it sorted.

P.s. If you're planning to use React JSX Highcharts on a publicly accessible website I'd love to see it in action. Would you be able to post a link if that is the case?

**Comment by sweetyv** [comment]
@whawker Thanks :) I am not sure if I can share the link but I will definitely try and ask the client.
