### ISSUE TITLE
AreaRange Series and Spiderweb chart problems

### ISSUE THREAD

**Issue by bonchevski** [whawker/react-jsx-highcharts#90]
Hey , so I've been using these charts in a react-jsx app . However when I have tried importing for example "AreaRangeSeries" from either highstock or highcharts-more and default from highcharts. They have not worked. I've been trying all types of things regarding implementing AreaRangeSeries ,however no luck, It only redirects me to see the issue #17 or #18 . 
I'm quite desperate, and no my json is correct the versions should be up to date etc. here's and example : 

```jsx
import React, { Component } from "react";
import Highcharts from "highcharts/highstock";
import {
  HighchartsStockChart,
  Chart,
  withHighcharts,
  XAxis,
  YAxis,
  Title,
  Legend,
  LineSeries,
  Navigator,
  RangeSelector,
  SplineSeries,
  AreaSeries,
  Tooltip
} from "react-jsx-highstock";

// import { createRandomData } from "../utils/data-helpers";

// ../utils/data-helpers
const createDataPoint = (time = Date.now(), magnitude = 1000, offset = 0) => {
  return [time + offset * magnitude, Math.round(Math.random() * 100 * 2) / 2];
};

const createRandomData = (time, magnitude) => {
  const data = [];

  for (let i = -99; i <= 0; i++) {
    data.push(createDataPoint(time, magnitude, i));
  }
  return data;
};

class VolatilityAndRisk extends Component {
  constructor(props) {
    super(props);

    this.state = {};
  }

  render() {
    const now = Date.now();
    const data = createRandomData(now, 1e7);

    const data2 = createRandomData(now, 1e7);
    return (
      <div>
        <HighchartsStockChart>
          <Chart zoomType="x" />
          <Title>First HighStock</Title>
          <Legend>
            <Legend.Title>Legend Title</Legend.Title>
          </Legend>
          
          <Tooltip />
          <XAxis>
            <XAxis.Title>XAxis Title</XAxis.Title>
          </XAxis>
          <YAxis id="price">
            <YAxis.Title>Price</YAxis.Title>
            <AreaRangeSeries id="portfolio" name="Basic Portfolio" data={data} />
            <SplineSeries id="BTC" name="BTC" data={data2} />
          </YAxis>
        
        </HighchartsStockChart>
      </div>
    );
  }
}

export default withHighcharts(VolatilityAndRisk, Highcharts);
```

**Comment by bonchevski** [comment]
So yeah basically It crashes completely whenever I try any type of Range series Regardless of the imports introduced

**Comment by whawker** [comment]
How are you importing Highcharts more? It should be like this

```js
import Highcharts from 'highcharts';
import addHighchartsMore from 'highcharts/highcharts-more';

addHighchartsMore(Highcharts);
```

**Comment by bonchevski** [comment]
Yep still not working, Will be back in an hour with some more code , Sorry for bothering :) ty for the quick reply

**Comment by bonchevski** [comment]
Okay so, this is the updated code 👍 

import React, { Component } from "react";
import Highcharts from "highcharts/highstock";
import {
  HighchartsStockChart,
  Chart,
  withHighcharts,
  XAxis,
  YAxis,
  Title,
  Legend,
  LineSeries,
  Navigator,
  RangeSelector,
  SplineSeries,
  AreaSeries,
  AreaRangeSeries,
  Tooltip
} from "react-jsx-highstock";
import addHighchartsMore from 'highcharts/highcharts-more';
// import { createRandomData } from "../utils/data-helpers";

// ../utils/data-helpers
const createDataPoint = (time = Date.now(), magnitude = 1000, offset = 0) => [
  time + offset * magnitude,
  Math.round(Math.random() * 100 * 2) / 2
];

const createRandomData = (time, magnitude) => {
  const data = [];

  for (let i = -99; i <= 0; i++) {
    data.push(createDataPoint(time, magnitude, i));
  }
  return data;
};

class VolatilityAndRisk extends Component {
  constructor(props) {
    super(props);

    this.state = {};
  }

  render() {
    const now = Date.now();
    const data = createRandomData(now, 1e7);

    const data2 = createRandomData(now, 1e7);
    return (
      <div>
        <HighchartsStockChart>
          <Chart zoomType="x" />
          <Title>First HighStock</Title>
          <Legend>
            <Legend.Title>Legend Title</Legend.Title>
          </Legend>

          <Tooltip shared />
          <XAxis>
            <XAxis.Title>XAxis Title</XAxis.Title>
          </XAxis>
          <YAxis id="price">
            <YAxis.Title>Price</YAxis.Title>
            <AreaRangeSeries id="portfolio" name="Basic Portfolio" data={data}>
              <SplineSeries id="BTC" name="BTC" data={data2} />
            </AreaRangeSeries>
          </YAxis>
        </HighchartsStockChart>
      </div>
    );
  }
}

export default withHighcharts(VolatilityAndRisk, Highcharts);

Sadly still doesn't work...

**Comment by whawker** [comment]
You've missed a line from my previous comment. You're not applying the Highcharts more module, after you import it.

You need to call it to extend Highcharts with extra functionality.

```js
addHighchartsMore(Highcharts);
````

**Comment by bonchevski** [comment]
Yeah it worked! Awesome, however it does not really... well display the arearange, any tips on the data for that? I'm suppposed to have my XAxis as datetime, and the arearange to be with a lineseries in it I have a screenshot:
![image](https://user-images.githubusercontent.com/35065347/38303308-5839f124-380e-11e8-821f-2b38259fe6ad.png)

**Comment by whawker** [comment]
Do you mean YAxis as datetime? Your XAxis (bottom axis) is already datetime.

**Comment by bonchevski** [comment]
This is only a Screenshot of our mock-up :D 
this is what happens with the code above 
![image](https://user-images.githubusercontent.com/35065347/38304442-2c1d19a0-3812-11e8-83fa-afaf373ff26d.png)

with the function for creating data the YAxis of the AreaRange doesn't show up instead only the YAxis LineSeries

**Comment by whawker** [comment]
AreaRange series require two Y points, as they define an area [see here](http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/arearange-line/)

The basic `createDataPoint` utility I provided in my examples only creates one Y point.

[Example here](https://stackblitz.com/edit/area-range-chart-example?file=MyChart.js)

P.s. You can't nest series within other series, it doesn't work like that, it depends on the data only.
