### ISSUE TITLE
Exporting an chart in styled mode results in blank image

### ISSUE THREAD

**Issue by DevsExMachina** [whawker/react-jsx-highcharts#97]
When using the CSS styled version of HighCharts - all (offline) export options give a blank (black) output where the chart should be.

My react component has these imports - 

import Highcharts from 'highcharts/js/highcharts'; // CSS STYLED VERSION
import applyExporting from 'highcharts/modules/exporting';
import applyOffline from 'highcharts/modules/offline-exporting';
import {HighchartsChart, Chart,withHighcharts,XAxis,YAxis,Legend,LineSeries,Title} from 'react-jsx-highcharts';

And calls these in the constructor

			applyExporting(Highcharts);
			applyOffline(Highcharts);

All exports are blank.

If I change the version of highcharts to the standard - everything works fine?

import Highcharts from 'highcharts';

Thanks in advance for the library and your help

**Comment by whawker** [comment]
Looks like you need to use the styled version of the export plugins (from the `/js/` folder)

```js
import applyExporting from 'highcharts/js/modules/exporting';
import applyOffline from 'highcharts/js/modules/offline-exporting';
```

[See here](https://github.com/highcharts/highcharts/issues/6307#issuecomment-304604505)

**Comment by shiraleeana** [comment]
Hello just wondering if there is a new solution for this since version 7, there is not separate set of `js/` files.
